// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const CreateManyFieldsResponseFieldsItemFieldMetaCheckboxValuesItem: core.serialization.ObjectSchema<
    serializers.documents.CreateManyFieldsResponseFieldsItemFieldMetaCheckboxValuesItem.Raw,
    Documenso.documents.CreateManyFieldsResponseFieldsItemFieldMetaCheckboxValuesItem
> = core.serialization.object({
    id: core.serialization.number(),
    checked: core.serialization.boolean(),
    value: core.serialization.string(),
});

export declare namespace CreateManyFieldsResponseFieldsItemFieldMetaCheckboxValuesItem {
    export interface Raw {
        id: number;
        checked: boolean;
        value: string;
    }
}
