// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";
import { GetFieldsResponseFieldMetaCheckbox } from "./GetFieldsResponseFieldMetaCheckbox.js";
import { GetFieldsResponseFieldMetaDate } from "./GetFieldsResponseFieldMetaDate.js";
import { GetFieldsResponseFieldMetaDropdown } from "./GetFieldsResponseFieldMetaDropdown.js";
import { GetFieldsResponseFieldMetaEmail } from "./GetFieldsResponseFieldMetaEmail.js";
import { GetFieldsResponseFieldMetaInitials } from "./GetFieldsResponseFieldMetaInitials.js";
import { GetFieldsResponseFieldMetaName } from "./GetFieldsResponseFieldMetaName.js";
import { GetFieldsResponseFieldMetaNumber } from "./GetFieldsResponseFieldMetaNumber.js";
import { GetFieldsResponseFieldMetaRadio } from "./GetFieldsResponseFieldMetaRadio.js";
import { GetFieldsResponseFieldMetaSignature } from "./GetFieldsResponseFieldMetaSignature.js";
import { GetFieldsResponseFieldMetaText } from "./GetFieldsResponseFieldMetaText.js";

export const GetFieldsResponseFieldMeta: core.serialization.Schema<
    serializers.documents.GetFieldsResponseFieldMeta.Raw,
    Documenso.documents.GetFieldsResponseFieldMeta
> = core.serialization
    .union("type", {
        signature: GetFieldsResponseFieldMetaSignature,
        initials: GetFieldsResponseFieldMetaInitials,
        name: GetFieldsResponseFieldMetaName,
        email: GetFieldsResponseFieldMetaEmail,
        date: GetFieldsResponseFieldMetaDate,
        text: GetFieldsResponseFieldMetaText,
        number: GetFieldsResponseFieldMetaNumber,
        radio: GetFieldsResponseFieldMetaRadio,
        checkbox: GetFieldsResponseFieldMetaCheckbox,
        dropdown: GetFieldsResponseFieldMetaDropdown,
    })
    .transform<Documenso.documents.GetFieldsResponseFieldMeta>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace GetFieldsResponseFieldMeta {
    export type Raw =
        | GetFieldsResponseFieldMeta.Signature
        | GetFieldsResponseFieldMeta.Initials
        | GetFieldsResponseFieldMeta.Name
        | GetFieldsResponseFieldMeta.Email
        | GetFieldsResponseFieldMeta.Date
        | GetFieldsResponseFieldMeta.Text
        | GetFieldsResponseFieldMeta.Number
        | GetFieldsResponseFieldMeta.Radio
        | GetFieldsResponseFieldMeta.Checkbox
        | GetFieldsResponseFieldMeta.Dropdown;

    export interface Signature extends GetFieldsResponseFieldMetaSignature.Raw {
        type: "signature";
    }

    export interface Initials extends GetFieldsResponseFieldMetaInitials.Raw {
        type: "initials";
    }

    export interface Name extends GetFieldsResponseFieldMetaName.Raw {
        type: "name";
    }

    export interface Email extends GetFieldsResponseFieldMetaEmail.Raw {
        type: "email";
    }

    export interface Date extends GetFieldsResponseFieldMetaDate.Raw {
        type: "date";
    }

    export interface Text extends GetFieldsResponseFieldMetaText.Raw {
        type: "text";
    }

    export interface Number extends GetFieldsResponseFieldMetaNumber.Raw {
        type: "number";
    }

    export interface Radio extends GetFieldsResponseFieldMetaRadio.Raw {
        type: "radio";
    }

    export interface Checkbox extends GetFieldsResponseFieldMetaCheckbox.Raw {
        type: "checkbox";
    }

    export interface Dropdown extends GetFieldsResponseFieldMetaDropdown.Raw {
        type: "dropdown";
    }
}
