// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const GetFieldsResponseFieldMetaInitialsTextAlign: core.serialization.Schema<
    serializers.documents.GetFieldsResponseFieldMetaInitialsTextAlign.Raw,
    Documenso.documents.GetFieldsResponseFieldMetaInitialsTextAlign
> = core.serialization.enum_(["left", "center", "right"]);

export declare namespace GetFieldsResponseFieldMetaInitialsTextAlign {
    export type Raw = "left" | "center" | "right";
}
