// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const UpdateManyFieldsResponseFieldsItemFieldMetaRadioDirection: core.serialization.Schema<
    serializers.documents.UpdateManyFieldsResponseFieldsItemFieldMetaRadioDirection.Raw,
    Documenso.documents.UpdateManyFieldsResponseFieldsItemFieldMetaRadioDirection
> = core.serialization.enum_(["vertical", "horizontal"]);

export declare namespace UpdateManyFieldsResponseFieldsItemFieldMetaRadioDirection {
    export type Raw = "vertical" | "horizontal";
}
