// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";
import { UpdateFieldsResponseFieldMetaCheckboxDirection } from "./UpdateFieldsResponseFieldMetaCheckboxDirection.js";
import { UpdateFieldsResponseFieldMetaCheckboxOverflow } from "./UpdateFieldsResponseFieldMetaCheckboxOverflow.js";
import { UpdateFieldsResponseFieldMetaCheckboxValuesItem } from "./UpdateFieldsResponseFieldMetaCheckboxValuesItem.js";

export const UpdateFieldsResponseFieldMetaCheckbox: core.serialization.ObjectSchema<
    serializers.documents.UpdateFieldsResponseFieldMetaCheckbox.Raw,
    Documenso.documents.UpdateFieldsResponseFieldMetaCheckbox
> = core.serialization.object({
    label: core.serialization.string().optional(),
    placeholder: core.serialization.string().optional(),
    required: core.serialization.boolean().optional(),
    readOnly: core.serialization.boolean().optional(),
    fontSize: core.serialization.number().optional(),
    overflow: UpdateFieldsResponseFieldMetaCheckboxOverflow.optional(),
    values: core.serialization.list(UpdateFieldsResponseFieldMetaCheckboxValuesItem).optional(),
    validationRule: core.serialization.string().optional(),
    validationLength: core.serialization.number().optional(),
    direction: UpdateFieldsResponseFieldMetaCheckboxDirection,
});

export declare namespace UpdateFieldsResponseFieldMetaCheckbox {
    export interface Raw {
        label?: string | null;
        placeholder?: string | null;
        required?: boolean | null;
        readOnly?: boolean | null;
        fontSize?: number | null;
        overflow?: UpdateFieldsResponseFieldMetaCheckboxOverflow.Raw | null;
        values?: UpdateFieldsResponseFieldMetaCheckboxValuesItem.Raw[] | null;
        validationRule?: string | null;
        validationLength?: number | null;
        direction: UpdateFieldsResponseFieldMetaCheckboxDirection.Raw;
    }
}
