// This file was auto-generated by Fern from our API Definition.

/** The vertical alignment of the text */
export const CreateFieldsResponseFieldMetaTextVerticalAlign = {
    Top: "top",
    Middle: "middle",
    Bottom: "bottom",
} as const;
export type CreateFieldsResponseFieldMetaTextVerticalAlign =
    (typeof CreateFieldsResponseFieldMetaTextVerticalAlign)[keyof typeof CreateFieldsResponseFieldMetaTextVerticalAlign];
