// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../index.js";

export type CreateManyFieldsResponseFieldsItemFieldMeta =
    | Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMeta.Signature
    | Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMeta.Initials
    | Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMeta.Name
    | Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMeta.Email
    | Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMeta.Date
    | Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMeta.Text
    | Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMeta.Number
    | Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMeta.Radio
    | Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMeta.Checkbox
    | Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMeta.Dropdown;

export namespace CreateManyFieldsResponseFieldsItemFieldMeta {
    export interface Signature extends Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaSignature {
        type: "signature";
    }

    export interface Initials extends Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaInitials {
        type: "initials";
    }

    export interface Name extends Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaName {
        type: "name";
    }

    export interface Email extends Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaEmail {
        type: "email";
    }

    export interface Date extends Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaDate {
        type: "date";
    }

    export interface Text extends Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaText {
        type: "text";
    }

    export interface Number extends Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaNumber {
        type: "number";
    }

    export interface Radio extends Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaRadio {
        type: "radio";
    }

    export interface Checkbox extends Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaCheckbox {
        type: "checkbox";
    }

    export interface Dropdown extends Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaDropdown {
        type: "dropdown";
    }
}
