// This file was auto-generated by Fern from our API Definition.

export const GetFieldsResponseFieldMetaNameOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type GetFieldsResponseFieldMetaNameOverflow =
    (typeof GetFieldsResponseFieldMetaNameOverflow)[keyof typeof GetFieldsResponseFieldMetaNameOverflow];
