// This file was auto-generated by Fern from our API Definition.

export const UpdateManyFieldsResponseFieldsItemFieldMetaCheckboxOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type UpdateManyFieldsResponseFieldsItemFieldMetaCheckboxOverflow =
    (typeof UpdateManyFieldsResponseFieldsItemFieldMetaCheckboxOverflow)[keyof typeof UpdateManyFieldsResponseFieldsItemFieldMetaCheckboxOverflow];
