// This file was auto-generated by Fern from our API Definition.

export const UpdateFieldsResponseFieldMetaSignatureOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type UpdateFieldsResponseFieldMetaSignatureOverflow =
    (typeof UpdateFieldsResponseFieldMetaSignatureOverflow)[keyof typeof UpdateFieldsResponseFieldMetaSignatureOverflow];
