// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../index.js";

export interface EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaEmail {
    label?: string;
    placeholder?: string;
    required?: boolean;
    readOnly?: boolean;
    fontSize?: number;
    overflow: Documenso.EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaEmailOverflow;
    textAlign?: Documenso.EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaEmailTextAlign;
}
