// This file was auto-generated by Fern from our API Definition.

export const EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaEmailOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaEmailOverflow =
    (typeof EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaEmailOverflow)[keyof typeof EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaEmailOverflow];
