// This file was auto-generated by Fern from our API Definition.

/** The vertical alignment of the text */
export const EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaNumberVerticalAlign = {
    Top: "top",
    Middle: "middle",
    Bottom: "bottom",
} as const;
export type EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaNumberVerticalAlign =
    (typeof EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaNumberVerticalAlign)[keyof typeof EnvelopeGetManyEnvelopeResponseDataItemFieldsItemFieldMetaNumberVerticalAlign];
