// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../index.js";

export interface EnvelopeGetManyEnvelopeResponseDataItemAuthOptions {
    globalAccessAuth: Documenso.EnvelopeGetManyEnvelopeResponseDataItemAuthOptionsGlobalAccessAuthItem[];
    globalActionAuth: Documenso.EnvelopeGetManyEnvelopeResponseDataItemAuthOptionsGlobalActionAuthItem[];
}
