// This file was auto-generated by Fern from our API Definition.

export const EnvelopeGetManyEnvelopeResponseDataItemDocumentMetaSigningOrder = {
    Parallel: "PARALLEL",
    Sequential: "SEQUENTIAL",
} as const;
export type EnvelopeGetManyEnvelopeResponseDataItemDocumentMetaSigningOrder =
    (typeof EnvelopeGetManyEnvelopeResponseDataItemDocumentMetaSigningOrder)[keyof typeof EnvelopeGetManyEnvelopeResponseDataItemDocumentMetaSigningOrder];
