// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../index.js";

export interface EnvelopeAuditLogFindEnvelopeResponseDataItem {
    id: string;
    createdAt: string;
    envelopeId: string;
    name?: string | null;
    email?: string | null;
    userId?: number | null;
    userAgent?: string | null;
    ipAddress?: string | null;
    type?: "ENVELOPE_ITEM_CREATED";
    data?: Documenso.EnvelopeAuditLogFindEnvelopeResponseDataItemData;
}
