// This file was auto-generated by Fern from our API Definition.

export const FindTemplatesResponseDataItemFieldsItemFieldMetaSignatureOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type FindTemplatesResponseDataItemFieldsItemFieldMetaSignatureOverflow =
    (typeof FindTemplatesResponseDataItemFieldsItemFieldMetaSignatureOverflow)[keyof typeof FindTemplatesResponseDataItemFieldsItemFieldMetaSignatureOverflow];
