// This file was auto-generated by Fern from our API Definition.

export const FindTemplatesResponseDataItemFieldsItemFieldMetaTextOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type FindTemplatesResponseDataItemFieldsItemFieldMetaTextOverflow =
    (typeof FindTemplatesResponseDataItemFieldsItemFieldMetaTextOverflow)[keyof typeof FindTemplatesResponseDataItemFieldsItemFieldMetaTextOverflow];
