// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../index.js";

export interface GetTemplatesResponse {
    type: Documenso.GetTemplatesResponseType;
    visibility: Documenso.GetTemplatesResponseVisibility;
    id: number;
    externalId: string | null;
    title: string;
    userId: number;
    teamId: number;
    authOptions: Documenso.GetTemplatesResponseAuthOptions | null;
    createdAt: string;
    updatedAt: string;
    publicTitle: string;
    publicDescription: string;
    folderId: string | null;
    envelopeId: string;
    templateDocumentDataId: string;
    templateDocumentData: Documenso.GetTemplatesResponseTemplateDocumentData;
    templateMeta: Documenso.GetTemplatesResponseTemplateMeta;
    directLink: Documenso.GetTemplatesResponseDirectLink | null;
    user: Documenso.GetTemplatesResponseUser;
    recipients: Documenso.GetTemplatesResponseRecipientsItem[];
    fields: Documenso.GetTemplatesResponseFieldsItem[];
    folder: Documenso.GetTemplatesResponseFolder | null;
    envelopeItems: Documenso.GetTemplatesResponseEnvelopeItemsItem[];
}
