// This file was auto-generated by Fern from our API Definition.

export const UpdateTemplatesRequestDataVisibility = {
    Everyone: "EVERYONE",
    ManagerAndAbove: "MANAGER_AND_ABOVE",
    Admin: "ADMIN",
} as const;
export type UpdateTemplatesRequestDataVisibility =
    (typeof UpdateTemplatesRequestDataVisibility)[keyof typeof UpdateTemplatesRequestDataVisibility];
