// This file was auto-generated by Fern from our API Definition.

export const UseTemplatesResponseRecipientsItemSigningStatus = {
    NotSigned: "NOT_SIGNED",
    Signed: "SIGNED",
    Rejected: "REJECTED",
} as const;
export type UseTemplatesResponseRecipientsItemSigningStatus =
    (typeof UseTemplatesResponseRecipientsItemSigningStatus)[keyof typeof UseTemplatesResponseRecipientsItemSigningStatus];
