// This file was auto-generated by Fern from our API Definition.

export const UseTemplatesResponseDocumentMetaEnvelopeExpirationPeriodAmountUnit = {
    Day: "day",
    Week: "week",
    Month: "month",
    Year: "year",
} as const;
export type UseTemplatesResponseDocumentMetaEnvelopeExpirationPeriodAmountUnit =
    (typeof UseTemplatesResponseDocumentMetaEnvelopeExpirationPeriodAmountUnit)[keyof typeof UseTemplatesResponseDocumentMetaEnvelopeExpirationPeriodAmountUnit];
