// This file was auto-generated by Fern from our API Definition.

/** The distribution method to use when sending the document to the recipients. */
export const UseTemplatesRequestOverrideDistributionMethod = {
    Email: "EMAIL",
    None: "NONE",
} as const;
export type UseTemplatesRequestOverrideDistributionMethod =
    (typeof UseTemplatesRequestOverrideDistributionMethod)[keyof typeof UseTemplatesRequestOverrideDistributionMethod];
