// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const UpdateManyItemsRequestDataItem: core.serialization.ObjectSchema<
    serializers.envelopes.UpdateManyItemsRequestDataItem.Raw,
    Documenso.envelopes.UpdateManyItemsRequestDataItem
> = core.serialization.object({
    envelopeItemId: core.serialization.string(),
    order: core.serialization.number().optional(),
    title: core.serialization.string().optional(),
});

export declare namespace UpdateManyItemsRequestDataItem {
    export interface Raw {
        envelopeItemId: string;
        order?: number | null;
        title?: string | null;
    }
}
