/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { DocumensoError } from "./documensoerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type DocumentDownloadBetaInternalServerErrorIssue = {
  message: string;
};

/**
 * Internal server error
 */
export type DocumentDownloadBetaInternalServerErrorData = {
  message: string;
  code: string;
  issues?: Array<DocumentDownloadBetaInternalServerErrorIssue> | undefined;
};

/**
 * Internal server error
 */
export class DocumentDownloadBetaInternalServerError extends DocumensoError {
  code: string;
  issues?: Array<DocumentDownloadBetaInternalServerErrorIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: DocumentDownloadBetaInternalServerErrorData;

  constructor(
    err: DocumentDownloadBetaInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "DocumentDownloadBetaInternalServerError";
  }
}

export type DocumentDownloadBetaNotFoundIssue = {
  message: string;
};

/**
 * Not found
 */
export type DocumentDownloadBetaNotFoundErrorData = {
  message: string;
  code: string;
  issues?: Array<DocumentDownloadBetaNotFoundIssue> | undefined;
};

/**
 * Not found
 */
export class DocumentDownloadBetaNotFoundError extends DocumensoError {
  code: string;
  issues?: Array<DocumentDownloadBetaNotFoundIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: DocumentDownloadBetaNotFoundErrorData;

  constructor(
    err: DocumentDownloadBetaNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "DocumentDownloadBetaNotFoundError";
  }
}

export type DocumentDownloadBetaForbiddenIssue = {
  message: string;
};

/**
 * Insufficient access
 */
export type DocumentDownloadBetaForbiddenErrorData = {
  message: string;
  code: string;
  issues?: Array<DocumentDownloadBetaForbiddenIssue> | undefined;
};

/**
 * Insufficient access
 */
export class DocumentDownloadBetaForbiddenError extends DocumensoError {
  code: string;
  issues?: Array<DocumentDownloadBetaForbiddenIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: DocumentDownloadBetaForbiddenErrorData;

  constructor(
    err: DocumentDownloadBetaForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "DocumentDownloadBetaForbiddenError";
  }
}

export type DocumentDownloadBetaUnauthorizedIssue = {
  message: string;
};

/**
 * Authorization not provided
 */
export type DocumentDownloadBetaUnauthorizedErrorData = {
  message: string;
  code: string;
  issues?: Array<DocumentDownloadBetaUnauthorizedIssue> | undefined;
};

/**
 * Authorization not provided
 */
export class DocumentDownloadBetaUnauthorizedError extends DocumensoError {
  code: string;
  issues?: Array<DocumentDownloadBetaUnauthorizedIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: DocumentDownloadBetaUnauthorizedErrorData;

  constructor(
    err: DocumentDownloadBetaUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "DocumentDownloadBetaUnauthorizedError";
  }
}

export type DocumentDownloadBetaBadRequestIssue = {
  message: string;
};

/**
 * Invalid input data
 */
export type DocumentDownloadBetaBadRequestErrorData = {
  message: string;
  code: string;
  issues?: Array<DocumentDownloadBetaBadRequestIssue> | undefined;
};

/**
 * Invalid input data
 */
export class DocumentDownloadBetaBadRequestError extends DocumensoError {
  code: string;
  issues?: Array<DocumentDownloadBetaBadRequestIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: DocumentDownloadBetaBadRequestErrorData;

  constructor(
    err: DocumentDownloadBetaBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "DocumentDownloadBetaBadRequestError";
  }
}

/** @internal */
export const DocumentDownloadBetaInternalServerErrorIssue$inboundSchema:
  z.ZodType<
    DocumentDownloadBetaInternalServerErrorIssue,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });
/** @internal */
export type DocumentDownloadBetaInternalServerErrorIssue$Outbound = {
  message: string;
};

/** @internal */
export const DocumentDownloadBetaInternalServerErrorIssue$outboundSchema:
  z.ZodType<
    DocumentDownloadBetaInternalServerErrorIssue$Outbound,
    z.ZodTypeDef,
    DocumentDownloadBetaInternalServerErrorIssue
  > = z.object({
    message: z.string(),
  });

export function documentDownloadBetaInternalServerErrorIssueToJSON(
  documentDownloadBetaInternalServerErrorIssue:
    DocumentDownloadBetaInternalServerErrorIssue,
): string {
  return JSON.stringify(
    DocumentDownloadBetaInternalServerErrorIssue$outboundSchema.parse(
      documentDownloadBetaInternalServerErrorIssue,
    ),
  );
}
export function documentDownloadBetaInternalServerErrorIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  DocumentDownloadBetaInternalServerErrorIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DocumentDownloadBetaInternalServerErrorIssue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DocumentDownloadBetaInternalServerErrorIssue' from JSON`,
  );
}

/** @internal */
export const DocumentDownloadBetaInternalServerError$inboundSchema: z.ZodType<
  DocumentDownloadBetaInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => DocumentDownloadBetaInternalServerErrorIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DocumentDownloadBetaInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DocumentDownloadBetaInternalServerError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<DocumentDownloadBetaInternalServerErrorIssue$Outbound>
    | undefined;
};

/** @internal */
export const DocumentDownloadBetaInternalServerError$outboundSchema: z.ZodType<
  DocumentDownloadBetaInternalServerError$Outbound,
  z.ZodTypeDef,
  DocumentDownloadBetaInternalServerError
> = z.instanceof(DocumentDownloadBetaInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => DocumentDownloadBetaInternalServerErrorIssue$outboundSchema),
    ).optional(),
  }));

/** @internal */
export const DocumentDownloadBetaNotFoundIssue$inboundSchema: z.ZodType<
  DocumentDownloadBetaNotFoundIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type DocumentDownloadBetaNotFoundIssue$Outbound = {
  message: string;
};

/** @internal */
export const DocumentDownloadBetaNotFoundIssue$outboundSchema: z.ZodType<
  DocumentDownloadBetaNotFoundIssue$Outbound,
  z.ZodTypeDef,
  DocumentDownloadBetaNotFoundIssue
> = z.object({
  message: z.string(),
});

export function documentDownloadBetaNotFoundIssueToJSON(
  documentDownloadBetaNotFoundIssue: DocumentDownloadBetaNotFoundIssue,
): string {
  return JSON.stringify(
    DocumentDownloadBetaNotFoundIssue$outboundSchema.parse(
      documentDownloadBetaNotFoundIssue,
    ),
  );
}
export function documentDownloadBetaNotFoundIssueFromJSON(
  jsonString: string,
): SafeParseResult<DocumentDownloadBetaNotFoundIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentDownloadBetaNotFoundIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentDownloadBetaNotFoundIssue' from JSON`,
  );
}

/** @internal */
export const DocumentDownloadBetaNotFoundError$inboundSchema: z.ZodType<
  DocumentDownloadBetaNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(z.lazy(() => DocumentDownloadBetaNotFoundIssue$inboundSchema))
    .optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DocumentDownloadBetaNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DocumentDownloadBetaNotFoundError$Outbound = {
  message: string;
  code: string;
  issues?: Array<DocumentDownloadBetaNotFoundIssue$Outbound> | undefined;
};

/** @internal */
export const DocumentDownloadBetaNotFoundError$outboundSchema: z.ZodType<
  DocumentDownloadBetaNotFoundError$Outbound,
  z.ZodTypeDef,
  DocumentDownloadBetaNotFoundError
> = z.instanceof(DocumentDownloadBetaNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => DocumentDownloadBetaNotFoundIssue$outboundSchema),
    ).optional(),
  }));

/** @internal */
export const DocumentDownloadBetaForbiddenIssue$inboundSchema: z.ZodType<
  DocumentDownloadBetaForbiddenIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type DocumentDownloadBetaForbiddenIssue$Outbound = {
  message: string;
};

/** @internal */
export const DocumentDownloadBetaForbiddenIssue$outboundSchema: z.ZodType<
  DocumentDownloadBetaForbiddenIssue$Outbound,
  z.ZodTypeDef,
  DocumentDownloadBetaForbiddenIssue
> = z.object({
  message: z.string(),
});

export function documentDownloadBetaForbiddenIssueToJSON(
  documentDownloadBetaForbiddenIssue: DocumentDownloadBetaForbiddenIssue,
): string {
  return JSON.stringify(
    DocumentDownloadBetaForbiddenIssue$outboundSchema.parse(
      documentDownloadBetaForbiddenIssue,
    ),
  );
}
export function documentDownloadBetaForbiddenIssueFromJSON(
  jsonString: string,
): SafeParseResult<DocumentDownloadBetaForbiddenIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DocumentDownloadBetaForbiddenIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentDownloadBetaForbiddenIssue' from JSON`,
  );
}

/** @internal */
export const DocumentDownloadBetaForbiddenError$inboundSchema: z.ZodType<
  DocumentDownloadBetaForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => DocumentDownloadBetaForbiddenIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DocumentDownloadBetaForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DocumentDownloadBetaForbiddenError$Outbound = {
  message: string;
  code: string;
  issues?: Array<DocumentDownloadBetaForbiddenIssue$Outbound> | undefined;
};

/** @internal */
export const DocumentDownloadBetaForbiddenError$outboundSchema: z.ZodType<
  DocumentDownloadBetaForbiddenError$Outbound,
  z.ZodTypeDef,
  DocumentDownloadBetaForbiddenError
> = z.instanceof(DocumentDownloadBetaForbiddenError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => DocumentDownloadBetaForbiddenIssue$outboundSchema),
    ).optional(),
  }));

/** @internal */
export const DocumentDownloadBetaUnauthorizedIssue$inboundSchema: z.ZodType<
  DocumentDownloadBetaUnauthorizedIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type DocumentDownloadBetaUnauthorizedIssue$Outbound = {
  message: string;
};

/** @internal */
export const DocumentDownloadBetaUnauthorizedIssue$outboundSchema: z.ZodType<
  DocumentDownloadBetaUnauthorizedIssue$Outbound,
  z.ZodTypeDef,
  DocumentDownloadBetaUnauthorizedIssue
> = z.object({
  message: z.string(),
});

export function documentDownloadBetaUnauthorizedIssueToJSON(
  documentDownloadBetaUnauthorizedIssue: DocumentDownloadBetaUnauthorizedIssue,
): string {
  return JSON.stringify(
    DocumentDownloadBetaUnauthorizedIssue$outboundSchema.parse(
      documentDownloadBetaUnauthorizedIssue,
    ),
  );
}
export function documentDownloadBetaUnauthorizedIssueFromJSON(
  jsonString: string,
): SafeParseResult<DocumentDownloadBetaUnauthorizedIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DocumentDownloadBetaUnauthorizedIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentDownloadBetaUnauthorizedIssue' from JSON`,
  );
}

/** @internal */
export const DocumentDownloadBetaUnauthorizedError$inboundSchema: z.ZodType<
  DocumentDownloadBetaUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => DocumentDownloadBetaUnauthorizedIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DocumentDownloadBetaUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DocumentDownloadBetaUnauthorizedError$Outbound = {
  message: string;
  code: string;
  issues?: Array<DocumentDownloadBetaUnauthorizedIssue$Outbound> | undefined;
};

/** @internal */
export const DocumentDownloadBetaUnauthorizedError$outboundSchema: z.ZodType<
  DocumentDownloadBetaUnauthorizedError$Outbound,
  z.ZodTypeDef,
  DocumentDownloadBetaUnauthorizedError
> = z.instanceof(DocumentDownloadBetaUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => DocumentDownloadBetaUnauthorizedIssue$outboundSchema),
    ).optional(),
  }));

/** @internal */
export const DocumentDownloadBetaBadRequestIssue$inboundSchema: z.ZodType<
  DocumentDownloadBetaBadRequestIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type DocumentDownloadBetaBadRequestIssue$Outbound = {
  message: string;
};

/** @internal */
export const DocumentDownloadBetaBadRequestIssue$outboundSchema: z.ZodType<
  DocumentDownloadBetaBadRequestIssue$Outbound,
  z.ZodTypeDef,
  DocumentDownloadBetaBadRequestIssue
> = z.object({
  message: z.string(),
});

export function documentDownloadBetaBadRequestIssueToJSON(
  documentDownloadBetaBadRequestIssue: DocumentDownloadBetaBadRequestIssue,
): string {
  return JSON.stringify(
    DocumentDownloadBetaBadRequestIssue$outboundSchema.parse(
      documentDownloadBetaBadRequestIssue,
    ),
  );
}
export function documentDownloadBetaBadRequestIssueFromJSON(
  jsonString: string,
): SafeParseResult<DocumentDownloadBetaBadRequestIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      DocumentDownloadBetaBadRequestIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentDownloadBetaBadRequestIssue' from JSON`,
  );
}

/** @internal */
export const DocumentDownloadBetaBadRequestError$inboundSchema: z.ZodType<
  DocumentDownloadBetaBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => DocumentDownloadBetaBadRequestIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DocumentDownloadBetaBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DocumentDownloadBetaBadRequestError$Outbound = {
  message: string;
  code: string;
  issues?: Array<DocumentDownloadBetaBadRequestIssue$Outbound> | undefined;
};

/** @internal */
export const DocumentDownloadBetaBadRequestError$outboundSchema: z.ZodType<
  DocumentDownloadBetaBadRequestError$Outbound,
  z.ZodTypeDef,
  DocumentDownloadBetaBadRequestError
> = z.instanceof(DocumentDownloadBetaBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => DocumentDownloadBetaBadRequestIssue$outboundSchema),
    ).optional(),
  }));
