/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { DocumensoError } from "./documensoerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type EnvelopeRecipientGetInternalServerErrorIssue = {
  message: string;
};

/**
 * Internal server error
 */
export type EnvelopeRecipientGetInternalServerErrorData = {
  message: string;
  code: string;
  issues?: Array<EnvelopeRecipientGetInternalServerErrorIssue> | undefined;
};

/**
 * Internal server error
 */
export class EnvelopeRecipientGetInternalServerError extends DocumensoError {
  code: string;
  issues?: Array<EnvelopeRecipientGetInternalServerErrorIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: EnvelopeRecipientGetInternalServerErrorData;

  constructor(
    err: EnvelopeRecipientGetInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "EnvelopeRecipientGetInternalServerError";
  }
}

export type EnvelopeRecipientGetNotFoundIssue = {
  message: string;
};

/**
 * Not found
 */
export type EnvelopeRecipientGetNotFoundErrorData = {
  message: string;
  code: string;
  issues?: Array<EnvelopeRecipientGetNotFoundIssue> | undefined;
};

/**
 * Not found
 */
export class EnvelopeRecipientGetNotFoundError extends DocumensoError {
  code: string;
  issues?: Array<EnvelopeRecipientGetNotFoundIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: EnvelopeRecipientGetNotFoundErrorData;

  constructor(
    err: EnvelopeRecipientGetNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "EnvelopeRecipientGetNotFoundError";
  }
}

export type EnvelopeRecipientGetForbiddenIssue = {
  message: string;
};

/**
 * Insufficient access
 */
export type EnvelopeRecipientGetForbiddenErrorData = {
  message: string;
  code: string;
  issues?: Array<EnvelopeRecipientGetForbiddenIssue> | undefined;
};

/**
 * Insufficient access
 */
export class EnvelopeRecipientGetForbiddenError extends DocumensoError {
  code: string;
  issues?: Array<EnvelopeRecipientGetForbiddenIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: EnvelopeRecipientGetForbiddenErrorData;

  constructor(
    err: EnvelopeRecipientGetForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "EnvelopeRecipientGetForbiddenError";
  }
}

export type EnvelopeRecipientGetUnauthorizedIssue = {
  message: string;
};

/**
 * Authorization not provided
 */
export type EnvelopeRecipientGetUnauthorizedErrorData = {
  message: string;
  code: string;
  issues?: Array<EnvelopeRecipientGetUnauthorizedIssue> | undefined;
};

/**
 * Authorization not provided
 */
export class EnvelopeRecipientGetUnauthorizedError extends DocumensoError {
  code: string;
  issues?: Array<EnvelopeRecipientGetUnauthorizedIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: EnvelopeRecipientGetUnauthorizedErrorData;

  constructor(
    err: EnvelopeRecipientGetUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "EnvelopeRecipientGetUnauthorizedError";
  }
}

export type EnvelopeRecipientGetBadRequestIssue = {
  message: string;
};

/**
 * Invalid input data
 */
export type EnvelopeRecipientGetBadRequestErrorData = {
  message: string;
  code: string;
  issues?: Array<EnvelopeRecipientGetBadRequestIssue> | undefined;
};

/**
 * Invalid input data
 */
export class EnvelopeRecipientGetBadRequestError extends DocumensoError {
  code: string;
  issues?: Array<EnvelopeRecipientGetBadRequestIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: EnvelopeRecipientGetBadRequestErrorData;

  constructor(
    err: EnvelopeRecipientGetBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "EnvelopeRecipientGetBadRequestError";
  }
}

/** @internal */
export const EnvelopeRecipientGetInternalServerErrorIssue$inboundSchema:
  z.ZodType<
    EnvelopeRecipientGetInternalServerErrorIssue,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });
/** @internal */
export type EnvelopeRecipientGetInternalServerErrorIssue$Outbound = {
  message: string;
};

/** @internal */
export const EnvelopeRecipientGetInternalServerErrorIssue$outboundSchema:
  z.ZodType<
    EnvelopeRecipientGetInternalServerErrorIssue$Outbound,
    z.ZodTypeDef,
    EnvelopeRecipientGetInternalServerErrorIssue
  > = z.object({
    message: z.string(),
  });

export function envelopeRecipientGetInternalServerErrorIssueToJSON(
  envelopeRecipientGetInternalServerErrorIssue:
    EnvelopeRecipientGetInternalServerErrorIssue,
): string {
  return JSON.stringify(
    EnvelopeRecipientGetInternalServerErrorIssue$outboundSchema.parse(
      envelopeRecipientGetInternalServerErrorIssue,
    ),
  );
}
export function envelopeRecipientGetInternalServerErrorIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  EnvelopeRecipientGetInternalServerErrorIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientGetInternalServerErrorIssue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EnvelopeRecipientGetInternalServerErrorIssue' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientGetInternalServerError$inboundSchema: z.ZodType<
  EnvelopeRecipientGetInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => EnvelopeRecipientGetInternalServerErrorIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new EnvelopeRecipientGetInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type EnvelopeRecipientGetInternalServerError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<EnvelopeRecipientGetInternalServerErrorIssue$Outbound>
    | undefined;
};

/** @internal */
export const EnvelopeRecipientGetInternalServerError$outboundSchema: z.ZodType<
  EnvelopeRecipientGetInternalServerError$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientGetInternalServerError
> = z.instanceof(EnvelopeRecipientGetInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => EnvelopeRecipientGetInternalServerErrorIssue$outboundSchema),
    ).optional(),
  }));

/** @internal */
export const EnvelopeRecipientGetNotFoundIssue$inboundSchema: z.ZodType<
  EnvelopeRecipientGetNotFoundIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type EnvelopeRecipientGetNotFoundIssue$Outbound = {
  message: string;
};

/** @internal */
export const EnvelopeRecipientGetNotFoundIssue$outboundSchema: z.ZodType<
  EnvelopeRecipientGetNotFoundIssue$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientGetNotFoundIssue
> = z.object({
  message: z.string(),
});

export function envelopeRecipientGetNotFoundIssueToJSON(
  envelopeRecipientGetNotFoundIssue: EnvelopeRecipientGetNotFoundIssue,
): string {
  return JSON.stringify(
    EnvelopeRecipientGetNotFoundIssue$outboundSchema.parse(
      envelopeRecipientGetNotFoundIssue,
    ),
  );
}
export function envelopeRecipientGetNotFoundIssueFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientGetNotFoundIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeRecipientGetNotFoundIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientGetNotFoundIssue' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientGetNotFoundError$inboundSchema: z.ZodType<
  EnvelopeRecipientGetNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(z.lazy(() => EnvelopeRecipientGetNotFoundIssue$inboundSchema))
    .optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new EnvelopeRecipientGetNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type EnvelopeRecipientGetNotFoundError$Outbound = {
  message: string;
  code: string;
  issues?: Array<EnvelopeRecipientGetNotFoundIssue$Outbound> | undefined;
};

/** @internal */
export const EnvelopeRecipientGetNotFoundError$outboundSchema: z.ZodType<
  EnvelopeRecipientGetNotFoundError$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientGetNotFoundError
> = z.instanceof(EnvelopeRecipientGetNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => EnvelopeRecipientGetNotFoundIssue$outboundSchema),
    ).optional(),
  }));

/** @internal */
export const EnvelopeRecipientGetForbiddenIssue$inboundSchema: z.ZodType<
  EnvelopeRecipientGetForbiddenIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type EnvelopeRecipientGetForbiddenIssue$Outbound = {
  message: string;
};

/** @internal */
export const EnvelopeRecipientGetForbiddenIssue$outboundSchema: z.ZodType<
  EnvelopeRecipientGetForbiddenIssue$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientGetForbiddenIssue
> = z.object({
  message: z.string(),
});

export function envelopeRecipientGetForbiddenIssueToJSON(
  envelopeRecipientGetForbiddenIssue: EnvelopeRecipientGetForbiddenIssue,
): string {
  return JSON.stringify(
    EnvelopeRecipientGetForbiddenIssue$outboundSchema.parse(
      envelopeRecipientGetForbiddenIssue,
    ),
  );
}
export function envelopeRecipientGetForbiddenIssueFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientGetForbiddenIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientGetForbiddenIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientGetForbiddenIssue' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientGetForbiddenError$inboundSchema: z.ZodType<
  EnvelopeRecipientGetForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => EnvelopeRecipientGetForbiddenIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new EnvelopeRecipientGetForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type EnvelopeRecipientGetForbiddenError$Outbound = {
  message: string;
  code: string;
  issues?: Array<EnvelopeRecipientGetForbiddenIssue$Outbound> | undefined;
};

/** @internal */
export const EnvelopeRecipientGetForbiddenError$outboundSchema: z.ZodType<
  EnvelopeRecipientGetForbiddenError$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientGetForbiddenError
> = z.instanceof(EnvelopeRecipientGetForbiddenError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => EnvelopeRecipientGetForbiddenIssue$outboundSchema),
    ).optional(),
  }));

/** @internal */
export const EnvelopeRecipientGetUnauthorizedIssue$inboundSchema: z.ZodType<
  EnvelopeRecipientGetUnauthorizedIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type EnvelopeRecipientGetUnauthorizedIssue$Outbound = {
  message: string;
};

/** @internal */
export const EnvelopeRecipientGetUnauthorizedIssue$outboundSchema: z.ZodType<
  EnvelopeRecipientGetUnauthorizedIssue$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientGetUnauthorizedIssue
> = z.object({
  message: z.string(),
});

export function envelopeRecipientGetUnauthorizedIssueToJSON(
  envelopeRecipientGetUnauthorizedIssue: EnvelopeRecipientGetUnauthorizedIssue,
): string {
  return JSON.stringify(
    EnvelopeRecipientGetUnauthorizedIssue$outboundSchema.parse(
      envelopeRecipientGetUnauthorizedIssue,
    ),
  );
}
export function envelopeRecipientGetUnauthorizedIssueFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientGetUnauthorizedIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientGetUnauthorizedIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientGetUnauthorizedIssue' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientGetUnauthorizedError$inboundSchema: z.ZodType<
  EnvelopeRecipientGetUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => EnvelopeRecipientGetUnauthorizedIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new EnvelopeRecipientGetUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type EnvelopeRecipientGetUnauthorizedError$Outbound = {
  message: string;
  code: string;
  issues?: Array<EnvelopeRecipientGetUnauthorizedIssue$Outbound> | undefined;
};

/** @internal */
export const EnvelopeRecipientGetUnauthorizedError$outboundSchema: z.ZodType<
  EnvelopeRecipientGetUnauthorizedError$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientGetUnauthorizedError
> = z.instanceof(EnvelopeRecipientGetUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => EnvelopeRecipientGetUnauthorizedIssue$outboundSchema),
    ).optional(),
  }));

/** @internal */
export const EnvelopeRecipientGetBadRequestIssue$inboundSchema: z.ZodType<
  EnvelopeRecipientGetBadRequestIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type EnvelopeRecipientGetBadRequestIssue$Outbound = {
  message: string;
};

/** @internal */
export const EnvelopeRecipientGetBadRequestIssue$outboundSchema: z.ZodType<
  EnvelopeRecipientGetBadRequestIssue$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientGetBadRequestIssue
> = z.object({
  message: z.string(),
});

export function envelopeRecipientGetBadRequestIssueToJSON(
  envelopeRecipientGetBadRequestIssue: EnvelopeRecipientGetBadRequestIssue,
): string {
  return JSON.stringify(
    EnvelopeRecipientGetBadRequestIssue$outboundSchema.parse(
      envelopeRecipientGetBadRequestIssue,
    ),
  );
}
export function envelopeRecipientGetBadRequestIssueFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientGetBadRequestIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientGetBadRequestIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientGetBadRequestIssue' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientGetBadRequestError$inboundSchema: z.ZodType<
  EnvelopeRecipientGetBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => EnvelopeRecipientGetBadRequestIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new EnvelopeRecipientGetBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type EnvelopeRecipientGetBadRequestError$Outbound = {
  message: string;
  code: string;
  issues?: Array<EnvelopeRecipientGetBadRequestIssue$Outbound> | undefined;
};

/** @internal */
export const EnvelopeRecipientGetBadRequestError$outboundSchema: z.ZodType<
  EnvelopeRecipientGetBadRequestError$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientGetBadRequestError
> = z.instanceof(EnvelopeRecipientGetBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => EnvelopeRecipientGetBadRequestIssue$outboundSchema),
    ).optional(),
  }));
