/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { DocumensoError } from "./documensoerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type FieldDeleteTemplateFieldInternalServerErrorIssue = {
  message: string;
};

/**
 * Internal server error
 */
export type FieldDeleteTemplateFieldInternalServerErrorData = {
  message: string;
  code: string;
  issues?: Array<FieldDeleteTemplateFieldInternalServerErrorIssue> | undefined;
};

/**
 * Internal server error
 */
export class FieldDeleteTemplateFieldInternalServerError
  extends DocumensoError
{
  code: string;
  issues?: Array<FieldDeleteTemplateFieldInternalServerErrorIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: FieldDeleteTemplateFieldInternalServerErrorData;

  constructor(
    err: FieldDeleteTemplateFieldInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "FieldDeleteTemplateFieldInternalServerError";
  }
}

export type FieldDeleteTemplateFieldForbiddenIssue = {
  message: string;
};

/**
 * Insufficient access
 */
export type FieldDeleteTemplateFieldForbiddenErrorData = {
  message: string;
  code: string;
  issues?: Array<FieldDeleteTemplateFieldForbiddenIssue> | undefined;
};

/**
 * Insufficient access
 */
export class FieldDeleteTemplateFieldForbiddenError extends DocumensoError {
  code: string;
  issues?: Array<FieldDeleteTemplateFieldForbiddenIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: FieldDeleteTemplateFieldForbiddenErrorData;

  constructor(
    err: FieldDeleteTemplateFieldForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "FieldDeleteTemplateFieldForbiddenError";
  }
}

export type FieldDeleteTemplateFieldUnauthorizedIssue = {
  message: string;
};

/**
 * Authorization not provided
 */
export type FieldDeleteTemplateFieldUnauthorizedErrorData = {
  message: string;
  code: string;
  issues?: Array<FieldDeleteTemplateFieldUnauthorizedIssue> | undefined;
};

/**
 * Authorization not provided
 */
export class FieldDeleteTemplateFieldUnauthorizedError extends DocumensoError {
  code: string;
  issues?: Array<FieldDeleteTemplateFieldUnauthorizedIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: FieldDeleteTemplateFieldUnauthorizedErrorData;

  constructor(
    err: FieldDeleteTemplateFieldUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "FieldDeleteTemplateFieldUnauthorizedError";
  }
}

export type FieldDeleteTemplateFieldBadRequestIssue = {
  message: string;
};

/**
 * Invalid input data
 */
export type FieldDeleteTemplateFieldBadRequestErrorData = {
  message: string;
  code: string;
  issues?: Array<FieldDeleteTemplateFieldBadRequestIssue> | undefined;
};

/**
 * Invalid input data
 */
export class FieldDeleteTemplateFieldBadRequestError extends DocumensoError {
  code: string;
  issues?: Array<FieldDeleteTemplateFieldBadRequestIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: FieldDeleteTemplateFieldBadRequestErrorData;

  constructor(
    err: FieldDeleteTemplateFieldBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "FieldDeleteTemplateFieldBadRequestError";
  }
}

/** @internal */
export const FieldDeleteTemplateFieldInternalServerErrorIssue$inboundSchema:
  z.ZodType<
    FieldDeleteTemplateFieldInternalServerErrorIssue,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });
/** @internal */
export type FieldDeleteTemplateFieldInternalServerErrorIssue$Outbound = {
  message: string;
};

/** @internal */
export const FieldDeleteTemplateFieldInternalServerErrorIssue$outboundSchema:
  z.ZodType<
    FieldDeleteTemplateFieldInternalServerErrorIssue$Outbound,
    z.ZodTypeDef,
    FieldDeleteTemplateFieldInternalServerErrorIssue
  > = z.object({
    message: z.string(),
  });

export function fieldDeleteTemplateFieldInternalServerErrorIssueToJSON(
  fieldDeleteTemplateFieldInternalServerErrorIssue:
    FieldDeleteTemplateFieldInternalServerErrorIssue,
): string {
  return JSON.stringify(
    FieldDeleteTemplateFieldInternalServerErrorIssue$outboundSchema.parse(
      fieldDeleteTemplateFieldInternalServerErrorIssue,
    ),
  );
}
export function fieldDeleteTemplateFieldInternalServerErrorIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  FieldDeleteTemplateFieldInternalServerErrorIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FieldDeleteTemplateFieldInternalServerErrorIssue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FieldDeleteTemplateFieldInternalServerErrorIssue' from JSON`,
  );
}

/** @internal */
export const FieldDeleteTemplateFieldInternalServerError$inboundSchema:
  z.ZodType<
    FieldDeleteTemplateFieldInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() =>
        FieldDeleteTemplateFieldInternalServerErrorIssue$inboundSchema
      ),
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new FieldDeleteTemplateFieldInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type FieldDeleteTemplateFieldInternalServerError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<FieldDeleteTemplateFieldInternalServerErrorIssue$Outbound>
    | undefined;
};

/** @internal */
export const FieldDeleteTemplateFieldInternalServerError$outboundSchema:
  z.ZodType<
    FieldDeleteTemplateFieldInternalServerError$Outbound,
    z.ZodTypeDef,
    FieldDeleteTemplateFieldInternalServerError
  > = z.instanceof(FieldDeleteTemplateFieldInternalServerError)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      code: z.string(),
      issues: z.array(
        z.lazy(() =>
          FieldDeleteTemplateFieldInternalServerErrorIssue$outboundSchema
        ),
      ).optional(),
    }));

/** @internal */
export const FieldDeleteTemplateFieldForbiddenIssue$inboundSchema: z.ZodType<
  FieldDeleteTemplateFieldForbiddenIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type FieldDeleteTemplateFieldForbiddenIssue$Outbound = {
  message: string;
};

/** @internal */
export const FieldDeleteTemplateFieldForbiddenIssue$outboundSchema: z.ZodType<
  FieldDeleteTemplateFieldForbiddenIssue$Outbound,
  z.ZodTypeDef,
  FieldDeleteTemplateFieldForbiddenIssue
> = z.object({
  message: z.string(),
});

export function fieldDeleteTemplateFieldForbiddenIssueToJSON(
  fieldDeleteTemplateFieldForbiddenIssue:
    FieldDeleteTemplateFieldForbiddenIssue,
): string {
  return JSON.stringify(
    FieldDeleteTemplateFieldForbiddenIssue$outboundSchema.parse(
      fieldDeleteTemplateFieldForbiddenIssue,
    ),
  );
}
export function fieldDeleteTemplateFieldForbiddenIssueFromJSON(
  jsonString: string,
): SafeParseResult<FieldDeleteTemplateFieldForbiddenIssue, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      FieldDeleteTemplateFieldForbiddenIssue$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FieldDeleteTemplateFieldForbiddenIssue' from JSON`,
  );
}

/** @internal */
export const FieldDeleteTemplateFieldForbiddenError$inboundSchema: z.ZodType<
  FieldDeleteTemplateFieldForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => FieldDeleteTemplateFieldForbiddenIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new FieldDeleteTemplateFieldForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type FieldDeleteTemplateFieldForbiddenError$Outbound = {
  message: string;
  code: string;
  issues?: Array<FieldDeleteTemplateFieldForbiddenIssue$Outbound> | undefined;
};

/** @internal */
export const FieldDeleteTemplateFieldForbiddenError$outboundSchema: z.ZodType<
  FieldDeleteTemplateFieldForbiddenError$Outbound,
  z.ZodTypeDef,
  FieldDeleteTemplateFieldForbiddenError
> = z.instanceof(FieldDeleteTemplateFieldForbiddenError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => FieldDeleteTemplateFieldForbiddenIssue$outboundSchema),
    ).optional(),
  }));

/** @internal */
export const FieldDeleteTemplateFieldUnauthorizedIssue$inboundSchema: z.ZodType<
  FieldDeleteTemplateFieldUnauthorizedIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type FieldDeleteTemplateFieldUnauthorizedIssue$Outbound = {
  message: string;
};

/** @internal */
export const FieldDeleteTemplateFieldUnauthorizedIssue$outboundSchema:
  z.ZodType<
    FieldDeleteTemplateFieldUnauthorizedIssue$Outbound,
    z.ZodTypeDef,
    FieldDeleteTemplateFieldUnauthorizedIssue
  > = z.object({
    message: z.string(),
  });

export function fieldDeleteTemplateFieldUnauthorizedIssueToJSON(
  fieldDeleteTemplateFieldUnauthorizedIssue:
    FieldDeleteTemplateFieldUnauthorizedIssue,
): string {
  return JSON.stringify(
    FieldDeleteTemplateFieldUnauthorizedIssue$outboundSchema.parse(
      fieldDeleteTemplateFieldUnauthorizedIssue,
    ),
  );
}
export function fieldDeleteTemplateFieldUnauthorizedIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  FieldDeleteTemplateFieldUnauthorizedIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FieldDeleteTemplateFieldUnauthorizedIssue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FieldDeleteTemplateFieldUnauthorizedIssue' from JSON`,
  );
}

/** @internal */
export const FieldDeleteTemplateFieldUnauthorizedError$inboundSchema: z.ZodType<
  FieldDeleteTemplateFieldUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => FieldDeleteTemplateFieldUnauthorizedIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new FieldDeleteTemplateFieldUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type FieldDeleteTemplateFieldUnauthorizedError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<FieldDeleteTemplateFieldUnauthorizedIssue$Outbound>
    | undefined;
};

/** @internal */
export const FieldDeleteTemplateFieldUnauthorizedError$outboundSchema:
  z.ZodType<
    FieldDeleteTemplateFieldUnauthorizedError$Outbound,
    z.ZodTypeDef,
    FieldDeleteTemplateFieldUnauthorizedError
  > = z.instanceof(FieldDeleteTemplateFieldUnauthorizedError)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      code: z.string(),
      issues: z.array(
        z.lazy(() => FieldDeleteTemplateFieldUnauthorizedIssue$outboundSchema),
      ).optional(),
    }));

/** @internal */
export const FieldDeleteTemplateFieldBadRequestIssue$inboundSchema: z.ZodType<
  FieldDeleteTemplateFieldBadRequestIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});
/** @internal */
export type FieldDeleteTemplateFieldBadRequestIssue$Outbound = {
  message: string;
};

/** @internal */
export const FieldDeleteTemplateFieldBadRequestIssue$outboundSchema: z.ZodType<
  FieldDeleteTemplateFieldBadRequestIssue$Outbound,
  z.ZodTypeDef,
  FieldDeleteTemplateFieldBadRequestIssue
> = z.object({
  message: z.string(),
});

export function fieldDeleteTemplateFieldBadRequestIssueToJSON(
  fieldDeleteTemplateFieldBadRequestIssue:
    FieldDeleteTemplateFieldBadRequestIssue,
): string {
  return JSON.stringify(
    FieldDeleteTemplateFieldBadRequestIssue$outboundSchema.parse(
      fieldDeleteTemplateFieldBadRequestIssue,
    ),
  );
}
export function fieldDeleteTemplateFieldBadRequestIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  FieldDeleteTemplateFieldBadRequestIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FieldDeleteTemplateFieldBadRequestIssue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FieldDeleteTemplateFieldBadRequestIssue' from JSON`,
  );
}

/** @internal */
export const FieldDeleteTemplateFieldBadRequestError$inboundSchema: z.ZodType<
  FieldDeleteTemplateFieldBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => FieldDeleteTemplateFieldBadRequestIssue$inboundSchema),
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new FieldDeleteTemplateFieldBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type FieldDeleteTemplateFieldBadRequestError$Outbound = {
  message: string;
  code: string;
  issues?: Array<FieldDeleteTemplateFieldBadRequestIssue$Outbound> | undefined;
};

/** @internal */
export const FieldDeleteTemplateFieldBadRequestError$outboundSchema: z.ZodType<
  FieldDeleteTemplateFieldBadRequestError$Outbound,
  z.ZodTypeDef,
  FieldDeleteTemplateFieldBadRequestError
> = z.instanceof(FieldDeleteTemplateFieldBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => FieldDeleteTemplateFieldBadRequestIssue$outboundSchema),
    ).optional(),
  }));
