/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { DocumensoError } from "./documensoerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type RecipientDeleteTemplateRecipientInternalServerErrorIssue = {
  message: string;
};

/**
 * Internal server error
 */
export type RecipientDeleteTemplateRecipientInternalServerErrorData = {
  message: string;
  code: string;
  issues?:
    | Array<RecipientDeleteTemplateRecipientInternalServerErrorIssue>
    | undefined;
};

/**
 * Internal server error
 */
export class RecipientDeleteTemplateRecipientInternalServerError
  extends DocumensoError
{
  code: string;
  issues?:
    | Array<RecipientDeleteTemplateRecipientInternalServerErrorIssue>
    | undefined;

  /** The original data that was passed to this error instance. */
  data$: RecipientDeleteTemplateRecipientInternalServerErrorData;

  constructor(
    err: RecipientDeleteTemplateRecipientInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "RecipientDeleteTemplateRecipientInternalServerError";
  }
}

export type RecipientDeleteTemplateRecipientForbiddenIssue = {
  message: string;
};

/**
 * Insufficient access
 */
export type RecipientDeleteTemplateRecipientForbiddenErrorData = {
  message: string;
  code: string;
  issues?: Array<RecipientDeleteTemplateRecipientForbiddenIssue> | undefined;
};

/**
 * Insufficient access
 */
export class RecipientDeleteTemplateRecipientForbiddenError
  extends DocumensoError
{
  code: string;
  issues?: Array<RecipientDeleteTemplateRecipientForbiddenIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: RecipientDeleteTemplateRecipientForbiddenErrorData;

  constructor(
    err: RecipientDeleteTemplateRecipientForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "RecipientDeleteTemplateRecipientForbiddenError";
  }
}

export type RecipientDeleteTemplateRecipientUnauthorizedIssue = {
  message: string;
};

/**
 * Authorization not provided
 */
export type RecipientDeleteTemplateRecipientUnauthorizedErrorData = {
  message: string;
  code: string;
  issues?: Array<RecipientDeleteTemplateRecipientUnauthorizedIssue> | undefined;
};

/**
 * Authorization not provided
 */
export class RecipientDeleteTemplateRecipientUnauthorizedError
  extends DocumensoError
{
  code: string;
  issues?: Array<RecipientDeleteTemplateRecipientUnauthorizedIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: RecipientDeleteTemplateRecipientUnauthorizedErrorData;

  constructor(
    err: RecipientDeleteTemplateRecipientUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "RecipientDeleteTemplateRecipientUnauthorizedError";
  }
}

export type RecipientDeleteTemplateRecipientBadRequestIssue = {
  message: string;
};

/**
 * Invalid input data
 */
export type RecipientDeleteTemplateRecipientBadRequestErrorData = {
  message: string;
  code: string;
  issues?: Array<RecipientDeleteTemplateRecipientBadRequestIssue> | undefined;
};

/**
 * Invalid input data
 */
export class RecipientDeleteTemplateRecipientBadRequestError
  extends DocumensoError
{
  code: string;
  issues?: Array<RecipientDeleteTemplateRecipientBadRequestIssue> | undefined;

  /** The original data that was passed to this error instance. */
  data$: RecipientDeleteTemplateRecipientBadRequestErrorData;

  constructor(
    err: RecipientDeleteTemplateRecipientBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "RecipientDeleteTemplateRecipientBadRequestError";
  }
}

/** @internal */
export const RecipientDeleteTemplateRecipientInternalServerErrorIssue$inboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientInternalServerErrorIssue,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });
/** @internal */
export type RecipientDeleteTemplateRecipientInternalServerErrorIssue$Outbound =
  {
    message: string;
  };

/** @internal */
export const RecipientDeleteTemplateRecipientInternalServerErrorIssue$outboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientInternalServerErrorIssue$Outbound,
    z.ZodTypeDef,
    RecipientDeleteTemplateRecipientInternalServerErrorIssue
  > = z.object({
    message: z.string(),
  });

export function recipientDeleteTemplateRecipientInternalServerErrorIssueToJSON(
  recipientDeleteTemplateRecipientInternalServerErrorIssue:
    RecipientDeleteTemplateRecipientInternalServerErrorIssue,
): string {
  return JSON.stringify(
    RecipientDeleteTemplateRecipientInternalServerErrorIssue$outboundSchema
      .parse(recipientDeleteTemplateRecipientInternalServerErrorIssue),
  );
}
export function recipientDeleteTemplateRecipientInternalServerErrorIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  RecipientDeleteTemplateRecipientInternalServerErrorIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RecipientDeleteTemplateRecipientInternalServerErrorIssue$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'RecipientDeleteTemplateRecipientInternalServerErrorIssue' from JSON`,
  );
}

/** @internal */
export const RecipientDeleteTemplateRecipientInternalServerError$inboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() =>
        RecipientDeleteTemplateRecipientInternalServerErrorIssue$inboundSchema
      ),
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new RecipientDeleteTemplateRecipientInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type RecipientDeleteTemplateRecipientInternalServerError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<RecipientDeleteTemplateRecipientInternalServerErrorIssue$Outbound>
    | undefined;
};

/** @internal */
export const RecipientDeleteTemplateRecipientInternalServerError$outboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientInternalServerError$Outbound,
    z.ZodTypeDef,
    RecipientDeleteTemplateRecipientInternalServerError
  > = z.instanceof(RecipientDeleteTemplateRecipientInternalServerError)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      code: z.string(),
      issues: z.array(
        z.lazy(() =>
          RecipientDeleteTemplateRecipientInternalServerErrorIssue$outboundSchema
        ),
      ).optional(),
    }));

/** @internal */
export const RecipientDeleteTemplateRecipientForbiddenIssue$inboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientForbiddenIssue,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });
/** @internal */
export type RecipientDeleteTemplateRecipientForbiddenIssue$Outbound = {
  message: string;
};

/** @internal */
export const RecipientDeleteTemplateRecipientForbiddenIssue$outboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientForbiddenIssue$Outbound,
    z.ZodTypeDef,
    RecipientDeleteTemplateRecipientForbiddenIssue
  > = z.object({
    message: z.string(),
  });

export function recipientDeleteTemplateRecipientForbiddenIssueToJSON(
  recipientDeleteTemplateRecipientForbiddenIssue:
    RecipientDeleteTemplateRecipientForbiddenIssue,
): string {
  return JSON.stringify(
    RecipientDeleteTemplateRecipientForbiddenIssue$outboundSchema.parse(
      recipientDeleteTemplateRecipientForbiddenIssue,
    ),
  );
}
export function recipientDeleteTemplateRecipientForbiddenIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  RecipientDeleteTemplateRecipientForbiddenIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RecipientDeleteTemplateRecipientForbiddenIssue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RecipientDeleteTemplateRecipientForbiddenIssue' from JSON`,
  );
}

/** @internal */
export const RecipientDeleteTemplateRecipientForbiddenError$inboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientForbiddenError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() =>
        RecipientDeleteTemplateRecipientForbiddenIssue$inboundSchema
      ),
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new RecipientDeleteTemplateRecipientForbiddenError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type RecipientDeleteTemplateRecipientForbiddenError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<RecipientDeleteTemplateRecipientForbiddenIssue$Outbound>
    | undefined;
};

/** @internal */
export const RecipientDeleteTemplateRecipientForbiddenError$outboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientForbiddenError$Outbound,
    z.ZodTypeDef,
    RecipientDeleteTemplateRecipientForbiddenError
  > = z.instanceof(RecipientDeleteTemplateRecipientForbiddenError)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      code: z.string(),
      issues: z.array(
        z.lazy(() =>
          RecipientDeleteTemplateRecipientForbiddenIssue$outboundSchema
        ),
      ).optional(),
    }));

/** @internal */
export const RecipientDeleteTemplateRecipientUnauthorizedIssue$inboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientUnauthorizedIssue,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });
/** @internal */
export type RecipientDeleteTemplateRecipientUnauthorizedIssue$Outbound = {
  message: string;
};

/** @internal */
export const RecipientDeleteTemplateRecipientUnauthorizedIssue$outboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientUnauthorizedIssue$Outbound,
    z.ZodTypeDef,
    RecipientDeleteTemplateRecipientUnauthorizedIssue
  > = z.object({
    message: z.string(),
  });

export function recipientDeleteTemplateRecipientUnauthorizedIssueToJSON(
  recipientDeleteTemplateRecipientUnauthorizedIssue:
    RecipientDeleteTemplateRecipientUnauthorizedIssue,
): string {
  return JSON.stringify(
    RecipientDeleteTemplateRecipientUnauthorizedIssue$outboundSchema.parse(
      recipientDeleteTemplateRecipientUnauthorizedIssue,
    ),
  );
}
export function recipientDeleteTemplateRecipientUnauthorizedIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  RecipientDeleteTemplateRecipientUnauthorizedIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RecipientDeleteTemplateRecipientUnauthorizedIssue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RecipientDeleteTemplateRecipientUnauthorizedIssue' from JSON`,
  );
}

/** @internal */
export const RecipientDeleteTemplateRecipientUnauthorizedError$inboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() =>
        RecipientDeleteTemplateRecipientUnauthorizedIssue$inboundSchema
      ),
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new RecipientDeleteTemplateRecipientUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type RecipientDeleteTemplateRecipientUnauthorizedError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<RecipientDeleteTemplateRecipientUnauthorizedIssue$Outbound>
    | undefined;
};

/** @internal */
export const RecipientDeleteTemplateRecipientUnauthorizedError$outboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientUnauthorizedError$Outbound,
    z.ZodTypeDef,
    RecipientDeleteTemplateRecipientUnauthorizedError
  > = z.instanceof(RecipientDeleteTemplateRecipientUnauthorizedError)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      code: z.string(),
      issues: z.array(
        z.lazy(() =>
          RecipientDeleteTemplateRecipientUnauthorizedIssue$outboundSchema
        ),
      ).optional(),
    }));

/** @internal */
export const RecipientDeleteTemplateRecipientBadRequestIssue$inboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientBadRequestIssue,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });
/** @internal */
export type RecipientDeleteTemplateRecipientBadRequestIssue$Outbound = {
  message: string;
};

/** @internal */
export const RecipientDeleteTemplateRecipientBadRequestIssue$outboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientBadRequestIssue$Outbound,
    z.ZodTypeDef,
    RecipientDeleteTemplateRecipientBadRequestIssue
  > = z.object({
    message: z.string(),
  });

export function recipientDeleteTemplateRecipientBadRequestIssueToJSON(
  recipientDeleteTemplateRecipientBadRequestIssue:
    RecipientDeleteTemplateRecipientBadRequestIssue,
): string {
  return JSON.stringify(
    RecipientDeleteTemplateRecipientBadRequestIssue$outboundSchema.parse(
      recipientDeleteTemplateRecipientBadRequestIssue,
    ),
  );
}
export function recipientDeleteTemplateRecipientBadRequestIssueFromJSON(
  jsonString: string,
): SafeParseResult<
  RecipientDeleteTemplateRecipientBadRequestIssue,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RecipientDeleteTemplateRecipientBadRequestIssue$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RecipientDeleteTemplateRecipientBadRequestIssue' from JSON`,
  );
}

/** @internal */
export const RecipientDeleteTemplateRecipientBadRequestError$inboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() =>
        RecipientDeleteTemplateRecipientBadRequestIssue$inboundSchema
      ),
    ).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new RecipientDeleteTemplateRecipientBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type RecipientDeleteTemplateRecipientBadRequestError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<RecipientDeleteTemplateRecipientBadRequestIssue$Outbound>
    | undefined;
};

/** @internal */
export const RecipientDeleteTemplateRecipientBadRequestError$outboundSchema:
  z.ZodType<
    RecipientDeleteTemplateRecipientBadRequestError$Outbound,
    z.ZodTypeDef,
    RecipientDeleteTemplateRecipientBadRequestError
  > = z.instanceof(RecipientDeleteTemplateRecipientBadRequestError)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      code: z.string(),
      issues: z.array(
        z.lazy(() =>
          RecipientDeleteTemplateRecipientBadRequestIssue$outboundSchema
        ),
      ).optional(),
    }));
