/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type RecipientUpdateDocumentRecipientsInternalServerErrorIssues = {
  message: string;
};

/**
 * Internal server error
 */
export type RecipientUpdateDocumentRecipientsInternalServerErrorData = {
  message: string;
  code: string;
  issues?:
    | Array<RecipientUpdateDocumentRecipientsInternalServerErrorIssues>
    | undefined;
};

/**
 * Internal server error
 */
export class RecipientUpdateDocumentRecipientsInternalServerError
  extends Error
{
  code: string;
  issues?:
    | Array<RecipientUpdateDocumentRecipientsInternalServerErrorIssues>
    | undefined;

  /** The original data that was passed to this error instance. */
  data$: RecipientUpdateDocumentRecipientsInternalServerErrorData;

  constructor(err: RecipientUpdateDocumentRecipientsInternalServerErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "RecipientUpdateDocumentRecipientsInternalServerError";
  }
}

export type RecipientUpdateDocumentRecipientsBadRequestIssues = {
  message: string;
};

/**
 * Invalid input data
 */
export type RecipientUpdateDocumentRecipientsBadRequestErrorData = {
  message: string;
  code: string;
  issues?: Array<RecipientUpdateDocumentRecipientsBadRequestIssues> | undefined;
};

/**
 * Invalid input data
 */
export class RecipientUpdateDocumentRecipientsBadRequestError extends Error {
  code: string;
  issues?: Array<RecipientUpdateDocumentRecipientsBadRequestIssues> | undefined;

  /** The original data that was passed to this error instance. */
  data$: RecipientUpdateDocumentRecipientsBadRequestErrorData;

  constructor(err: RecipientUpdateDocumentRecipientsBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "RecipientUpdateDocumentRecipientsBadRequestError";
  }
}

/** @internal */
export const RecipientUpdateDocumentRecipientsInternalServerErrorIssues$inboundSchema:
  z.ZodType<
    RecipientUpdateDocumentRecipientsInternalServerErrorIssues,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });

/** @internal */
export type RecipientUpdateDocumentRecipientsInternalServerErrorIssues$Outbound =
  {
    message: string;
  };

/** @internal */
export const RecipientUpdateDocumentRecipientsInternalServerErrorIssues$outboundSchema:
  z.ZodType<
    RecipientUpdateDocumentRecipientsInternalServerErrorIssues$Outbound,
    z.ZodTypeDef,
    RecipientUpdateDocumentRecipientsInternalServerErrorIssues
  > = z.object({
    message: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RecipientUpdateDocumentRecipientsInternalServerErrorIssues$ {
  /** @deprecated use `RecipientUpdateDocumentRecipientsInternalServerErrorIssues$inboundSchema` instead. */
  export const inboundSchema =
    RecipientUpdateDocumentRecipientsInternalServerErrorIssues$inboundSchema;
  /** @deprecated use `RecipientUpdateDocumentRecipientsInternalServerErrorIssues$outboundSchema` instead. */
  export const outboundSchema =
    RecipientUpdateDocumentRecipientsInternalServerErrorIssues$outboundSchema;
  /** @deprecated use `RecipientUpdateDocumentRecipientsInternalServerErrorIssues$Outbound` instead. */
  export type Outbound =
    RecipientUpdateDocumentRecipientsInternalServerErrorIssues$Outbound;
}

export function recipientUpdateDocumentRecipientsInternalServerErrorIssuesToJSON(
  recipientUpdateDocumentRecipientsInternalServerErrorIssues:
    RecipientUpdateDocumentRecipientsInternalServerErrorIssues,
): string {
  return JSON.stringify(
    RecipientUpdateDocumentRecipientsInternalServerErrorIssues$outboundSchema
      .parse(recipientUpdateDocumentRecipientsInternalServerErrorIssues),
  );
}

export function recipientUpdateDocumentRecipientsInternalServerErrorIssuesFromJSON(
  jsonString: string,
): SafeParseResult<
  RecipientUpdateDocumentRecipientsInternalServerErrorIssues,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RecipientUpdateDocumentRecipientsInternalServerErrorIssues$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'RecipientUpdateDocumentRecipientsInternalServerErrorIssues' from JSON`,
  );
}

/** @internal */
export const RecipientUpdateDocumentRecipientsInternalServerError$inboundSchema:
  z.ZodType<
    RecipientUpdateDocumentRecipientsInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() =>
        RecipientUpdateDocumentRecipientsInternalServerErrorIssues$inboundSchema
      ),
    ).optional(),
  })
    .transform((v) => {
      return new RecipientUpdateDocumentRecipientsInternalServerError(v);
    });

/** @internal */
export type RecipientUpdateDocumentRecipientsInternalServerError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<RecipientUpdateDocumentRecipientsInternalServerErrorIssues$Outbound>
    | undefined;
};

/** @internal */
export const RecipientUpdateDocumentRecipientsInternalServerError$outboundSchema:
  z.ZodType<
    RecipientUpdateDocumentRecipientsInternalServerError$Outbound,
    z.ZodTypeDef,
    RecipientUpdateDocumentRecipientsInternalServerError
  > = z.instanceof(RecipientUpdateDocumentRecipientsInternalServerError)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      code: z.string(),
      issues: z.array(
        z.lazy(() =>
          RecipientUpdateDocumentRecipientsInternalServerErrorIssues$outboundSchema
        ),
      ).optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RecipientUpdateDocumentRecipientsInternalServerError$ {
  /** @deprecated use `RecipientUpdateDocumentRecipientsInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    RecipientUpdateDocumentRecipientsInternalServerError$inboundSchema;
  /** @deprecated use `RecipientUpdateDocumentRecipientsInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    RecipientUpdateDocumentRecipientsInternalServerError$outboundSchema;
  /** @deprecated use `RecipientUpdateDocumentRecipientsInternalServerError$Outbound` instead. */
  export type Outbound =
    RecipientUpdateDocumentRecipientsInternalServerError$Outbound;
}

/** @internal */
export const RecipientUpdateDocumentRecipientsBadRequestIssues$inboundSchema:
  z.ZodType<
    RecipientUpdateDocumentRecipientsBadRequestIssues,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });

/** @internal */
export type RecipientUpdateDocumentRecipientsBadRequestIssues$Outbound = {
  message: string;
};

/** @internal */
export const RecipientUpdateDocumentRecipientsBadRequestIssues$outboundSchema:
  z.ZodType<
    RecipientUpdateDocumentRecipientsBadRequestIssues$Outbound,
    z.ZodTypeDef,
    RecipientUpdateDocumentRecipientsBadRequestIssues
  > = z.object({
    message: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RecipientUpdateDocumentRecipientsBadRequestIssues$ {
  /** @deprecated use `RecipientUpdateDocumentRecipientsBadRequestIssues$inboundSchema` instead. */
  export const inboundSchema =
    RecipientUpdateDocumentRecipientsBadRequestIssues$inboundSchema;
  /** @deprecated use `RecipientUpdateDocumentRecipientsBadRequestIssues$outboundSchema` instead. */
  export const outboundSchema =
    RecipientUpdateDocumentRecipientsBadRequestIssues$outboundSchema;
  /** @deprecated use `RecipientUpdateDocumentRecipientsBadRequestIssues$Outbound` instead. */
  export type Outbound =
    RecipientUpdateDocumentRecipientsBadRequestIssues$Outbound;
}

export function recipientUpdateDocumentRecipientsBadRequestIssuesToJSON(
  recipientUpdateDocumentRecipientsBadRequestIssues:
    RecipientUpdateDocumentRecipientsBadRequestIssues,
): string {
  return JSON.stringify(
    RecipientUpdateDocumentRecipientsBadRequestIssues$outboundSchema.parse(
      recipientUpdateDocumentRecipientsBadRequestIssues,
    ),
  );
}

export function recipientUpdateDocumentRecipientsBadRequestIssuesFromJSON(
  jsonString: string,
): SafeParseResult<
  RecipientUpdateDocumentRecipientsBadRequestIssues,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      RecipientUpdateDocumentRecipientsBadRequestIssues$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'RecipientUpdateDocumentRecipientsBadRequestIssues' from JSON`,
  );
}

/** @internal */
export const RecipientUpdateDocumentRecipientsBadRequestError$inboundSchema:
  z.ZodType<
    RecipientUpdateDocumentRecipientsBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() =>
        RecipientUpdateDocumentRecipientsBadRequestIssues$inboundSchema
      ),
    ).optional(),
  })
    .transform((v) => {
      return new RecipientUpdateDocumentRecipientsBadRequestError(v);
    });

/** @internal */
export type RecipientUpdateDocumentRecipientsBadRequestError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<RecipientUpdateDocumentRecipientsBadRequestIssues$Outbound>
    | undefined;
};

/** @internal */
export const RecipientUpdateDocumentRecipientsBadRequestError$outboundSchema:
  z.ZodType<
    RecipientUpdateDocumentRecipientsBadRequestError$Outbound,
    z.ZodTypeDef,
    RecipientUpdateDocumentRecipientsBadRequestError
  > = z.instanceof(RecipientUpdateDocumentRecipientsBadRequestError)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      code: z.string(),
      issues: z.array(
        z.lazy(() =>
          RecipientUpdateDocumentRecipientsBadRequestIssues$outboundSchema
        ),
      ).optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RecipientUpdateDocumentRecipientsBadRequestError$ {
  /** @deprecated use `RecipientUpdateDocumentRecipientsBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    RecipientUpdateDocumentRecipientsBadRequestError$inboundSchema;
  /** @deprecated use `RecipientUpdateDocumentRecipientsBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    RecipientUpdateDocumentRecipientsBadRequestError$outboundSchema;
  /** @deprecated use `RecipientUpdateDocumentRecipientsBadRequestError$Outbound` instead. */
  export type Outbound =
    RecipientUpdateDocumentRecipientsBadRequestError$Outbound;
}
