/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type TemplateDuplicateTemplateInternalServerErrorIssues = {
  message: string;
};

/**
 * Internal server error
 */
export type TemplateDuplicateTemplateInternalServerErrorData = {
  message: string;
  code: string;
  issues?:
    | Array<TemplateDuplicateTemplateInternalServerErrorIssues>
    | undefined;
};

/**
 * Internal server error
 */
export class TemplateDuplicateTemplateInternalServerError extends Error {
  code: string;
  issues?:
    | Array<TemplateDuplicateTemplateInternalServerErrorIssues>
    | undefined;

  /** The original data that was passed to this error instance. */
  data$: TemplateDuplicateTemplateInternalServerErrorData;

  constructor(err: TemplateDuplicateTemplateInternalServerErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "TemplateDuplicateTemplateInternalServerError";
  }
}

export type TemplateDuplicateTemplateBadRequestIssues = {
  message: string;
};

/**
 * Invalid input data
 */
export type TemplateDuplicateTemplateBadRequestErrorData = {
  message: string;
  code: string;
  issues?: Array<TemplateDuplicateTemplateBadRequestIssues> | undefined;
};

/**
 * Invalid input data
 */
export class TemplateDuplicateTemplateBadRequestError extends Error {
  code: string;
  issues?: Array<TemplateDuplicateTemplateBadRequestIssues> | undefined;

  /** The original data that was passed to this error instance. */
  data$: TemplateDuplicateTemplateBadRequestErrorData;

  constructor(err: TemplateDuplicateTemplateBadRequestErrorData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.code = err.code;
    if (err.issues != null) this.issues = err.issues;

    this.name = "TemplateDuplicateTemplateBadRequestError";
  }
}

/** @internal */
export const TemplateDuplicateTemplateInternalServerErrorIssues$inboundSchema:
  z.ZodType<
    TemplateDuplicateTemplateInternalServerErrorIssues,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
  });

/** @internal */
export type TemplateDuplicateTemplateInternalServerErrorIssues$Outbound = {
  message: string;
};

/** @internal */
export const TemplateDuplicateTemplateInternalServerErrorIssues$outboundSchema:
  z.ZodType<
    TemplateDuplicateTemplateInternalServerErrorIssues$Outbound,
    z.ZodTypeDef,
    TemplateDuplicateTemplateInternalServerErrorIssues
  > = z.object({
    message: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TemplateDuplicateTemplateInternalServerErrorIssues$ {
  /** @deprecated use `TemplateDuplicateTemplateInternalServerErrorIssues$inboundSchema` instead. */
  export const inboundSchema =
    TemplateDuplicateTemplateInternalServerErrorIssues$inboundSchema;
  /** @deprecated use `TemplateDuplicateTemplateInternalServerErrorIssues$outboundSchema` instead. */
  export const outboundSchema =
    TemplateDuplicateTemplateInternalServerErrorIssues$outboundSchema;
  /** @deprecated use `TemplateDuplicateTemplateInternalServerErrorIssues$Outbound` instead. */
  export type Outbound =
    TemplateDuplicateTemplateInternalServerErrorIssues$Outbound;
}

export function templateDuplicateTemplateInternalServerErrorIssuesToJSON(
  templateDuplicateTemplateInternalServerErrorIssues:
    TemplateDuplicateTemplateInternalServerErrorIssues,
): string {
  return JSON.stringify(
    TemplateDuplicateTemplateInternalServerErrorIssues$outboundSchema.parse(
      templateDuplicateTemplateInternalServerErrorIssues,
    ),
  );
}

export function templateDuplicateTemplateInternalServerErrorIssuesFromJSON(
  jsonString: string,
): SafeParseResult<
  TemplateDuplicateTemplateInternalServerErrorIssues,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TemplateDuplicateTemplateInternalServerErrorIssues$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TemplateDuplicateTemplateInternalServerErrorIssues' from JSON`,
  );
}

/** @internal */
export const TemplateDuplicateTemplateInternalServerError$inboundSchema:
  z.ZodType<
    TemplateDuplicateTemplateInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() =>
        TemplateDuplicateTemplateInternalServerErrorIssues$inboundSchema
      ),
    ).optional(),
  })
    .transform((v) => {
      return new TemplateDuplicateTemplateInternalServerError(v);
    });

/** @internal */
export type TemplateDuplicateTemplateInternalServerError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<TemplateDuplicateTemplateInternalServerErrorIssues$Outbound>
    | undefined;
};

/** @internal */
export const TemplateDuplicateTemplateInternalServerError$outboundSchema:
  z.ZodType<
    TemplateDuplicateTemplateInternalServerError$Outbound,
    z.ZodTypeDef,
    TemplateDuplicateTemplateInternalServerError
  > = z.instanceof(TemplateDuplicateTemplateInternalServerError)
    .transform(v => v.data$)
    .pipe(z.object({
      message: z.string(),
      code: z.string(),
      issues: z.array(
        z.lazy(() =>
          TemplateDuplicateTemplateInternalServerErrorIssues$outboundSchema
        ),
      ).optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TemplateDuplicateTemplateInternalServerError$ {
  /** @deprecated use `TemplateDuplicateTemplateInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    TemplateDuplicateTemplateInternalServerError$inboundSchema;
  /** @deprecated use `TemplateDuplicateTemplateInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    TemplateDuplicateTemplateInternalServerError$outboundSchema;
  /** @deprecated use `TemplateDuplicateTemplateInternalServerError$Outbound` instead. */
  export type Outbound = TemplateDuplicateTemplateInternalServerError$Outbound;
}

/** @internal */
export const TemplateDuplicateTemplateBadRequestIssues$inboundSchema: z.ZodType<
  TemplateDuplicateTemplateBadRequestIssues,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
});

/** @internal */
export type TemplateDuplicateTemplateBadRequestIssues$Outbound = {
  message: string;
};

/** @internal */
export const TemplateDuplicateTemplateBadRequestIssues$outboundSchema:
  z.ZodType<
    TemplateDuplicateTemplateBadRequestIssues$Outbound,
    z.ZodTypeDef,
    TemplateDuplicateTemplateBadRequestIssues
  > = z.object({
    message: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TemplateDuplicateTemplateBadRequestIssues$ {
  /** @deprecated use `TemplateDuplicateTemplateBadRequestIssues$inboundSchema` instead. */
  export const inboundSchema =
    TemplateDuplicateTemplateBadRequestIssues$inboundSchema;
  /** @deprecated use `TemplateDuplicateTemplateBadRequestIssues$outboundSchema` instead. */
  export const outboundSchema =
    TemplateDuplicateTemplateBadRequestIssues$outboundSchema;
  /** @deprecated use `TemplateDuplicateTemplateBadRequestIssues$Outbound` instead. */
  export type Outbound = TemplateDuplicateTemplateBadRequestIssues$Outbound;
}

export function templateDuplicateTemplateBadRequestIssuesToJSON(
  templateDuplicateTemplateBadRequestIssues:
    TemplateDuplicateTemplateBadRequestIssues,
): string {
  return JSON.stringify(
    TemplateDuplicateTemplateBadRequestIssues$outboundSchema.parse(
      templateDuplicateTemplateBadRequestIssues,
    ),
  );
}

export function templateDuplicateTemplateBadRequestIssuesFromJSON(
  jsonString: string,
): SafeParseResult<
  TemplateDuplicateTemplateBadRequestIssues,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      TemplateDuplicateTemplateBadRequestIssues$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'TemplateDuplicateTemplateBadRequestIssues' from JSON`,
  );
}

/** @internal */
export const TemplateDuplicateTemplateBadRequestError$inboundSchema: z.ZodType<
  TemplateDuplicateTemplateBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: z.string(),
  issues: z.array(
    z.lazy(() => TemplateDuplicateTemplateBadRequestIssues$inboundSchema),
  ).optional(),
})
  .transform((v) => {
    return new TemplateDuplicateTemplateBadRequestError(v);
  });

/** @internal */
export type TemplateDuplicateTemplateBadRequestError$Outbound = {
  message: string;
  code: string;
  issues?:
    | Array<TemplateDuplicateTemplateBadRequestIssues$Outbound>
    | undefined;
};

/** @internal */
export const TemplateDuplicateTemplateBadRequestError$outboundSchema: z.ZodType<
  TemplateDuplicateTemplateBadRequestError$Outbound,
  z.ZodTypeDef,
  TemplateDuplicateTemplateBadRequestError
> = z.instanceof(TemplateDuplicateTemplateBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    message: z.string(),
    code: z.string(),
    issues: z.array(
      z.lazy(() => TemplateDuplicateTemplateBadRequestIssues$outboundSchema),
    ).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TemplateDuplicateTemplateBadRequestError$ {
  /** @deprecated use `TemplateDuplicateTemplateBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    TemplateDuplicateTemplateBadRequestError$inboundSchema;
  /** @deprecated use `TemplateDuplicateTemplateBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    TemplateDuplicateTemplateBadRequestError$outboundSchema;
  /** @deprecated use `TemplateDuplicateTemplateBadRequestError$Outbound` instead. */
  export type Outbound = TemplateDuplicateTemplateBadRequestError$Outbound;
}
