/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { envelopeRecipientsEnvelopeRecipientUpdateMany } from "../../funcs/envelopeRecipientsEnvelopeRecipientUpdateMany.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EnvelopeRecipientUpdateManyRequest$inboundSchema,
};

export const tool$envelopeRecipientsEnvelopeRecipientUpdateMany: ToolDefinition<
  typeof args
> = {
  name: "envelope-recipients-envelope-recipient-update-many",
  description: `Update envelope recipients

Update multiple recipients for an envelope`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await envelopeRecipientsEnvelopeRecipientUpdateMany(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
