/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { envelopesAttachmentsCreate } from "../../funcs/envelopesAttachmentsCreate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EnvelopeAttachmentCreateRequest$inboundSchema,
};

export const tool$envelopesAttachmentsCreate: ToolDefinition<typeof args> = {
  name: "envelopes-attachments-create",
  description: `Create attachment

Create a new attachment for an envelope`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await envelopesAttachmentsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
