/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { envelopeEnvelopeUpdate } from "../../funcs/envelopeEnvelopeUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EnvelopeUpdateRequest$inboundSchema,
};

export const tool$envelopeEnvelopeUpdate: ToolDefinition<typeof args> = {
  name: "envelope-envelope-update",
  description: `Update envelope`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await envelopeEnvelopeUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
