// This file was auto-generated by Fern from our API Definition.

export const EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaDateOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaDateOverflow =
    (typeof EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaDateOverflow)[keyof typeof EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaDateOverflow];
