// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../index.js";

export interface EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItem {
    envelopeId: string;
    envelopeItemId: string;
    type: Documenso.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemType;
    id: number;
    secondaryId: string;
    recipientId: number;
    /** The page number of the field on the document. Starts from 1. */
    page: number;
    positionX?: unknown;
    positionY?: unknown;
    width?: unknown;
    height?: unknown;
    customText: string;
    inserted: boolean;
    fieldMeta: Documenso.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMeta | null;
    documentId?: number | null;
    templateId?: number | null;
}
