// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../index.js";

export interface DocumentGetManyDocumentResponseDataItem {
    visibility: Documenso.DocumentGetManyDocumentResponseDataItemVisibility;
    status: Documenso.DocumentGetManyDocumentResponseDataItemStatus;
    source: Documenso.DocumentGetManyDocumentResponseDataItemSource;
    id: number;
    /** A custom external ID you can use to identify the document. */
    externalId: string | null;
    /** The ID of the user that created this document. */
    userId: number;
    authOptions: Documenso.DocumentGetManyDocumentResponseDataItemAuthOptions | null;
    formValues: Record<string, Documenso.DocumentGetManyDocumentResponseDataItemFormValuesValue | null> | null;
    title: string;
    createdAt: string;
    updatedAt: string;
    completedAt: string | null;
    deletedAt: string | null;
    teamId: number;
    folderId: string | null;
    useLegacyFieldInsertion: boolean;
    envelopeId: string;
    internalVersion: number;
    documentDataId: string;
    /** The ID of the template that the document was created from, if any. */
    templateId?: number | null;
    user: Documenso.DocumentGetManyDocumentResponseDataItemUser;
    recipients: Documenso.DocumentGetManyDocumentResponseDataItemRecipientsItem[];
    team: Documenso.DocumentGetManyDocumentResponseDataItemTeam | null;
}
