// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";
import { UpdateRecipientsResponseFieldsItemFieldMetaSignatureOverflow } from "./UpdateRecipientsResponseFieldsItemFieldMetaSignatureOverflow.js";

export const UpdateRecipientsResponseFieldsItemFieldMetaSignature: core.serialization.ObjectSchema<
    serializers.templates.UpdateRecipientsResponseFieldsItemFieldMetaSignature.Raw,
    Documenso.templates.UpdateRecipientsResponseFieldsItemFieldMetaSignature
> = core.serialization.object({
    label: core.serialization.string().optional(),
    placeholder: core.serialization.string().optional(),
    required: core.serialization.boolean().optional(),
    readOnly: core.serialization.boolean().optional(),
    fontSize: core.serialization.number().optional(),
    overflow: UpdateRecipientsResponseFieldsItemFieldMetaSignatureOverflow,
});

export declare namespace UpdateRecipientsResponseFieldsItemFieldMetaSignature {
    export interface Raw {
        label?: string | null;
        placeholder?: string | null;
        required?: boolean | null;
        readOnly?: boolean | null;
        fontSize?: number | null;
        overflow: UpdateRecipientsResponseFieldsItemFieldMetaSignatureOverflow.Raw;
    }
}
