// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const UpdateRecipientsResponseFieldsItemFieldMetaRadioDirection: core.serialization.Schema<
    serializers.templates.UpdateRecipientsResponseFieldsItemFieldMetaRadioDirection.Raw,
    Documenso.templates.UpdateRecipientsResponseFieldsItemFieldMetaRadioDirection
> = core.serialization.enum_(["vertical", "horizontal"]);

export declare namespace UpdateRecipientsResponseFieldsItemFieldMetaRadioDirection {
    export type Raw = "vertical" | "horizontal";
}
