// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaDateTextAlign: core.serialization.Schema<
    serializers.templates.UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaDateTextAlign.Raw,
    Documenso.templates.UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaDateTextAlign
> = core.serialization.enum_(["left", "center", "right"]);

export declare namespace UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaDateTextAlign {
    export type Raw = "left" | "center" | "right";
}
