// This file was auto-generated by Fern from our API Definition.

export const UpdateManyRecipientsResponseDataItemSendStatus = {
    NotSent: "NOT_SENT",
    Sent: "SENT",
} as const;
export type UpdateManyRecipientsResponseDataItemSendStatus =
    (typeof UpdateManyRecipientsResponseDataItemSendStatus)[keyof typeof UpdateManyRecipientsResponseDataItemSendStatus];
