// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../index.js";

export interface UpdateManyRecipientsResponseDataItem {
    envelopeId: string;
    role: Documenso.envelopes.UpdateManyRecipientsResponseDataItemRole;
    readStatus: Documenso.envelopes.UpdateManyRecipientsResponseDataItemReadStatus;
    signingStatus: Documenso.envelopes.UpdateManyRecipientsResponseDataItemSigningStatus;
    sendStatus: Documenso.envelopes.UpdateManyRecipientsResponseDataItemSendStatus;
    id: number;
    email: string;
    name: string;
    token: string;
    documentDeletedAt: string | null;
    expired: string | null;
    expiresAt: string | null;
    expirationNotifiedAt: string | null;
    signedAt: string | null;
    authOptions: Documenso.envelopes.UpdateManyRecipientsResponseDataItemAuthOptions | null;
    /** The order in which the recipient should sign the document. Only works if the document is set to sequential signing. */
    signingOrder: number | null;
    rejectionReason: string | null;
    documentId?: number | null;
    templateId?: number | null;
}
