// This file was auto-generated by Fern from our API Definition.

export const UpdateManyRecipientsResponseDataItemRole = {
    Cc: "CC",
    Signer: "SIGNER",
    Viewer: "VIEWER",
    Approver: "APPROVER",
    Assistant: "ASSISTANT",
} as const;
export type UpdateManyRecipientsResponseDataItemRole =
    (typeof UpdateManyRecipientsResponseDataItemRole)[keyof typeof UpdateManyRecipientsResponseDataItemRole];
