// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import * as serializers from "../../../../../../index.js";
import { CreateRecipientsRequestRecipient } from "../../types/CreateRecipientsRequestRecipient.js";

export const CreateRecipientsRequest: core.serialization.Schema<
    serializers.templates.CreateRecipientsRequest.Raw,
    Documenso.templates.CreateRecipientsRequest
> = core.serialization.object({
    templateId: core.serialization.number(),
    recipient: CreateRecipientsRequestRecipient,
});

export declare namespace CreateRecipientsRequest {
    export interface Raw {
        templateId: number;
        recipient: CreateRecipientsRequestRecipient.Raw;
    }
}
