// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         recipientId: 1.1,
 *         envelopeId: "envelopeId",
 *         reason: "reason"
 *     }
 */
export interface EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsRequest {
    /** The ID of the recipient to reject the document on behalf of. */
    recipientId: number;
    /** The ID of the envelope the recipient belongs to. */
    envelopeId: string;
    /** The reason the recipient rejected the document. */
    reason: string;
    /** The email of the team member to attribute the rejection to. Defaults to the API user when omitted. */
    actAsEmail?: string;
}
