// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import * as serializers from "../../../../index.js";

export const EmbeddingPresignVerifyEmbeddingPresignTokenEmbeddingRequest: core.serialization.Schema<
    serializers.EmbeddingPresignVerifyEmbeddingPresignTokenEmbeddingRequest.Raw,
    Documenso.EmbeddingPresignVerifyEmbeddingPresignTokenEmbeddingRequest
> = core.serialization.object({
    token: core.serialization.string(),
    scope: core.serialization.string().optional(),
});

export declare namespace EmbeddingPresignVerifyEmbeddingPresignTokenEmbeddingRequest {
    export interface Raw {
        token: string;
        scope?: string | null;
    }
}
