// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const CreateTemplatesRequestPayloadMetaDistributionMethod: core.serialization.Schema<
    serializers.CreateTemplatesRequestPayloadMetaDistributionMethod.Raw,
    Documenso.CreateTemplatesRequestPayloadMetaDistributionMethod
> = core.serialization.enum_(["EMAIL", "NONE"]);

export declare namespace CreateTemplatesRequestPayloadMetaDistributionMethod {
    export type Raw = "EMAIL" | "NONE";
}
