// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const CreateTemplatesRequestPayloadType: core.serialization.Schema<
    serializers.CreateTemplatesRequestPayloadType.Raw,
    Documenso.CreateTemplatesRequestPayloadType
> = core.serialization.enum_(["PUBLIC", "PRIVATE", "ORGANISATION"]);

export declare namespace CreateTemplatesRequestPayloadType {
    export type Raw = "PUBLIC" | "PRIVATE" | "ORGANISATION";
}
