// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const DeleteTemplatesResponse: core.serialization.ObjectSchema<
    serializers.DeleteTemplatesResponse.Raw,
    Documenso.DeleteTemplatesResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
});

export declare namespace DeleteTemplatesResponse {
    export interface Raw {
        success: boolean;
    }
}
