// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const UpdateTemplatesRequestMetaSigningOrder: core.serialization.Schema<
    serializers.UpdateTemplatesRequestMetaSigningOrder.Raw,
    Documenso.UpdateTemplatesRequestMetaSigningOrder
> = core.serialization.enum_(["PARALLEL", "SEQUENTIAL"]);

export declare namespace UpdateTemplatesRequestMetaSigningOrder {
    export type Raw = "PARALLEL" | "SEQUENTIAL";
}
