// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const UseTemplatesResponseDocumentMetaDistributionMethod: core.serialization.Schema<
    serializers.UseTemplatesResponseDocumentMetaDistributionMethod.Raw,
    Documenso.UseTemplatesResponseDocumentMetaDistributionMethod
> = core.serialization.enum_(["EMAIL", "NONE"]);

export declare namespace UseTemplatesResponseDocumentMetaDistributionMethod {
    export type Raw = "EMAIL" | "NONE";
}
