// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const UseTemplatesResponseFieldsItemFieldMetaNumberTextAlign: core.serialization.Schema<
    serializers.UseTemplatesResponseFieldsItemFieldMetaNumberTextAlign.Raw,
    Documenso.UseTemplatesResponseFieldsItemFieldMetaNumberTextAlign
> = core.serialization.enum_(["left", "center", "right"]);

export declare namespace UseTemplatesResponseFieldsItemFieldMetaNumberTextAlign {
    export type Raw = "left" | "center" | "right";
}
