// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const UseTemplatesResponseDocumentMetaReminderSettingsRepeatEveryDisabled: core.serialization.ObjectSchema<
    serializers.UseTemplatesResponseDocumentMetaReminderSettingsRepeatEveryDisabled.Raw,
    Documenso.UseTemplatesResponseDocumentMetaReminderSettingsRepeatEveryDisabled
> = core.serialization.object({
    disabled: core.serialization.booleanLiteral(true),
});

export declare namespace UseTemplatesResponseDocumentMetaReminderSettingsRepeatEveryDisabled {
    export interface Raw {
        disabled: true;
    }
}
