// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const UseTemplatesRequestPrefillFieldsItem: core.serialization.ObjectSchema<
    serializers.UseTemplatesRequestPrefillFieldsItem.Raw,
    Documenso.UseTemplatesRequestPrefillFieldsItem
> = core.serialization.object({
    id: core.serialization.number(),
    type: core.serialization.stringLiteral("text").optional(),
    label: core.serialization.string().optional(),
    placeholder: core.serialization.string().optional(),
    value: core.serialization.string().optional(),
});

export declare namespace UseTemplatesRequestPrefillFieldsItem {
    export interface Raw {
        id: number;
        type?: "text" | null;
        label?: string | null;
        placeholder?: string | null;
        value?: string | null;
    }
}
