// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const UseTemplatesRequestOverrideEnvelopeExpirationPeriodDisabled: core.serialization.ObjectSchema<
    serializers.UseTemplatesRequestOverrideEnvelopeExpirationPeriodDisabled.Raw,
    Documenso.UseTemplatesRequestOverrideEnvelopeExpirationPeriodDisabled
> = core.serialization.object({
    disabled: core.serialization.booleanLiteral(true),
});

export declare namespace UseTemplatesRequestOverrideEnvelopeExpirationPeriodDisabled {
    export interface Raw {
        disabled: true;
    }
}
