/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { DocumensoCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$documentDocumentDownload } from "./tools/documentDocumentDownload.js";
import { tool$documentDocumentGetMany } from "./tools/documentDocumentGetMany.js";
import { tool$documentsAttachmentsCreate } from "./tools/documentsAttachmentsCreate.js";
import { tool$documentsAttachmentsDelete } from "./tools/documentsAttachmentsDelete.js";
import { tool$documentsAttachmentsFind } from "./tools/documentsAttachmentsFind.js";
import { tool$documentsAttachmentsUpdate } from "./tools/documentsAttachmentsUpdate.js";
import { tool$documentsCreate } from "./tools/documentsCreate.js";
import { tool$documentsCreateV0 } from "./tools/documentsCreateV0.js";
import { tool$documentsDelete } from "./tools/documentsDelete.js";
import { tool$documentsDistribute } from "./tools/documentsDistribute.js";
import { tool$documentsDownload } from "./tools/documentsDownload.js";
import { tool$documentsDuplicate } from "./tools/documentsDuplicate.js";
import { tool$documentsFieldsCreate } from "./tools/documentsFieldsCreate.js";
import { tool$documentsFieldsCreateMany } from "./tools/documentsFieldsCreateMany.js";
import { tool$documentsFieldsDelete } from "./tools/documentsFieldsDelete.js";
import { tool$documentsFieldsGet } from "./tools/documentsFieldsGet.js";
import { tool$documentsFieldsUpdate } from "./tools/documentsFieldsUpdate.js";
import { tool$documentsFieldsUpdateMany } from "./tools/documentsFieldsUpdateMany.js";
import { tool$documentsFind } from "./tools/documentsFind.js";
import { tool$documentsGet } from "./tools/documentsGet.js";
import { tool$documentsRecipientsCreate } from "./tools/documentsRecipientsCreate.js";
import { tool$documentsRecipientsCreateMany } from "./tools/documentsRecipientsCreateMany.js";
import { tool$documentsRecipientsDelete } from "./tools/documentsRecipientsDelete.js";
import { tool$documentsRecipientsGet } from "./tools/documentsRecipientsGet.js";
import { tool$documentsRecipientsUpdate } from "./tools/documentsRecipientsUpdate.js";
import { tool$documentsRecipientsUpdateMany } from "./tools/documentsRecipientsUpdateMany.js";
import { tool$documentsRedistribute } from "./tools/documentsRedistribute.js";
import { tool$documentsUpdate } from "./tools/documentsUpdate.js";
import { tool$embeddingEmbeddingPresignCreateEmbeddingPresignToken } from "./tools/embeddingEmbeddingPresignCreateEmbeddingPresignToken.js";
import { tool$embeddingEmbeddingPresignVerifyEmbeddingPresignToken } from "./tools/embeddingEmbeddingPresignVerifyEmbeddingPresignToken.js";
import { tool$envelopeEnvelopeAuditLogFind } from "./tools/envelopeEnvelopeAuditLogFind.js";
import { tool$envelopeEnvelopeFind } from "./tools/envelopeEnvelopeFind.js";
import { tool$envelopeEnvelopeGetMany } from "./tools/envelopeEnvelopeGetMany.js";
import { tool$envelopesAttachmentsCreate } from "./tools/envelopesAttachmentsCreate.js";
import { tool$envelopesAttachmentsDelete } from "./tools/envelopesAttachmentsDelete.js";
import { tool$envelopesAttachmentsFind } from "./tools/envelopesAttachmentsFind.js";
import { tool$envelopesAttachmentsUpdate } from "./tools/envelopesAttachmentsUpdate.js";
import { tool$envelopesCreate } from "./tools/envelopesCreate.js";
import { tool$envelopesDelete } from "./tools/envelopesDelete.js";
import { tool$envelopesDistribute } from "./tools/envelopesDistribute.js";
import { tool$envelopesDuplicate } from "./tools/envelopesDuplicate.js";
import { tool$envelopesFieldsCreateMany } from "./tools/envelopesFieldsCreateMany.js";
import { tool$envelopesFieldsDelete } from "./tools/envelopesFieldsDelete.js";
import { tool$envelopesFieldsGet } from "./tools/envelopesFieldsGet.js";
import { tool$envelopesFieldsUpdateMany } from "./tools/envelopesFieldsUpdateMany.js";
import { tool$envelopesGet } from "./tools/envelopesGet.js";
import { tool$envelopesItemsCreateMany } from "./tools/envelopesItemsCreateMany.js";
import { tool$envelopesItemsDelete } from "./tools/envelopesItemsDelete.js";
import { tool$envelopesItemsDownload } from "./tools/envelopesItemsDownload.js";
import { tool$envelopesItemsUpdateMany } from "./tools/envelopesItemsUpdateMany.js";
import { tool$envelopesRecipientsCreateMany } from "./tools/envelopesRecipientsCreateMany.js";
import { tool$envelopesRecipientsDelete } from "./tools/envelopesRecipientsDelete.js";
import { tool$envelopesRecipientsGet } from "./tools/envelopesRecipientsGet.js";
import { tool$envelopesRecipientsUpdateMany } from "./tools/envelopesRecipientsUpdateMany.js";
import { tool$envelopesRedistribute } from "./tools/envelopesRedistribute.js";
import { tool$envelopesUpdate } from "./tools/envelopesUpdate.js";
import { tool$envelopesUse } from "./tools/envelopesUse.js";
import { tool$foldersCreate } from "./tools/foldersCreate.js";
import { tool$foldersDelete } from "./tools/foldersDelete.js";
import { tool$foldersFind } from "./tools/foldersFind.js";
import { tool$foldersUpdate } from "./tools/foldersUpdate.js";
import { tool$templatesCreate } from "./tools/templatesCreate.js";
import { tool$templatesDelete } from "./tools/templatesDelete.js";
import { tool$templatesDirectLinkCreate } from "./tools/templatesDirectLinkCreate.js";
import { tool$templatesDirectLinkDelete } from "./tools/templatesDirectLinkDelete.js";
import { tool$templatesDirectLinkToggle } from "./tools/templatesDirectLinkToggle.js";
import { tool$templatesDuplicate } from "./tools/templatesDuplicate.js";
import { tool$templatesFieldsCreate } from "./tools/templatesFieldsCreate.js";
import { tool$templatesFieldsCreateMany } from "./tools/templatesFieldsCreateMany.js";
import { tool$templatesFieldsDelete } from "./tools/templatesFieldsDelete.js";
import { tool$templatesFieldsGet } from "./tools/templatesFieldsGet.js";
import { tool$templatesFieldsUpdate } from "./tools/templatesFieldsUpdate.js";
import { tool$templatesFieldsUpdateMany } from "./tools/templatesFieldsUpdateMany.js";
import { tool$templatesFind } from "./tools/templatesFind.js";
import { tool$templatesGet } from "./tools/templatesGet.js";
import { tool$templatesRecipientsCreate } from "./tools/templatesRecipientsCreate.js";
import { tool$templatesRecipientsCreateMany } from "./tools/templatesRecipientsCreateMany.js";
import { tool$templatesRecipientsDelete } from "./tools/templatesRecipientsDelete.js";
import { tool$templatesRecipientsGet } from "./tools/templatesRecipientsGet.js";
import { tool$templatesRecipientsUpdate } from "./tools/templatesRecipientsUpdate.js";
import { tool$templatesRecipientsUpdateMany } from "./tools/templatesRecipientsUpdateMany.js";
import { tool$templatesUpdate } from "./tools/templatesUpdate.js";
import { tool$templatesUse } from "./tools/templatesUse.js";
import { tool$templateTemplateCreateTemplateTemporary } from "./tools/templateTemplateCreateTemplateTemporary.js";
import { tool$templateTemplateGetMany } from "./tools/templateTemplateGetMany.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  apiKey?: SDKOptions["apiKey"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Documenso",
    version: "0.7.0",
  });

  const client = new DocumensoCore({
    apiKey: deps.apiKey,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$envelopesGet);
  tool(tool$envelopesCreate);
  tool(tool$envelopesUse);
  tool(tool$envelopesUpdate);
  tool(tool$envelopesDelete);
  tool(tool$envelopesDuplicate);
  tool(tool$envelopesDistribute);
  tool(tool$envelopesRedistribute);
  tool(tool$envelopeEnvelopeFind);
  tool(tool$envelopeEnvelopeAuditLogFind);
  tool(tool$envelopeEnvelopeGetMany);
  tool(tool$documentsGet);
  tool(tool$documentsFind);
  tool(tool$documentsCreate);
  tool(tool$documentsUpdate);
  tool(tool$documentsDelete);
  tool(tool$documentsDuplicate);
  tool(tool$documentsDistribute);
  tool(tool$documentsRedistribute);
  tool(tool$documentsDownload);
  tool(tool$documentsCreateV0);
  tool(tool$documentDocumentGetMany);
  tool(tool$documentDocumentDownload);
  tool(tool$templatesFind);
  tool(tool$templatesGet);
  tool(tool$templatesCreate);
  tool(tool$templatesUpdate);
  tool(tool$templatesDuplicate);
  tool(tool$templatesDelete);
  tool(tool$templatesUse);
  tool(tool$foldersFind);
  tool(tool$foldersCreate);
  tool(tool$foldersUpdate);
  tool(tool$foldersDelete);
  tool(tool$templateTemplateGetMany);
  tool(tool$templateTemplateCreateTemplateTemporary);
  tool(tool$embeddingEmbeddingPresignCreateEmbeddingPresignToken);
  tool(tool$embeddingEmbeddingPresignVerifyEmbeddingPresignToken);
  tool(tool$envelopesAttachmentsFind);
  tool(tool$envelopesAttachmentsCreate);
  tool(tool$envelopesAttachmentsUpdate);
  tool(tool$envelopesAttachmentsDelete);
  tool(tool$envelopesItemsCreateMany);
  tool(tool$envelopesItemsUpdateMany);
  tool(tool$envelopesItemsDelete);
  tool(tool$envelopesItemsDownload);
  tool(tool$envelopesRecipientsGet);
  tool(tool$envelopesRecipientsCreateMany);
  tool(tool$envelopesRecipientsUpdateMany);
  tool(tool$envelopesRecipientsDelete);
  tool(tool$envelopesFieldsGet);
  tool(tool$envelopesFieldsCreateMany);
  tool(tool$envelopesFieldsUpdateMany);
  tool(tool$envelopesFieldsDelete);
  tool(tool$documentsAttachmentsCreate);
  tool(tool$documentsAttachmentsUpdate);
  tool(tool$documentsAttachmentsDelete);
  tool(tool$documentsAttachmentsFind);
  tool(tool$documentsFieldsGet);
  tool(tool$documentsFieldsCreate);
  tool(tool$documentsFieldsCreateMany);
  tool(tool$documentsFieldsUpdate);
  tool(tool$documentsFieldsUpdateMany);
  tool(tool$documentsFieldsDelete);
  tool(tool$documentsRecipientsGet);
  tool(tool$documentsRecipientsCreate);
  tool(tool$documentsRecipientsCreateMany);
  tool(tool$documentsRecipientsUpdate);
  tool(tool$documentsRecipientsUpdateMany);
  tool(tool$documentsRecipientsDelete);
  tool(tool$templatesFieldsCreate);
  tool(tool$templatesFieldsGet);
  tool(tool$templatesFieldsCreateMany);
  tool(tool$templatesFieldsUpdate);
  tool(tool$templatesFieldsUpdateMany);
  tool(tool$templatesFieldsDelete);
  tool(tool$templatesRecipientsGet);
  tool(tool$templatesRecipientsCreate);
  tool(tool$templatesRecipientsCreateMany);
  tool(tool$templatesRecipientsUpdate);
  tool(tool$templatesRecipientsUpdateMany);
  tool(tool$templatesRecipientsDelete);
  tool(tool$templatesDirectLinkCreate);
  tool(tool$templatesDirectLinkDelete);
  tool(tool$templatesDirectLinkToggle);

  return server;
}
