// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import * as serializers from "../../../../index.js";

export const EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsRequest: core.serialization.Schema<
    serializers.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsRequest.Raw,
    Omit<Documenso.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsRequest, "recipientId">
> = core.serialization.object({
    envelopeId: core.serialization.string(),
    reason: core.serialization.string(),
    actAsEmail: core.serialization.string().optional(),
});

export declare namespace EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsRequest {
    export interface Raw {
        envelopeId: string;
        reason: string;
        actAsEmail?: string | null;
    }
}
