// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../index.js";

export interface CreateRecipientsResponseAuthOptions {
    accessAuth: Documenso.templates.CreateRecipientsResponseAuthOptionsAccessAuthItem[];
    actionAuth: Documenso.templates.CreateRecipientsResponseAuthOptionsActionAuthItem[];
}
