// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../index.js";

export interface GetRecipientsResponseFieldsItemFieldMetaDropdown {
    label?: string;
    placeholder?: string;
    required?: boolean;
    readOnly?: boolean;
    fontSize?: number;
    overflow?: Documenso.templates.GetRecipientsResponseFieldsItemFieldMetaDropdownOverflow;
    values?: Documenso.templates.GetRecipientsResponseFieldsItemFieldMetaDropdownValuesItem[];
    defaultValue?: string;
}
