// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";
import { CreateFieldsRequestFieldFieldMetaOverflow } from "./CreateFieldsRequestFieldFieldMetaOverflow.js";

export const CreateFieldsRequestFieldFieldMeta: core.serialization.ObjectSchema<
    serializers.templates.CreateFieldsRequestFieldFieldMeta.Raw,
    Documenso.templates.CreateFieldsRequestFieldFieldMeta
> = core.serialization.object({
    label: core.serialization.string().optional(),
    placeholder: core.serialization.string().optional(),
    required: core.serialization.boolean().optional(),
    readOnly: core.serialization.boolean().optional(),
    fontSize: core.serialization.number().optional(),
    overflow: CreateFieldsRequestFieldFieldMetaOverflow.optional(),
    type: core.serialization.stringLiteral("signature"),
});

export declare namespace CreateFieldsRequestFieldFieldMeta {
    export interface Raw {
        label?: string | null;
        placeholder?: string | null;
        required?: boolean | null;
        readOnly?: boolean | null;
        fontSize?: number | null;
        overflow?: CreateFieldsRequestFieldFieldMetaOverflow.Raw | null;
        type: "signature";
    }
}
