// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const CreateManyFieldsResponseFieldsItemFieldMetaCheckboxDirection: core.serialization.Schema<
    serializers.templates.CreateManyFieldsResponseFieldsItemFieldMetaCheckboxDirection.Raw,
    Documenso.templates.CreateManyFieldsResponseFieldsItemFieldMetaCheckboxDirection
> = core.serialization.enum_(["vertical", "horizontal"]);

export declare namespace CreateManyFieldsResponseFieldsItemFieldMetaCheckboxDirection {
    export type Raw = "vertical" | "horizontal";
}
