// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const UpdateFieldsResponseFieldMetaTextOverflow: core.serialization.Schema<
    serializers.templates.UpdateFieldsResponseFieldMetaTextOverflow.Raw,
    Documenso.templates.UpdateFieldsResponseFieldMetaTextOverflow
> = core.serialization.enum_(["auto", "horizontal", "vertical", "crop"]);

export declare namespace UpdateFieldsResponseFieldMetaTextOverflow {
    export type Raw = "auto" | "horizontal" | "vertical" | "crop";
}
