// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";
import { UpdateManyFieldsResponseFieldsItemFieldMetaDateOverflow } from "./UpdateManyFieldsResponseFieldsItemFieldMetaDateOverflow.js";
import { UpdateManyFieldsResponseFieldsItemFieldMetaDateTextAlign } from "./UpdateManyFieldsResponseFieldsItemFieldMetaDateTextAlign.js";

export const UpdateManyFieldsResponseFieldsItemFieldMetaDate: core.serialization.ObjectSchema<
    serializers.templates.UpdateManyFieldsResponseFieldsItemFieldMetaDate.Raw,
    Documenso.templates.UpdateManyFieldsResponseFieldsItemFieldMetaDate
> = core.serialization.object({
    label: core.serialization.string().optional(),
    placeholder: core.serialization.string().optional(),
    required: core.serialization.boolean().optional(),
    readOnly: core.serialization.boolean().optional(),
    fontSize: core.serialization.number().optional(),
    overflow: UpdateManyFieldsResponseFieldsItemFieldMetaDateOverflow,
    textAlign: UpdateManyFieldsResponseFieldsItemFieldMetaDateTextAlign.optional(),
});

export declare namespace UpdateManyFieldsResponseFieldsItemFieldMetaDate {
    export interface Raw {
        label?: string | null;
        placeholder?: string | null;
        required?: boolean | null;
        readOnly?: boolean | null;
        fontSize?: number | null;
        overflow: UpdateManyFieldsResponseFieldsItemFieldMetaDateOverflow.Raw;
        textAlign?: UpdateManyFieldsResponseFieldsItemFieldMetaDateTextAlign.Raw | null;
    }
}
