// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const CreateV0DocumentsResponseDocumentRecipientsItemSigningStatus: core.serialization.Schema<
    serializers.CreateV0DocumentsResponseDocumentRecipientsItemSigningStatus.Raw,
    Documenso.CreateV0DocumentsResponseDocumentRecipientsItemSigningStatus
> = core.serialization.enum_(["NOT_SIGNED", "SIGNED", "REJECTED"]);

export declare namespace CreateV0DocumentsResponseDocumentRecipientsItemSigningStatus {
    export type Raw = "NOT_SIGNED" | "SIGNED" | "REJECTED";
}
