// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const CreateDocumentsResponse: core.serialization.ObjectSchema<
    serializers.CreateDocumentsResponse.Raw,
    Documenso.CreateDocumentsResponse
> = core.serialization.object({
    envelopeId: core.serialization.string(),
    id: core.serialization.number(),
});

export declare namespace CreateDocumentsResponse {
    export interface Raw {
        envelopeId: string;
        id: number;
    }
}
