// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEveryAmount } from "./CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEveryAmount.js";
import { CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEveryDisabled } from "./CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEveryDisabled.js";

export const CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEvery: core.serialization.Schema<
    serializers.CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEvery.Raw,
    Documenso.CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEvery
> = core.serialization.undiscriminatedUnion([
    CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEveryAmount,
    CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEveryDisabled,
]);

export declare namespace CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEvery {
    export type Raw =
        | CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEveryAmount.Raw
        | CreateDocumentsRequestPayloadMetaReminderSettingsRepeatEveryDisabled.Raw;
}
