// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const DeleteDocumentsResponse: core.serialization.ObjectSchema<
    serializers.DeleteDocumentsResponse.Raw,
    Documenso.DeleteDocumentsResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
});

export declare namespace DeleteDocumentsResponse {
    export interface Raw {
        success: boolean;
    }
}
