// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const DistributeDocumentsResponseFormValuesValue: core.serialization.Schema<
    serializers.DistributeDocumentsResponseFormValuesValue.Raw,
    Documenso.DistributeDocumentsResponseFormValuesValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.boolean(),
    core.serialization.number(),
]);

export declare namespace DistributeDocumentsResponseFormValuesValue {
    export type Raw = string | boolean | number;
}
