// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { GetDocumentsResponseFieldsItemFieldMetaCheckbox } from "./GetDocumentsResponseFieldsItemFieldMetaCheckbox.js";
import { GetDocumentsResponseFieldsItemFieldMetaDate } from "./GetDocumentsResponseFieldsItemFieldMetaDate.js";
import { GetDocumentsResponseFieldsItemFieldMetaDropdown } from "./GetDocumentsResponseFieldsItemFieldMetaDropdown.js";
import { GetDocumentsResponseFieldsItemFieldMetaEmail } from "./GetDocumentsResponseFieldsItemFieldMetaEmail.js";
import { GetDocumentsResponseFieldsItemFieldMetaInitials } from "./GetDocumentsResponseFieldsItemFieldMetaInitials.js";
import { GetDocumentsResponseFieldsItemFieldMetaName } from "./GetDocumentsResponseFieldsItemFieldMetaName.js";
import { GetDocumentsResponseFieldsItemFieldMetaNumber } from "./GetDocumentsResponseFieldsItemFieldMetaNumber.js";
import { GetDocumentsResponseFieldsItemFieldMetaRadio } from "./GetDocumentsResponseFieldsItemFieldMetaRadio.js";
import { GetDocumentsResponseFieldsItemFieldMetaSignature } from "./GetDocumentsResponseFieldsItemFieldMetaSignature.js";
import { GetDocumentsResponseFieldsItemFieldMetaText } from "./GetDocumentsResponseFieldsItemFieldMetaText.js";

export const GetDocumentsResponseFieldsItemFieldMeta: core.serialization.Schema<
    serializers.GetDocumentsResponseFieldsItemFieldMeta.Raw,
    Documenso.GetDocumentsResponseFieldsItemFieldMeta
> = core.serialization
    .union("type", {
        signature: GetDocumentsResponseFieldsItemFieldMetaSignature,
        initials: GetDocumentsResponseFieldsItemFieldMetaInitials,
        name: GetDocumentsResponseFieldsItemFieldMetaName,
        email: GetDocumentsResponseFieldsItemFieldMetaEmail,
        date: GetDocumentsResponseFieldsItemFieldMetaDate,
        text: GetDocumentsResponseFieldsItemFieldMetaText,
        number: GetDocumentsResponseFieldsItemFieldMetaNumber,
        radio: GetDocumentsResponseFieldsItemFieldMetaRadio,
        checkbox: GetDocumentsResponseFieldsItemFieldMetaCheckbox,
        dropdown: GetDocumentsResponseFieldsItemFieldMetaDropdown,
    })
    .transform<Documenso.GetDocumentsResponseFieldsItemFieldMeta>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace GetDocumentsResponseFieldsItemFieldMeta {
    export type Raw =
        | GetDocumentsResponseFieldsItemFieldMeta.Signature
        | GetDocumentsResponseFieldsItemFieldMeta.Initials
        | GetDocumentsResponseFieldsItemFieldMeta.Name
        | GetDocumentsResponseFieldsItemFieldMeta.Email
        | GetDocumentsResponseFieldsItemFieldMeta.Date
        | GetDocumentsResponseFieldsItemFieldMeta.Text
        | GetDocumentsResponseFieldsItemFieldMeta.Number
        | GetDocumentsResponseFieldsItemFieldMeta.Radio
        | GetDocumentsResponseFieldsItemFieldMeta.Checkbox
        | GetDocumentsResponseFieldsItemFieldMeta.Dropdown;

    export interface Signature extends GetDocumentsResponseFieldsItemFieldMetaSignature.Raw {
        type: "signature";
    }

    export interface Initials extends GetDocumentsResponseFieldsItemFieldMetaInitials.Raw {
        type: "initials";
    }

    export interface Name extends GetDocumentsResponseFieldsItemFieldMetaName.Raw {
        type: "name";
    }

    export interface Email extends GetDocumentsResponseFieldsItemFieldMetaEmail.Raw {
        type: "email";
    }

    export interface Date extends GetDocumentsResponseFieldsItemFieldMetaDate.Raw {
        type: "date";
    }

    export interface Text extends GetDocumentsResponseFieldsItemFieldMetaText.Raw {
        type: "text";
    }

    export interface Number extends GetDocumentsResponseFieldsItemFieldMetaNumber.Raw {
        type: "number";
    }

    export interface Radio extends GetDocumentsResponseFieldsItemFieldMetaRadio.Raw {
        type: "radio";
    }

    export interface Checkbox extends GetDocumentsResponseFieldsItemFieldMetaCheckbox.Raw {
        type: "checkbox";
    }

    export interface Dropdown extends GetDocumentsResponseFieldsItemFieldMetaDropdown.Raw {
        type: "dropdown";
    }
}
