// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { UpdateDocumentsResponseAuthOptions } from "./UpdateDocumentsResponseAuthOptions.js";
import { UpdateDocumentsResponseFormValuesValue } from "./UpdateDocumentsResponseFormValuesValue.js";
import { UpdateDocumentsResponseSource } from "./UpdateDocumentsResponseSource.js";
import { UpdateDocumentsResponseStatus } from "./UpdateDocumentsResponseStatus.js";
import { UpdateDocumentsResponseVisibility } from "./UpdateDocumentsResponseVisibility.js";

export const UpdateDocumentsResponse: core.serialization.ObjectSchema<
    serializers.UpdateDocumentsResponse.Raw,
    Documenso.UpdateDocumentsResponse
> = core.serialization.object({
    visibility: UpdateDocumentsResponseVisibility,
    status: UpdateDocumentsResponseStatus,
    source: UpdateDocumentsResponseSource,
    id: core.serialization.number(),
    externalId: core.serialization.string().nullable(),
    userId: core.serialization.number(),
    authOptions: UpdateDocumentsResponseAuthOptions.nullable(),
    formValues: core.serialization
        .record(core.serialization.string(), UpdateDocumentsResponseFormValuesValue.nullable())
        .nullable(),
    title: core.serialization.string(),
    createdAt: core.serialization.string(),
    updatedAt: core.serialization.string(),
    completedAt: core.serialization.string().nullable(),
    deletedAt: core.serialization.string().nullable(),
    teamId: core.serialization.number(),
    folderId: core.serialization.string().nullable(),
    useLegacyFieldInsertion: core.serialization.boolean(),
    envelopeId: core.serialization.string(),
    internalVersion: core.serialization.number(),
    documentDataId: core.serialization.string(),
    templateId: core.serialization.number().optionalNullable(),
});

export declare namespace UpdateDocumentsResponse {
    export interface Raw {
        visibility: UpdateDocumentsResponseVisibility.Raw;
        status: UpdateDocumentsResponseStatus.Raw;
        source: UpdateDocumentsResponseSource.Raw;
        id: number;
        externalId?: string | null;
        userId: number;
        authOptions?: UpdateDocumentsResponseAuthOptions.Raw | null;
        formValues?: Record<string, UpdateDocumentsResponseFormValuesValue.Raw | null | undefined> | null;
        title: string;
        createdAt: string;
        updatedAt: string;
        completedAt?: string | null;
        deletedAt?: string | null;
        teamId: number;
        folderId?: string | null;
        useLegacyFieldInsertion: boolean;
        envelopeId: string;
        internalVersion: number;
        documentDataId: string;
        templateId?: (number | null | undefined) | null;
    }
}
