"use strict";
/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.createMCPServer = createMCPServer;
const mcp_js_1 = require("@modelcontextprotocol/sdk/server/mcp.js");
const core_js_1 = require("../core.js");
const scopes_js_1 = require("./scopes.js");
const tools_js_1 = require("./tools.js");
const documentsCreateV0_js_1 = require("./tools/documentsCreateV0.js");
const documentsDelete_js_1 = require("./tools/documentsDelete.js");
const documentsDistribute_js_1 = require("./tools/documentsDistribute.js");
const documentsDuplicate_js_1 = require("./tools/documentsDuplicate.js");
const documentsFieldsCreate_js_1 = require("./tools/documentsFieldsCreate.js");
const documentsFieldsCreateMany_js_1 = require("./tools/documentsFieldsCreateMany.js");
const documentsFieldsDelete_js_1 = require("./tools/documentsFieldsDelete.js");
const documentsFieldsGet_js_1 = require("./tools/documentsFieldsGet.js");
const documentsFieldsUpdate_js_1 = require("./tools/documentsFieldsUpdate.js");
const documentsFieldsUpdateMany_js_1 = require("./tools/documentsFieldsUpdateMany.js");
const documentsFind_js_1 = require("./tools/documentsFind.js");
const documentsGet_js_1 = require("./tools/documentsGet.js");
const documentsMoveToTeam_js_1 = require("./tools/documentsMoveToTeam.js");
const documentsRecipientsCreate_js_1 = require("./tools/documentsRecipientsCreate.js");
const documentsRecipientsCreateMany_js_1 = require("./tools/documentsRecipientsCreateMany.js");
const documentsRecipientsDelete_js_1 = require("./tools/documentsRecipientsDelete.js");
const documentsRecipientsGet_js_1 = require("./tools/documentsRecipientsGet.js");
const documentsRecipientsUpdate_js_1 = require("./tools/documentsRecipientsUpdate.js");
const documentsRecipientsUpdateMany_js_1 = require("./tools/documentsRecipientsUpdateMany.js");
const documentsRedistribute_js_1 = require("./tools/documentsRedistribute.js");
const documentsUpdate_js_1 = require("./tools/documentsUpdate.js");
const templatesDelete_js_1 = require("./tools/templatesDelete.js");
const templatesDirectLinkCreate_js_1 = require("./tools/templatesDirectLinkCreate.js");
const templatesDirectLinkDelete_js_1 = require("./tools/templatesDirectLinkDelete.js");
const templatesDirectLinkToggle_js_1 = require("./tools/templatesDirectLinkToggle.js");
const templatesDuplicate_js_1 = require("./tools/templatesDuplicate.js");
const templatesFieldsCreate_js_1 = require("./tools/templatesFieldsCreate.js");
const templatesFieldsCreateMany_js_1 = require("./tools/templatesFieldsCreateMany.js");
const templatesFieldsDelete_js_1 = require("./tools/templatesFieldsDelete.js");
const templatesFieldsGet_js_1 = require("./tools/templatesFieldsGet.js");
const templatesFieldsUpdate_js_1 = require("./tools/templatesFieldsUpdate.js");
const templatesFieldsUpdateMany_js_1 = require("./tools/templatesFieldsUpdateMany.js");
const templatesFind_js_1 = require("./tools/templatesFind.js");
const templatesGet_js_1 = require("./tools/templatesGet.js");
const templatesMoveToTeam_js_1 = require("./tools/templatesMoveToTeam.js");
const templatesRecipientsCreate_js_1 = require("./tools/templatesRecipientsCreate.js");
const templatesRecipientsCreateMany_js_1 = require("./tools/templatesRecipientsCreateMany.js");
const templatesRecipientsDelete_js_1 = require("./tools/templatesRecipientsDelete.js");
const templatesRecipientsGet_js_1 = require("./tools/templatesRecipientsGet.js");
const templatesRecipientsUpdate_js_1 = require("./tools/templatesRecipientsUpdate.js");
const templatesRecipientsUpdateMany_js_1 = require("./tools/templatesRecipientsUpdateMany.js");
const templatesUpdate_js_1 = require("./tools/templatesUpdate.js");
const templatesUse_js_1 = require("./tools/templatesUse.js");
function createMCPServer(deps) {
    const server = new mcp_js_1.McpServer({
        name: "Documenso",
        version: "0.2.0",
    });
    const client = new core_js_1.DocumensoCore({
        serverURL: deps.serverURL,
        serverIdx: deps.serverIdx,
    });
    const scopes = new Set(deps.scopes ?? scopes_js_1.mcpScopes);
    const tool = (0, tools_js_1.createRegisterTool)(deps.logger, server, client, scopes);
    tool(documentsFind_js_1.tool$documentsFind);
    tool(documentsGet_js_1.tool$documentsGet);
    tool(documentsCreateV0_js_1.tool$documentsCreateV0);
    tool(documentsUpdate_js_1.tool$documentsUpdate);
    tool(documentsDelete_js_1.tool$documentsDelete);
    tool(documentsMoveToTeam_js_1.tool$documentsMoveToTeam);
    tool(documentsDistribute_js_1.tool$documentsDistribute);
    tool(documentsRedistribute_js_1.tool$documentsRedistribute);
    tool(documentsDuplicate_js_1.tool$documentsDuplicate);
    tool(templatesFind_js_1.tool$templatesFind);
    tool(templatesGet_js_1.tool$templatesGet);
    tool(templatesUpdate_js_1.tool$templatesUpdate);
    tool(templatesDuplicate_js_1.tool$templatesDuplicate);
    tool(templatesDelete_js_1.tool$templatesDelete);
    tool(templatesUse_js_1.tool$templatesUse);
    tool(templatesMoveToTeam_js_1.tool$templatesMoveToTeam);
    tool(documentsFieldsGet_js_1.tool$documentsFieldsGet);
    tool(documentsFieldsCreate_js_1.tool$documentsFieldsCreate);
    tool(documentsFieldsCreateMany_js_1.tool$documentsFieldsCreateMany);
    tool(documentsFieldsUpdate_js_1.tool$documentsFieldsUpdate);
    tool(documentsFieldsUpdateMany_js_1.tool$documentsFieldsUpdateMany);
    tool(documentsFieldsDelete_js_1.tool$documentsFieldsDelete);
    tool(documentsRecipientsGet_js_1.tool$documentsRecipientsGet);
    tool(documentsRecipientsCreate_js_1.tool$documentsRecipientsCreate);
    tool(documentsRecipientsCreateMany_js_1.tool$documentsRecipientsCreateMany);
    tool(documentsRecipientsUpdate_js_1.tool$documentsRecipientsUpdate);
    tool(documentsRecipientsUpdateMany_js_1.tool$documentsRecipientsUpdateMany);
    tool(documentsRecipientsDelete_js_1.tool$documentsRecipientsDelete);
    tool(templatesFieldsCreate_js_1.tool$templatesFieldsCreate);
    tool(templatesFieldsGet_js_1.tool$templatesFieldsGet);
    tool(templatesFieldsCreateMany_js_1.tool$templatesFieldsCreateMany);
    tool(templatesFieldsUpdate_js_1.tool$templatesFieldsUpdate);
    tool(templatesFieldsUpdateMany_js_1.tool$templatesFieldsUpdateMany);
    tool(templatesFieldsDelete_js_1.tool$templatesFieldsDelete);
    tool(templatesRecipientsGet_js_1.tool$templatesRecipientsGet);
    tool(templatesRecipientsCreate_js_1.tool$templatesRecipientsCreate);
    tool(templatesRecipientsCreateMany_js_1.tool$templatesRecipientsCreateMany);
    tool(templatesRecipientsUpdate_js_1.tool$templatesRecipientsUpdate);
    tool(templatesRecipientsUpdateMany_js_1.tool$templatesRecipientsUpdateMany);
    tool(templatesRecipientsDelete_js_1.tool$templatesRecipientsDelete);
    tool(templatesDirectLinkCreate_js_1.tool$templatesDirectLinkCreate);
    tool(templatesDirectLinkDelete_js_1.tool$templatesDirectLinkDelete);
    tool(templatesDirectLinkToggle_js_1.tool$templatesDirectLinkToggle);
    return server;
}
//# sourceMappingURL=server.js.map