/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentsAttachmentsCreate } from "../funcs/documentsAttachmentsCreate.js";
import { documentsAttachmentsDelete } from "../funcs/documentsAttachmentsDelete.js";
import { documentsAttachmentsFind } from "../funcs/documentsAttachmentsFind.js";
import { documentsAttachmentsUpdate } from "../funcs/documentsAttachmentsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class DocumentsAttachments extends ClientSDK {
  /**
   * Create attachment
   *
   * @remarks
   * Create a new attachment for a document
   */
  async create(
    request: operations.DocumentAttachmentCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.DocumentAttachmentCreateResponse> {
    return unwrapAsync(documentsAttachmentsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Update attachment
   *
   * @remarks
   * Update an existing attachment
   */
  async update(
    request: operations.DocumentAttachmentUpdateRequest,
    options?: RequestOptions,
  ): Promise<operations.DocumentAttachmentUpdateResponse> {
    return unwrapAsync(documentsAttachmentsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete attachment
   *
   * @remarks
   * Delete an attachment from a document
   */
  async delete(
    request: operations.DocumentAttachmentDeleteRequest,
    options?: RequestOptions,
  ): Promise<operations.DocumentAttachmentDeleteResponse> {
    return unwrapAsync(documentsAttachmentsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Find attachments
   *
   * @remarks
   * Find all attachments for a document
   */
  async find(
    request: operations.DocumentAttachmentFindRequest,
    options?: RequestOptions,
  ): Promise<operations.DocumentAttachmentFindResponse> {
    return unwrapAsync(documentsAttachmentsFind(
      this,
      request,
      options,
    ));
  }
}
