/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { recipientsGet } from "../funcs/recipientsGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Recipients extends ClientSDK {
  /**
   * Get recipient
   *
   * @remarks
   * Returns a single recipient. If you want to retrieve all the recipients for a document or template, use the "Get Document" or "Get Template" request.
   */
  async get(
    request: operations.RecipientGetRecipientRequest,
    options?: RequestOptions,
  ): Promise<operations.RecipientGetRecipientResponseBody> {
    return unwrapAsync(recipientsGet(
      this,
      request,
      options,
    ));
  }
}
