// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../index.js";

export interface CreateV0DocumentsResponseDocumentDocumentMeta {
    signingOrder: Documenso.CreateV0DocumentsResponseDocumentDocumentMetaSigningOrder;
    distributionMethod: Documenso.CreateV0DocumentsResponseDocumentDocumentMetaDistributionMethod;
    id: string;
    subject: string | null;
    message: string | null;
    timezone: string | null;
    dateFormat: string | null;
    redirectUrl: string | null;
    typedSignatureEnabled: boolean;
    uploadSignatureEnabled: boolean;
    drawSignatureEnabled: boolean;
    allowDictateNextSigner: boolean;
    language: string;
    emailSettings: Documenso.CreateV0DocumentsResponseDocumentDocumentMetaEmailSettings | null;
    emailId: string | null;
    emailReplyTo: string | null;
    envelopeExpirationPeriod: Documenso.CreateV0DocumentsResponseDocumentDocumentMetaEnvelopeExpirationPeriod | null;
    reminderSettings: Documenso.CreateV0DocumentsResponseDocumentDocumentMetaReminderSettings | null;
    password: string | null;
    documentId?: number;
}
