// This file was auto-generated by Fern from our API Definition.

export interface CreateV0DocumentsResponseDocumentFieldsItemFieldMetaRadioValuesItem {
    id: number;
    checked: boolean;
    value: string;
}
