// This file was auto-generated by Fern from our API Definition.

/** The type of authentication required for the recipient to access the document. */
export const CreateV0DocumentsResponseDocumentAuthOptionsGlobalAccessAuthItem = {
    Account: "ACCOUNT",
    TwoFactorAuth: "TWO_FACTOR_AUTH",
} as const;
export type CreateV0DocumentsResponseDocumentAuthOptionsGlobalAccessAuthItem =
    (typeof CreateV0DocumentsResponseDocumentAuthOptionsGlobalAccessAuthItem)[keyof typeof CreateV0DocumentsResponseDocumentAuthOptionsGlobalAccessAuthItem];
