// This file was auto-generated by Fern from our API Definition.

export const CreateV0DocumentsResponseDocumentRecipientsItemSigningStatus = {
    NotSigned: "NOT_SIGNED",
    Signed: "SIGNED",
    Rejected: "REJECTED",
} as const;
export type CreateV0DocumentsResponseDocumentRecipientsItemSigningStatus =
    (typeof CreateV0DocumentsResponseDocumentRecipientsItemSigningStatus)[keyof typeof CreateV0DocumentsResponseDocumentRecipientsItemSigningStatus];
