// This file was auto-generated by Fern from our API Definition.

/** Filter documents by the current status */
export const FindDocumentsRequestStatus = {
    Draft: "DRAFT",
    Pending: "PENDING",
    Completed: "COMPLETED",
    Rejected: "REJECTED",
    Cancelled: "CANCELLED",
} as const;
export type FindDocumentsRequestStatus = (typeof FindDocumentsRequestStatus)[keyof typeof FindDocumentsRequestStatus];
