// This file was auto-generated by Fern from our API Definition.

export const GetDocumentsResponseFieldsItemFieldMetaNumberOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type GetDocumentsResponseFieldsItemFieldMetaNumberOverflow =
    (typeof GetDocumentsResponseFieldsItemFieldMetaNumberOverflow)[keyof typeof GetDocumentsResponseFieldsItemFieldMetaNumberOverflow];
