// This file was auto-generated by Fern from our API Definition.

export const GetDocumentsResponseDocumentDataType = {
    S3Path: "S3_PATH",
    Bytes: "BYTES",
    Bytes64: "BYTES_64",
} as const;
export type GetDocumentsResponseDocumentDataType =
    (typeof GetDocumentsResponseDocumentDataType)[keyof typeof GetDocumentsResponseDocumentDataType];
