// This file was auto-generated by Fern from our API Definition.

export const GetDocumentsResponseFieldsItemFieldMetaRadioOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type GetDocumentsResponseFieldsItemFieldMetaRadioOverflow =
    (typeof GetDocumentsResponseFieldsItemFieldMetaRadioOverflow)[keyof typeof GetDocumentsResponseFieldsItemFieldMetaRadioOverflow];
