// This file was auto-generated by Fern from our API Definition.

export const UpdateDocumentsRequestMetaEnvelopeExpirationPeriodAmountUnit = {
    Day: "day",
    Week: "week",
    Month: "month",
    Year: "year",
} as const;
export type UpdateDocumentsRequestMetaEnvelopeExpirationPeriodAmountUnit =
    (typeof UpdateDocumentsRequestMetaEnvelopeExpirationPeriodAmountUnit)[keyof typeof UpdateDocumentsRequestMetaEnvelopeExpirationPeriodAmountUnit];
