// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaNameOverflow } from "./EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaNameOverflow.js";
import { EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaNameTextAlign } from "./EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaNameTextAlign.js";

export const EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaName: core.serialization.ObjectSchema<
    serializers.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaName.Raw,
    Documenso.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaName
> = core.serialization.object({
    label: core.serialization.string().optional(),
    placeholder: core.serialization.string().optional(),
    required: core.serialization.boolean().optional(),
    readOnly: core.serialization.boolean().optional(),
    fontSize: core.serialization.number().optional(),
    overflow: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaNameOverflow.optional(),
    textAlign: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaNameTextAlign.optional(),
});

export declare namespace EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaName {
    export interface Raw {
        label?: string | null;
        placeholder?: string | null;
        required?: boolean | null;
        readOnly?: boolean | null;
        fontSize?: number | null;
        overflow?: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaNameOverflow.Raw | null;
        textAlign?: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaNameTextAlign.Raw | null;
    }
}
