// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseAuthOptions } from "./EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseAuthOptions.js";
import { EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItem } from "./EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItem.js";
import { EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseReadStatus } from "./EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseReadStatus.js";
import { EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseRole } from "./EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseRole.js";
import { EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseSendStatus } from "./EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseSendStatus.js";
import { EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseSigningStatus } from "./EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseSigningStatus.js";

export const EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponse: core.serialization.ObjectSchema<
    serializers.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponse.Raw,
    Documenso.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponse
> = core.serialization.object({
    envelopeId: core.serialization.string(),
    role: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseRole,
    readStatus: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseReadStatus,
    signingStatus: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseSigningStatus,
    sendStatus: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseSendStatus,
    id: core.serialization.number(),
    email: core.serialization.string(),
    name: core.serialization.string(),
    token: core.serialization.string(),
    documentDeletedAt: core.serialization.string().nullable(),
    expired: core.serialization.string().nullable(),
    expiresAt: core.serialization.string().nullable(),
    expirationNotifiedAt: core.serialization.string().nullable(),
    signedAt: core.serialization.string().nullable(),
    authOptions: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseAuthOptions.nullable(),
    signingOrder: core.serialization.number().nullable(),
    rejectionReason: core.serialization.string().nullable(),
    fields: core.serialization.list(EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItem),
});

export declare namespace EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponse {
    export interface Raw {
        envelopeId: string;
        role: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseRole.Raw;
        readStatus: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseReadStatus.Raw;
        signingStatus: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseSigningStatus.Raw;
        sendStatus: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseSendStatus.Raw;
        id: number;
        email: string;
        name: string;
        token: string;
        documentDeletedAt?: string | null;
        expired?: string | null;
        expiresAt?: string | null;
        expirationNotifiedAt?: string | null;
        signedAt?: string | null;
        authOptions?: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseAuthOptions.Raw | null;
        signingOrder?: number | null;
        rejectionReason?: string | null;
        fields: EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItem.Raw[];
    }
}
