// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaRadioDirection: core.serialization.Schema<
    serializers.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaRadioDirection.Raw,
    Documenso.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaRadioDirection
> = core.serialization.enum_(["vertical", "horizontal"]);

export declare namespace EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaRadioDirection {
    export type Raw = "vertical" | "horizontal";
}
