// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaDropdownValuesItem: core.serialization.ObjectSchema<
    serializers.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaDropdownValuesItem.Raw,
    Documenso.EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaDropdownValuesItem
> = core.serialization.object({
    value: core.serialization.string(),
});

export declare namespace EnvelopeRecipientRejectOnBehalfOfEnvelopeRecipientsResponseFieldsItemFieldMetaDropdownValuesItem {
    export interface Raw {
        value: string;
    }
}
