// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../index.js";

export interface TemplateGetManyTemplateResponseDataItemFieldsItemFieldMetaCheckbox {
    label?: string;
    placeholder?: string;
    required?: boolean;
    readOnly?: boolean;
    fontSize?: number;
    overflow?: Documenso.TemplateGetManyTemplateResponseDataItemFieldsItemFieldMetaCheckboxOverflow;
    values?: Documenso.TemplateGetManyTemplateResponseDataItemFieldsItemFieldMetaCheckboxValuesItem[];
    validationRule?: string;
    validationLength?: number;
    direction: Documenso.TemplateGetManyTemplateResponseDataItemFieldsItemFieldMetaCheckboxDirection;
}
