// This file was auto-generated by Fern from our API Definition.

export const TemplateGetManyTemplateResponseDataItemFieldsItemFieldMetaEmailOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type TemplateGetManyTemplateResponseDataItemFieldsItemFieldMetaEmailOverflow =
    (typeof TemplateGetManyTemplateResponseDataItemFieldsItemFieldMetaEmailOverflow)[keyof typeof TemplateGetManyTemplateResponseDataItemFieldsItemFieldMetaEmailOverflow];
