/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EnvelopeCertificateDownloadPdfRequest = {
  /**
   * The ID of the envelope to download the certificate for.
   */
  envelopeId: string;
};

export type EnvelopeCertificateDownloadPdfResponse = {
  headers: { [k: string]: Array<string> };
  result?: any | undefined;
};

/** @internal */
export const EnvelopeCertificateDownloadPdfRequest$inboundSchema: z.ZodType<
  EnvelopeCertificateDownloadPdfRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  envelopeId: z.string(),
});
/** @internal */
export type EnvelopeCertificateDownloadPdfRequest$Outbound = {
  envelopeId: string;
};

/** @internal */
export const EnvelopeCertificateDownloadPdfRequest$outboundSchema: z.ZodType<
  EnvelopeCertificateDownloadPdfRequest$Outbound,
  z.ZodTypeDef,
  EnvelopeCertificateDownloadPdfRequest
> = z.object({
  envelopeId: z.string(),
});

export function envelopeCertificateDownloadPdfRequestToJSON(
  envelopeCertificateDownloadPdfRequest: EnvelopeCertificateDownloadPdfRequest,
): string {
  return JSON.stringify(
    EnvelopeCertificateDownloadPdfRequest$outboundSchema.parse(
      envelopeCertificateDownloadPdfRequest,
    ),
  );
}
export function envelopeCertificateDownloadPdfRequestFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeCertificateDownloadPdfRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeCertificateDownloadPdfRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeCertificateDownloadPdfRequest' from JSON`,
  );
}

/** @internal */
export const EnvelopeCertificateDownloadPdfResponse$inboundSchema: z.ZodType<
  EnvelopeCertificateDownloadPdfResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});
/** @internal */
export type EnvelopeCertificateDownloadPdfResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result?: any | undefined;
};

/** @internal */
export const EnvelopeCertificateDownloadPdfResponse$outboundSchema: z.ZodType<
  EnvelopeCertificateDownloadPdfResponse$Outbound,
  z.ZodTypeDef,
  EnvelopeCertificateDownloadPdfResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

export function envelopeCertificateDownloadPdfResponseToJSON(
  envelopeCertificateDownloadPdfResponse:
    EnvelopeCertificateDownloadPdfResponse,
): string {
  return JSON.stringify(
    EnvelopeCertificateDownloadPdfResponse$outboundSchema.parse(
      envelopeCertificateDownloadPdfResponse,
    ),
  );
}
export function envelopeCertificateDownloadPdfResponseFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeCertificateDownloadPdfResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeCertificateDownloadPdfResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeCertificateDownloadPdfResponse' from JSON`,
  );
}
