/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const EnvelopeRecipientUpdateManyEmailEnum = {
  Unknown: "",
} as const;
export type EnvelopeRecipientUpdateManyEmailEnum = ClosedEnum<
  typeof EnvelopeRecipientUpdateManyEmailEnum
>;

export type EnvelopeRecipientUpdateManyEmailUnion =
  | EnvelopeRecipientUpdateManyEmailEnum
  | string;

export const EnvelopeRecipientUpdateManyRoleRequest = {
  Cc: "CC",
  Signer: "SIGNER",
  Viewer: "VIEWER",
  Approver: "APPROVER",
  Assistant: "ASSISTANT",
} as const;
export type EnvelopeRecipientUpdateManyRoleRequest = ClosedEnum<
  typeof EnvelopeRecipientUpdateManyRoleRequest
>;

export const EnvelopeRecipientUpdateManyAccessAuthRequest = {
  Account: "ACCOUNT",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
} as const;
export type EnvelopeRecipientUpdateManyAccessAuthRequest = ClosedEnum<
  typeof EnvelopeRecipientUpdateManyAccessAuthRequest
>;

export const EnvelopeRecipientUpdateManyActionAuthRequest = {
  Account: "ACCOUNT",
  Passkey: "PASSKEY",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
  Password: "PASSWORD",
  ExplicitNone: "EXPLICIT_NONE",
} as const;
export type EnvelopeRecipientUpdateManyActionAuthRequest = ClosedEnum<
  typeof EnvelopeRecipientUpdateManyActionAuthRequest
>;

export type EnvelopeRecipientUpdateManyDataRequest = {
  id: number;
  email?: EnvelopeRecipientUpdateManyEmailEnum | string | undefined;
  name?: string | undefined;
  role?: EnvelopeRecipientUpdateManyRoleRequest | undefined;
  signingOrder?: number | undefined;
  accessAuth?: Array<EnvelopeRecipientUpdateManyAccessAuthRequest> | undefined;
  actionAuth?: Array<EnvelopeRecipientUpdateManyActionAuthRequest> | undefined;
};

export type EnvelopeRecipientUpdateManyRequest = {
  envelopeId: string;
  data: Array<EnvelopeRecipientUpdateManyDataRequest>;
};

export const EnvelopeRecipientUpdateManyRoleResponse = {
  Cc: "CC",
  Signer: "SIGNER",
  Viewer: "VIEWER",
  Approver: "APPROVER",
  Assistant: "ASSISTANT",
} as const;
export type EnvelopeRecipientUpdateManyRoleResponse = ClosedEnum<
  typeof EnvelopeRecipientUpdateManyRoleResponse
>;

export const EnvelopeRecipientUpdateManyReadStatus = {
  NotOpened: "NOT_OPENED",
  Opened: "OPENED",
} as const;
export type EnvelopeRecipientUpdateManyReadStatus = ClosedEnum<
  typeof EnvelopeRecipientUpdateManyReadStatus
>;

export const EnvelopeRecipientUpdateManySigningStatus = {
  NotSigned: "NOT_SIGNED",
  Signed: "SIGNED",
  Rejected: "REJECTED",
} as const;
export type EnvelopeRecipientUpdateManySigningStatus = ClosedEnum<
  typeof EnvelopeRecipientUpdateManySigningStatus
>;

export const EnvelopeRecipientUpdateManySendStatus = {
  NotSent: "NOT_SENT",
  Sent: "SENT",
} as const;
export type EnvelopeRecipientUpdateManySendStatus = ClosedEnum<
  typeof EnvelopeRecipientUpdateManySendStatus
>;

export const EnvelopeRecipientUpdateManyAuthOptionsAccessAuth = {
  Account: "ACCOUNT",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
} as const;
export type EnvelopeRecipientUpdateManyAuthOptionsAccessAuth = ClosedEnum<
  typeof EnvelopeRecipientUpdateManyAuthOptionsAccessAuth
>;

export const EnvelopeRecipientUpdateManyAuthOptionsActionAuth = {
  Account: "ACCOUNT",
  Passkey: "PASSKEY",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
  Password: "PASSWORD",
  ExplicitNone: "EXPLICIT_NONE",
} as const;
export type EnvelopeRecipientUpdateManyAuthOptionsActionAuth = ClosedEnum<
  typeof EnvelopeRecipientUpdateManyAuthOptionsActionAuth
>;

export type EnvelopeRecipientUpdateManyAuthOptions = {
  accessAuth: Array<EnvelopeRecipientUpdateManyAuthOptionsAccessAuth>;
  actionAuth: Array<EnvelopeRecipientUpdateManyAuthOptionsActionAuth>;
};

export type EnvelopeRecipientUpdateManyDataResponse = {
  envelopeId: string;
  role: EnvelopeRecipientUpdateManyRoleResponse;
  readStatus: EnvelopeRecipientUpdateManyReadStatus;
  signingStatus: EnvelopeRecipientUpdateManySigningStatus;
  sendStatus: EnvelopeRecipientUpdateManySendStatus;
  id: number;
  email: string;
  name: string;
  token: string;
  documentDeletedAt: string | null;
  expired: string | null;
  signedAt: string | null;
  authOptions: EnvelopeRecipientUpdateManyAuthOptions | null;
  signingOrder: number | null;
  rejectionReason: string | null;
  documentId?: number | null | undefined;
  templateId?: number | null | undefined;
};

/**
 * Successful response
 */
export type EnvelopeRecipientUpdateManyResponse = {
  data: Array<EnvelopeRecipientUpdateManyDataResponse>;
};

/** @internal */
export const EnvelopeRecipientUpdateManyEmailEnum$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyEmailEnum> = z.nativeEnum(
    EnvelopeRecipientUpdateManyEmailEnum,
  );
/** @internal */
export const EnvelopeRecipientUpdateManyEmailEnum$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyEmailEnum> =
    EnvelopeRecipientUpdateManyEmailEnum$inboundSchema;

/** @internal */
export const EnvelopeRecipientUpdateManyEmailUnion$inboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyEmailUnion,
  z.ZodTypeDef,
  unknown
> = z.union([EnvelopeRecipientUpdateManyEmailEnum$inboundSchema, z.string()]);
/** @internal */
export type EnvelopeRecipientUpdateManyEmailUnion$Outbound = string | string;

/** @internal */
export const EnvelopeRecipientUpdateManyEmailUnion$outboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyEmailUnion$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientUpdateManyEmailUnion
> = z.union([EnvelopeRecipientUpdateManyEmailEnum$outboundSchema, z.string()]);

export function envelopeRecipientUpdateManyEmailUnionToJSON(
  envelopeRecipientUpdateManyEmailUnion: EnvelopeRecipientUpdateManyEmailUnion,
): string {
  return JSON.stringify(
    EnvelopeRecipientUpdateManyEmailUnion$outboundSchema.parse(
      envelopeRecipientUpdateManyEmailUnion,
    ),
  );
}
export function envelopeRecipientUpdateManyEmailUnionFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientUpdateManyEmailUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientUpdateManyEmailUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientUpdateManyEmailUnion' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientUpdateManyRoleRequest$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyRoleRequest> = z.nativeEnum(
    EnvelopeRecipientUpdateManyRoleRequest,
  );
/** @internal */
export const EnvelopeRecipientUpdateManyRoleRequest$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyRoleRequest> =
    EnvelopeRecipientUpdateManyRoleRequest$inboundSchema;

/** @internal */
export const EnvelopeRecipientUpdateManyAccessAuthRequest$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyAccessAuthRequest> = z
    .nativeEnum(EnvelopeRecipientUpdateManyAccessAuthRequest);
/** @internal */
export const EnvelopeRecipientUpdateManyAccessAuthRequest$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyAccessAuthRequest> =
    EnvelopeRecipientUpdateManyAccessAuthRequest$inboundSchema;

/** @internal */
export const EnvelopeRecipientUpdateManyActionAuthRequest$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyActionAuthRequest> = z
    .nativeEnum(EnvelopeRecipientUpdateManyActionAuthRequest);
/** @internal */
export const EnvelopeRecipientUpdateManyActionAuthRequest$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyActionAuthRequest> =
    EnvelopeRecipientUpdateManyActionAuthRequest$inboundSchema;

/** @internal */
export const EnvelopeRecipientUpdateManyDataRequest$inboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyDataRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number(),
  email: z.union([
    EnvelopeRecipientUpdateManyEmailEnum$inboundSchema,
    z.string(),
  ]).optional(),
  name: z.string().optional(),
  role: EnvelopeRecipientUpdateManyRoleRequest$inboundSchema.optional(),
  signingOrder: z.number().optional(),
  accessAuth: z.array(
    EnvelopeRecipientUpdateManyAccessAuthRequest$inboundSchema,
  ).optional(),
  actionAuth: z.array(
    EnvelopeRecipientUpdateManyActionAuthRequest$inboundSchema,
  ).optional(),
});
/** @internal */
export type EnvelopeRecipientUpdateManyDataRequest$Outbound = {
  id: number;
  email?: string | string | undefined;
  name?: string | undefined;
  role?: string | undefined;
  signingOrder?: number | undefined;
  accessAuth?: Array<string> | undefined;
  actionAuth?: Array<string> | undefined;
};

/** @internal */
export const EnvelopeRecipientUpdateManyDataRequest$outboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyDataRequest$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientUpdateManyDataRequest
> = z.object({
  id: z.number(),
  email: z.union([
    EnvelopeRecipientUpdateManyEmailEnum$outboundSchema,
    z.string(),
  ]).optional(),
  name: z.string().optional(),
  role: EnvelopeRecipientUpdateManyRoleRequest$outboundSchema.optional(),
  signingOrder: z.number().optional(),
  accessAuth: z.array(
    EnvelopeRecipientUpdateManyAccessAuthRequest$outboundSchema,
  ).optional(),
  actionAuth: z.array(
    EnvelopeRecipientUpdateManyActionAuthRequest$outboundSchema,
  ).optional(),
});

export function envelopeRecipientUpdateManyDataRequestToJSON(
  envelopeRecipientUpdateManyDataRequest:
    EnvelopeRecipientUpdateManyDataRequest,
): string {
  return JSON.stringify(
    EnvelopeRecipientUpdateManyDataRequest$outboundSchema.parse(
      envelopeRecipientUpdateManyDataRequest,
    ),
  );
}
export function envelopeRecipientUpdateManyDataRequestFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientUpdateManyDataRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientUpdateManyDataRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientUpdateManyDataRequest' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientUpdateManyRequest$inboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  envelopeId: z.string(),
  data: z.array(
    z.lazy(() => EnvelopeRecipientUpdateManyDataRequest$inboundSchema),
  ),
});
/** @internal */
export type EnvelopeRecipientUpdateManyRequest$Outbound = {
  envelopeId: string;
  data: Array<EnvelopeRecipientUpdateManyDataRequest$Outbound>;
};

/** @internal */
export const EnvelopeRecipientUpdateManyRequest$outboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyRequest$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientUpdateManyRequest
> = z.object({
  envelopeId: z.string(),
  data: z.array(
    z.lazy(() => EnvelopeRecipientUpdateManyDataRequest$outboundSchema),
  ),
});

export function envelopeRecipientUpdateManyRequestToJSON(
  envelopeRecipientUpdateManyRequest: EnvelopeRecipientUpdateManyRequest,
): string {
  return JSON.stringify(
    EnvelopeRecipientUpdateManyRequest$outboundSchema.parse(
      envelopeRecipientUpdateManyRequest,
    ),
  );
}
export function envelopeRecipientUpdateManyRequestFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientUpdateManyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientUpdateManyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientUpdateManyRequest' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientUpdateManyRoleResponse$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyRoleResponse> = z
    .nativeEnum(EnvelopeRecipientUpdateManyRoleResponse);
/** @internal */
export const EnvelopeRecipientUpdateManyRoleResponse$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyRoleResponse> =
    EnvelopeRecipientUpdateManyRoleResponse$inboundSchema;

/** @internal */
export const EnvelopeRecipientUpdateManyReadStatus$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyReadStatus> = z.nativeEnum(
    EnvelopeRecipientUpdateManyReadStatus,
  );
/** @internal */
export const EnvelopeRecipientUpdateManyReadStatus$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyReadStatus> =
    EnvelopeRecipientUpdateManyReadStatus$inboundSchema;

/** @internal */
export const EnvelopeRecipientUpdateManySigningStatus$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManySigningStatus> = z
    .nativeEnum(EnvelopeRecipientUpdateManySigningStatus);
/** @internal */
export const EnvelopeRecipientUpdateManySigningStatus$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManySigningStatus> =
    EnvelopeRecipientUpdateManySigningStatus$inboundSchema;

/** @internal */
export const EnvelopeRecipientUpdateManySendStatus$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManySendStatus> = z.nativeEnum(
    EnvelopeRecipientUpdateManySendStatus,
  );
/** @internal */
export const EnvelopeRecipientUpdateManySendStatus$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManySendStatus> =
    EnvelopeRecipientUpdateManySendStatus$inboundSchema;

/** @internal */
export const EnvelopeRecipientUpdateManyAuthOptionsAccessAuth$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyAuthOptionsAccessAuth> = z
    .nativeEnum(EnvelopeRecipientUpdateManyAuthOptionsAccessAuth);
/** @internal */
export const EnvelopeRecipientUpdateManyAuthOptionsAccessAuth$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyAuthOptionsAccessAuth> =
    EnvelopeRecipientUpdateManyAuthOptionsAccessAuth$inboundSchema;

/** @internal */
export const EnvelopeRecipientUpdateManyAuthOptionsActionAuth$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyAuthOptionsActionAuth> = z
    .nativeEnum(EnvelopeRecipientUpdateManyAuthOptionsActionAuth);
/** @internal */
export const EnvelopeRecipientUpdateManyAuthOptionsActionAuth$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientUpdateManyAuthOptionsActionAuth> =
    EnvelopeRecipientUpdateManyAuthOptionsActionAuth$inboundSchema;

/** @internal */
export const EnvelopeRecipientUpdateManyAuthOptions$inboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyAuthOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  accessAuth: z.array(
    EnvelopeRecipientUpdateManyAuthOptionsAccessAuth$inboundSchema,
  ),
  actionAuth: z.array(
    EnvelopeRecipientUpdateManyAuthOptionsActionAuth$inboundSchema,
  ),
});
/** @internal */
export type EnvelopeRecipientUpdateManyAuthOptions$Outbound = {
  accessAuth: Array<string>;
  actionAuth: Array<string>;
};

/** @internal */
export const EnvelopeRecipientUpdateManyAuthOptions$outboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyAuthOptions$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientUpdateManyAuthOptions
> = z.object({
  accessAuth: z.array(
    EnvelopeRecipientUpdateManyAuthOptionsAccessAuth$outboundSchema,
  ),
  actionAuth: z.array(
    EnvelopeRecipientUpdateManyAuthOptionsActionAuth$outboundSchema,
  ),
});

export function envelopeRecipientUpdateManyAuthOptionsToJSON(
  envelopeRecipientUpdateManyAuthOptions:
    EnvelopeRecipientUpdateManyAuthOptions,
): string {
  return JSON.stringify(
    EnvelopeRecipientUpdateManyAuthOptions$outboundSchema.parse(
      envelopeRecipientUpdateManyAuthOptions,
    ),
  );
}
export function envelopeRecipientUpdateManyAuthOptionsFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientUpdateManyAuthOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientUpdateManyAuthOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientUpdateManyAuthOptions' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientUpdateManyDataResponse$inboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyDataResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  envelopeId: z.string(),
  role: EnvelopeRecipientUpdateManyRoleResponse$inboundSchema,
  readStatus: EnvelopeRecipientUpdateManyReadStatus$inboundSchema,
  signingStatus: EnvelopeRecipientUpdateManySigningStatus$inboundSchema,
  sendStatus: EnvelopeRecipientUpdateManySendStatus$inboundSchema,
  id: z.number(),
  email: z.string(),
  name: z.string(),
  token: z.string(),
  documentDeletedAt: z.nullable(z.string()),
  expired: z.nullable(z.string()),
  signedAt: z.nullable(z.string()),
  authOptions: z.nullable(
    z.lazy(() => EnvelopeRecipientUpdateManyAuthOptions$inboundSchema),
  ),
  signingOrder: z.nullable(z.number()),
  rejectionReason: z.nullable(z.string()),
  documentId: z.nullable(z.number()).optional(),
  templateId: z.nullable(z.number()).optional(),
});
/** @internal */
export type EnvelopeRecipientUpdateManyDataResponse$Outbound = {
  envelopeId: string;
  role: string;
  readStatus: string;
  signingStatus: string;
  sendStatus: string;
  id: number;
  email: string;
  name: string;
  token: string;
  documentDeletedAt: string | null;
  expired: string | null;
  signedAt: string | null;
  authOptions: EnvelopeRecipientUpdateManyAuthOptions$Outbound | null;
  signingOrder: number | null;
  rejectionReason: string | null;
  documentId?: number | null | undefined;
  templateId?: number | null | undefined;
};

/** @internal */
export const EnvelopeRecipientUpdateManyDataResponse$outboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyDataResponse$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientUpdateManyDataResponse
> = z.object({
  envelopeId: z.string(),
  role: EnvelopeRecipientUpdateManyRoleResponse$outboundSchema,
  readStatus: EnvelopeRecipientUpdateManyReadStatus$outboundSchema,
  signingStatus: EnvelopeRecipientUpdateManySigningStatus$outboundSchema,
  sendStatus: EnvelopeRecipientUpdateManySendStatus$outboundSchema,
  id: z.number(),
  email: z.string(),
  name: z.string(),
  token: z.string(),
  documentDeletedAt: z.nullable(z.string()),
  expired: z.nullable(z.string()),
  signedAt: z.nullable(z.string()),
  authOptions: z.nullable(
    z.lazy(() => EnvelopeRecipientUpdateManyAuthOptions$outboundSchema),
  ),
  signingOrder: z.nullable(z.number()),
  rejectionReason: z.nullable(z.string()),
  documentId: z.nullable(z.number()).optional(),
  templateId: z.nullable(z.number()).optional(),
});

export function envelopeRecipientUpdateManyDataResponseToJSON(
  envelopeRecipientUpdateManyDataResponse:
    EnvelopeRecipientUpdateManyDataResponse,
): string {
  return JSON.stringify(
    EnvelopeRecipientUpdateManyDataResponse$outboundSchema.parse(
      envelopeRecipientUpdateManyDataResponse,
    ),
  );
}
export function envelopeRecipientUpdateManyDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  EnvelopeRecipientUpdateManyDataResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientUpdateManyDataResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EnvelopeRecipientUpdateManyDataResponse' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientUpdateManyResponse$inboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(
    z.lazy(() => EnvelopeRecipientUpdateManyDataResponse$inboundSchema),
  ),
});
/** @internal */
export type EnvelopeRecipientUpdateManyResponse$Outbound = {
  data: Array<EnvelopeRecipientUpdateManyDataResponse$Outbound>;
};

/** @internal */
export const EnvelopeRecipientUpdateManyResponse$outboundSchema: z.ZodType<
  EnvelopeRecipientUpdateManyResponse$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientUpdateManyResponse
> = z.object({
  data: z.array(
    z.lazy(() => EnvelopeRecipientUpdateManyDataResponse$outboundSchema),
  ),
});

export function envelopeRecipientUpdateManyResponseToJSON(
  envelopeRecipientUpdateManyResponse: EnvelopeRecipientUpdateManyResponse,
): string {
  return JSON.stringify(
    EnvelopeRecipientUpdateManyResponse$outboundSchema.parse(
      envelopeRecipientUpdateManyResponse,
    ),
  );
}
export function envelopeRecipientUpdateManyResponseFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientUpdateManyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientUpdateManyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientUpdateManyResponse' from JSON`,
  );
}
