/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EnvelopeItemDeleteRequest = {
  envelopeId: string;
  envelopeItemId: string;
};

/**
 * Successful response
 */
export type EnvelopeItemDeleteResponse = {
  success: boolean;
};

/** @internal */
export const EnvelopeItemDeleteRequest$inboundSchema: z.ZodType<
  EnvelopeItemDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  envelopeId: z.string(),
  envelopeItemId: z.string(),
});
/** @internal */
export type EnvelopeItemDeleteRequest$Outbound = {
  envelopeId: string;
  envelopeItemId: string;
};

/** @internal */
export const EnvelopeItemDeleteRequest$outboundSchema: z.ZodType<
  EnvelopeItemDeleteRequest$Outbound,
  z.ZodTypeDef,
  EnvelopeItemDeleteRequest
> = z.object({
  envelopeId: z.string(),
  envelopeItemId: z.string(),
});

export function envelopeItemDeleteRequestToJSON(
  envelopeItemDeleteRequest: EnvelopeItemDeleteRequest,
): string {
  return JSON.stringify(
    EnvelopeItemDeleteRequest$outboundSchema.parse(envelopeItemDeleteRequest),
  );
}
export function envelopeItemDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeItemDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeItemDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeItemDeleteRequest' from JSON`,
  );
}

/** @internal */
export const EnvelopeItemDeleteResponse$inboundSchema: z.ZodType<
  EnvelopeItemDeleteResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
});
/** @internal */
export type EnvelopeItemDeleteResponse$Outbound = {
  success: boolean;
};

/** @internal */
export const EnvelopeItemDeleteResponse$outboundSchema: z.ZodType<
  EnvelopeItemDeleteResponse$Outbound,
  z.ZodTypeDef,
  EnvelopeItemDeleteResponse
> = z.object({
  success: z.boolean(),
});

export function envelopeItemDeleteResponseToJSON(
  envelopeItemDeleteResponse: EnvelopeItemDeleteResponse,
): string {
  return JSON.stringify(
    EnvelopeItemDeleteResponse$outboundSchema.parse(envelopeItemDeleteResponse),
  );
}
export function envelopeItemDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeItemDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeItemDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeItemDeleteResponse' from JSON`,
  );
}
