/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const EnvelopeRecipientCreateManyRoleRequest = {
  Cc: "CC",
  Signer: "SIGNER",
  Viewer: "VIEWER",
  Approver: "APPROVER",
  Assistant: "ASSISTANT",
} as const;
export type EnvelopeRecipientCreateManyRoleRequest = ClosedEnum<
  typeof EnvelopeRecipientCreateManyRoleRequest
>;

export const EnvelopeRecipientCreateManyAccessAuthRequest = {
  Account: "ACCOUNT",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
} as const;
export type EnvelopeRecipientCreateManyAccessAuthRequest = ClosedEnum<
  typeof EnvelopeRecipientCreateManyAccessAuthRequest
>;

export const EnvelopeRecipientCreateManyActionAuthRequest = {
  Account: "ACCOUNT",
  Passkey: "PASSKEY",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
  Password: "PASSWORD",
  ExplicitNone: "EXPLICIT_NONE",
} as const;
export type EnvelopeRecipientCreateManyActionAuthRequest = ClosedEnum<
  typeof EnvelopeRecipientCreateManyActionAuthRequest
>;

export type EnvelopeRecipientCreateManyDataRequest = {
  email: string;
  name: string;
  role: EnvelopeRecipientCreateManyRoleRequest;
  signingOrder?: number | undefined;
  accessAuth?: Array<EnvelopeRecipientCreateManyAccessAuthRequest> | undefined;
  actionAuth?: Array<EnvelopeRecipientCreateManyActionAuthRequest> | undefined;
};

export type EnvelopeRecipientCreateManyRequest = {
  envelopeId: string;
  data: Array<EnvelopeRecipientCreateManyDataRequest>;
};

export const EnvelopeRecipientCreateManyRoleResponse = {
  Cc: "CC",
  Signer: "SIGNER",
  Viewer: "VIEWER",
  Approver: "APPROVER",
  Assistant: "ASSISTANT",
} as const;
export type EnvelopeRecipientCreateManyRoleResponse = ClosedEnum<
  typeof EnvelopeRecipientCreateManyRoleResponse
>;

export const EnvelopeRecipientCreateManyReadStatus = {
  NotOpened: "NOT_OPENED",
  Opened: "OPENED",
} as const;
export type EnvelopeRecipientCreateManyReadStatus = ClosedEnum<
  typeof EnvelopeRecipientCreateManyReadStatus
>;

export const EnvelopeRecipientCreateManySigningStatus = {
  NotSigned: "NOT_SIGNED",
  Signed: "SIGNED",
  Rejected: "REJECTED",
} as const;
export type EnvelopeRecipientCreateManySigningStatus = ClosedEnum<
  typeof EnvelopeRecipientCreateManySigningStatus
>;

export const EnvelopeRecipientCreateManySendStatus = {
  NotSent: "NOT_SENT",
  Sent: "SENT",
} as const;
export type EnvelopeRecipientCreateManySendStatus = ClosedEnum<
  typeof EnvelopeRecipientCreateManySendStatus
>;

export const EnvelopeRecipientCreateManyAccessAuthResponse = {
  Account: "ACCOUNT",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
} as const;
export type EnvelopeRecipientCreateManyAccessAuthResponse = ClosedEnum<
  typeof EnvelopeRecipientCreateManyAccessAuthResponse
>;

export const EnvelopeRecipientCreateManyActionAuthResponse = {
  Account: "ACCOUNT",
  Passkey: "PASSKEY",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
  Password: "PASSWORD",
  ExplicitNone: "EXPLICIT_NONE",
} as const;
export type EnvelopeRecipientCreateManyActionAuthResponse = ClosedEnum<
  typeof EnvelopeRecipientCreateManyActionAuthResponse
>;

export type EnvelopeRecipientCreateManyAuthOptions = {
  accessAuth: Array<EnvelopeRecipientCreateManyAccessAuthResponse>;
  actionAuth: Array<EnvelopeRecipientCreateManyActionAuthResponse>;
};

export type EnvelopeRecipientCreateManyDataResponse = {
  envelopeId: string;
  role: EnvelopeRecipientCreateManyRoleResponse;
  readStatus: EnvelopeRecipientCreateManyReadStatus;
  signingStatus: EnvelopeRecipientCreateManySigningStatus;
  sendStatus: EnvelopeRecipientCreateManySendStatus;
  id: number;
  email: string;
  name: string;
  token: string;
  documentDeletedAt: string | null;
  expired: string | null;
  signedAt: string | null;
  authOptions: EnvelopeRecipientCreateManyAuthOptions | null;
  signingOrder: number | null;
  rejectionReason: string | null;
};

/**
 * Successful response
 */
export type EnvelopeRecipientCreateManyResponse = {
  data: Array<EnvelopeRecipientCreateManyDataResponse>;
};

/** @internal */
export const EnvelopeRecipientCreateManyRoleRequest$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyRoleRequest> = z.nativeEnum(
    EnvelopeRecipientCreateManyRoleRequest,
  );
/** @internal */
export const EnvelopeRecipientCreateManyRoleRequest$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyRoleRequest> =
    EnvelopeRecipientCreateManyRoleRequest$inboundSchema;

/** @internal */
export const EnvelopeRecipientCreateManyAccessAuthRequest$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyAccessAuthRequest> = z
    .nativeEnum(EnvelopeRecipientCreateManyAccessAuthRequest);
/** @internal */
export const EnvelopeRecipientCreateManyAccessAuthRequest$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyAccessAuthRequest> =
    EnvelopeRecipientCreateManyAccessAuthRequest$inboundSchema;

/** @internal */
export const EnvelopeRecipientCreateManyActionAuthRequest$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyActionAuthRequest> = z
    .nativeEnum(EnvelopeRecipientCreateManyActionAuthRequest);
/** @internal */
export const EnvelopeRecipientCreateManyActionAuthRequest$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyActionAuthRequest> =
    EnvelopeRecipientCreateManyActionAuthRequest$inboundSchema;

/** @internal */
export const EnvelopeRecipientCreateManyDataRequest$inboundSchema: z.ZodType<
  EnvelopeRecipientCreateManyDataRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  name: z.string(),
  role: EnvelopeRecipientCreateManyRoleRequest$inboundSchema,
  signingOrder: z.number().optional(),
  accessAuth: z.array(
    EnvelopeRecipientCreateManyAccessAuthRequest$inboundSchema,
  ).optional(),
  actionAuth: z.array(
    EnvelopeRecipientCreateManyActionAuthRequest$inboundSchema,
  ).optional(),
});
/** @internal */
export type EnvelopeRecipientCreateManyDataRequest$Outbound = {
  email: string;
  name: string;
  role: string;
  signingOrder?: number | undefined;
  accessAuth?: Array<string> | undefined;
  actionAuth?: Array<string> | undefined;
};

/** @internal */
export const EnvelopeRecipientCreateManyDataRequest$outboundSchema: z.ZodType<
  EnvelopeRecipientCreateManyDataRequest$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientCreateManyDataRequest
> = z.object({
  email: z.string(),
  name: z.string(),
  role: EnvelopeRecipientCreateManyRoleRequest$outboundSchema,
  signingOrder: z.number().optional(),
  accessAuth: z.array(
    EnvelopeRecipientCreateManyAccessAuthRequest$outboundSchema,
  ).optional(),
  actionAuth: z.array(
    EnvelopeRecipientCreateManyActionAuthRequest$outboundSchema,
  ).optional(),
});

export function envelopeRecipientCreateManyDataRequestToJSON(
  envelopeRecipientCreateManyDataRequest:
    EnvelopeRecipientCreateManyDataRequest,
): string {
  return JSON.stringify(
    EnvelopeRecipientCreateManyDataRequest$outboundSchema.parse(
      envelopeRecipientCreateManyDataRequest,
    ),
  );
}
export function envelopeRecipientCreateManyDataRequestFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientCreateManyDataRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientCreateManyDataRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientCreateManyDataRequest' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientCreateManyRequest$inboundSchema: z.ZodType<
  EnvelopeRecipientCreateManyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  envelopeId: z.string(),
  data: z.array(
    z.lazy(() => EnvelopeRecipientCreateManyDataRequest$inboundSchema),
  ),
});
/** @internal */
export type EnvelopeRecipientCreateManyRequest$Outbound = {
  envelopeId: string;
  data: Array<EnvelopeRecipientCreateManyDataRequest$Outbound>;
};

/** @internal */
export const EnvelopeRecipientCreateManyRequest$outboundSchema: z.ZodType<
  EnvelopeRecipientCreateManyRequest$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientCreateManyRequest
> = z.object({
  envelopeId: z.string(),
  data: z.array(
    z.lazy(() => EnvelopeRecipientCreateManyDataRequest$outboundSchema),
  ),
});

export function envelopeRecipientCreateManyRequestToJSON(
  envelopeRecipientCreateManyRequest: EnvelopeRecipientCreateManyRequest,
): string {
  return JSON.stringify(
    EnvelopeRecipientCreateManyRequest$outboundSchema.parse(
      envelopeRecipientCreateManyRequest,
    ),
  );
}
export function envelopeRecipientCreateManyRequestFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientCreateManyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientCreateManyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientCreateManyRequest' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientCreateManyRoleResponse$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyRoleResponse> = z
    .nativeEnum(EnvelopeRecipientCreateManyRoleResponse);
/** @internal */
export const EnvelopeRecipientCreateManyRoleResponse$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyRoleResponse> =
    EnvelopeRecipientCreateManyRoleResponse$inboundSchema;

/** @internal */
export const EnvelopeRecipientCreateManyReadStatus$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyReadStatus> = z.nativeEnum(
    EnvelopeRecipientCreateManyReadStatus,
  );
/** @internal */
export const EnvelopeRecipientCreateManyReadStatus$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyReadStatus> =
    EnvelopeRecipientCreateManyReadStatus$inboundSchema;

/** @internal */
export const EnvelopeRecipientCreateManySigningStatus$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManySigningStatus> = z
    .nativeEnum(EnvelopeRecipientCreateManySigningStatus);
/** @internal */
export const EnvelopeRecipientCreateManySigningStatus$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManySigningStatus> =
    EnvelopeRecipientCreateManySigningStatus$inboundSchema;

/** @internal */
export const EnvelopeRecipientCreateManySendStatus$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManySendStatus> = z.nativeEnum(
    EnvelopeRecipientCreateManySendStatus,
  );
/** @internal */
export const EnvelopeRecipientCreateManySendStatus$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManySendStatus> =
    EnvelopeRecipientCreateManySendStatus$inboundSchema;

/** @internal */
export const EnvelopeRecipientCreateManyAccessAuthResponse$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyAccessAuthResponse> = z
    .nativeEnum(EnvelopeRecipientCreateManyAccessAuthResponse);
/** @internal */
export const EnvelopeRecipientCreateManyAccessAuthResponse$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyAccessAuthResponse> =
    EnvelopeRecipientCreateManyAccessAuthResponse$inboundSchema;

/** @internal */
export const EnvelopeRecipientCreateManyActionAuthResponse$inboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyActionAuthResponse> = z
    .nativeEnum(EnvelopeRecipientCreateManyActionAuthResponse);
/** @internal */
export const EnvelopeRecipientCreateManyActionAuthResponse$outboundSchema:
  z.ZodNativeEnum<typeof EnvelopeRecipientCreateManyActionAuthResponse> =
    EnvelopeRecipientCreateManyActionAuthResponse$inboundSchema;

/** @internal */
export const EnvelopeRecipientCreateManyAuthOptions$inboundSchema: z.ZodType<
  EnvelopeRecipientCreateManyAuthOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  accessAuth: z.array(
    EnvelopeRecipientCreateManyAccessAuthResponse$inboundSchema,
  ),
  actionAuth: z.array(
    EnvelopeRecipientCreateManyActionAuthResponse$inboundSchema,
  ),
});
/** @internal */
export type EnvelopeRecipientCreateManyAuthOptions$Outbound = {
  accessAuth: Array<string>;
  actionAuth: Array<string>;
};

/** @internal */
export const EnvelopeRecipientCreateManyAuthOptions$outboundSchema: z.ZodType<
  EnvelopeRecipientCreateManyAuthOptions$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientCreateManyAuthOptions
> = z.object({
  accessAuth: z.array(
    EnvelopeRecipientCreateManyAccessAuthResponse$outboundSchema,
  ),
  actionAuth: z.array(
    EnvelopeRecipientCreateManyActionAuthResponse$outboundSchema,
  ),
});

export function envelopeRecipientCreateManyAuthOptionsToJSON(
  envelopeRecipientCreateManyAuthOptions:
    EnvelopeRecipientCreateManyAuthOptions,
): string {
  return JSON.stringify(
    EnvelopeRecipientCreateManyAuthOptions$outboundSchema.parse(
      envelopeRecipientCreateManyAuthOptions,
    ),
  );
}
export function envelopeRecipientCreateManyAuthOptionsFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientCreateManyAuthOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientCreateManyAuthOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientCreateManyAuthOptions' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientCreateManyDataResponse$inboundSchema: z.ZodType<
  EnvelopeRecipientCreateManyDataResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  envelopeId: z.string(),
  role: EnvelopeRecipientCreateManyRoleResponse$inboundSchema,
  readStatus: EnvelopeRecipientCreateManyReadStatus$inboundSchema,
  signingStatus: EnvelopeRecipientCreateManySigningStatus$inboundSchema,
  sendStatus: EnvelopeRecipientCreateManySendStatus$inboundSchema,
  id: z.number(),
  email: z.string(),
  name: z.string(),
  token: z.string(),
  documentDeletedAt: z.nullable(z.string()),
  expired: z.nullable(z.string()),
  signedAt: z.nullable(z.string()),
  authOptions: z.nullable(
    z.lazy(() => EnvelopeRecipientCreateManyAuthOptions$inboundSchema),
  ),
  signingOrder: z.nullable(z.number()),
  rejectionReason: z.nullable(z.string()),
});
/** @internal */
export type EnvelopeRecipientCreateManyDataResponse$Outbound = {
  envelopeId: string;
  role: string;
  readStatus: string;
  signingStatus: string;
  sendStatus: string;
  id: number;
  email: string;
  name: string;
  token: string;
  documentDeletedAt: string | null;
  expired: string | null;
  signedAt: string | null;
  authOptions: EnvelopeRecipientCreateManyAuthOptions$Outbound | null;
  signingOrder: number | null;
  rejectionReason: string | null;
};

/** @internal */
export const EnvelopeRecipientCreateManyDataResponse$outboundSchema: z.ZodType<
  EnvelopeRecipientCreateManyDataResponse$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientCreateManyDataResponse
> = z.object({
  envelopeId: z.string(),
  role: EnvelopeRecipientCreateManyRoleResponse$outboundSchema,
  readStatus: EnvelopeRecipientCreateManyReadStatus$outboundSchema,
  signingStatus: EnvelopeRecipientCreateManySigningStatus$outboundSchema,
  sendStatus: EnvelopeRecipientCreateManySendStatus$outboundSchema,
  id: z.number(),
  email: z.string(),
  name: z.string(),
  token: z.string(),
  documentDeletedAt: z.nullable(z.string()),
  expired: z.nullable(z.string()),
  signedAt: z.nullable(z.string()),
  authOptions: z.nullable(
    z.lazy(() => EnvelopeRecipientCreateManyAuthOptions$outboundSchema),
  ),
  signingOrder: z.nullable(z.number()),
  rejectionReason: z.nullable(z.string()),
});

export function envelopeRecipientCreateManyDataResponseToJSON(
  envelopeRecipientCreateManyDataResponse:
    EnvelopeRecipientCreateManyDataResponse,
): string {
  return JSON.stringify(
    EnvelopeRecipientCreateManyDataResponse$outboundSchema.parse(
      envelopeRecipientCreateManyDataResponse,
    ),
  );
}
export function envelopeRecipientCreateManyDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  EnvelopeRecipientCreateManyDataResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientCreateManyDataResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'EnvelopeRecipientCreateManyDataResponse' from JSON`,
  );
}

/** @internal */
export const EnvelopeRecipientCreateManyResponse$inboundSchema: z.ZodType<
  EnvelopeRecipientCreateManyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(
    z.lazy(() => EnvelopeRecipientCreateManyDataResponse$inboundSchema),
  ),
});
/** @internal */
export type EnvelopeRecipientCreateManyResponse$Outbound = {
  data: Array<EnvelopeRecipientCreateManyDataResponse$Outbound>;
};

/** @internal */
export const EnvelopeRecipientCreateManyResponse$outboundSchema: z.ZodType<
  EnvelopeRecipientCreateManyResponse$Outbound,
  z.ZodTypeDef,
  EnvelopeRecipientCreateManyResponse
> = z.object({
  data: z.array(
    z.lazy(() => EnvelopeRecipientCreateManyDataResponse$outboundSchema),
  ),
});

export function envelopeRecipientCreateManyResponseToJSON(
  envelopeRecipientCreateManyResponse: EnvelopeRecipientCreateManyResponse,
): string {
  return JSON.stringify(
    EnvelopeRecipientCreateManyResponse$outboundSchema.parse(
      envelopeRecipientCreateManyResponse,
    ),
  );
}
export function envelopeRecipientCreateManyResponseFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeRecipientCreateManyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EnvelopeRecipientCreateManyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeRecipientCreateManyResponse' from JSON`,
  );
}
