/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Filter envelopes by type (DOCUMENT or TEMPLATE).
 */
export const EnvelopeFindQueryParamType = {
  Document: "DOCUMENT",
  Template: "TEMPLATE",
} as const;
/**
 * Filter envelopes by type (DOCUMENT or TEMPLATE).
 */
export type EnvelopeFindQueryParamType = ClosedEnum<
  typeof EnvelopeFindQueryParamType
>;

/**
 * Filter envelopes by how it was created.
 */
export const EnvelopeFindQueryParamSource = {
  Document: "DOCUMENT",
  Template: "TEMPLATE",
  TemplateDirectLink: "TEMPLATE_DIRECT_LINK",
} as const;
/**
 * Filter envelopes by how it was created.
 */
export type EnvelopeFindQueryParamSource = ClosedEnum<
  typeof EnvelopeFindQueryParamSource
>;

/**
 * Filter envelopes by the current status.
 */
export const EnvelopeFindQueryParamStatus = {
  Draft: "DRAFT",
  Pending: "PENDING",
  Completed: "COMPLETED",
  Rejected: "REJECTED",
} as const;
/**
 * Filter envelopes by the current status.
 */
export type EnvelopeFindQueryParamStatus = ClosedEnum<
  typeof EnvelopeFindQueryParamStatus
>;

export const EnvelopeFindOrderByColumn = {
  CreatedAt: "createdAt",
} as const;
export type EnvelopeFindOrderByColumn = ClosedEnum<
  typeof EnvelopeFindOrderByColumn
>;

/**
 * Sort direction.
 */
export const EnvelopeFindOrderByDirection = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort direction.
 */
export type EnvelopeFindOrderByDirection = ClosedEnum<
  typeof EnvelopeFindOrderByDirection
>;

export type EnvelopeFindRequest = {
  /**
   * The search query.
   */
  query?: string | undefined;
  /**
   * The pagination page number, starts at 1.
   */
  page?: number | undefined;
  /**
   * The number of items per page.
   */
  perPage?: number | undefined;
  /**
   * Filter envelopes by type (DOCUMENT or TEMPLATE).
   */
  type?: EnvelopeFindQueryParamType | undefined;
  /**
   * Filter envelopes by the template ID used to create it.
   */
  templateId?: number | undefined;
  /**
   * Filter envelopes by how it was created.
   */
  source?: EnvelopeFindQueryParamSource | undefined;
  /**
   * Filter envelopes by the current status.
   */
  status?: EnvelopeFindQueryParamStatus | undefined;
  /**
   * Filter envelopes by folder ID.
   */
  folderId?: string | undefined;
  orderByColumn?: EnvelopeFindOrderByColumn | undefined;
  /**
   * Sort direction.
   */
  orderByDirection?: EnvelopeFindOrderByDirection | undefined;
};

export const EnvelopeFindDataType = {
  Document: "DOCUMENT",
  Template: "TEMPLATE",
} as const;
export type EnvelopeFindDataType = ClosedEnum<typeof EnvelopeFindDataType>;

export const EnvelopeFindDataStatus = {
  Draft: "DRAFT",
  Pending: "PENDING",
  Completed: "COMPLETED",
  Rejected: "REJECTED",
} as const;
export type EnvelopeFindDataStatus = ClosedEnum<typeof EnvelopeFindDataStatus>;

export const EnvelopeFindDataSource = {
  Document: "DOCUMENT",
  Template: "TEMPLATE",
  TemplateDirectLink: "TEMPLATE_DIRECT_LINK",
} as const;
export type EnvelopeFindDataSource = ClosedEnum<typeof EnvelopeFindDataSource>;

export const EnvelopeFindVisibility = {
  Everyone: "EVERYONE",
  ManagerAndAbove: "MANAGER_AND_ABOVE",
  Admin: "ADMIN",
} as const;
export type EnvelopeFindVisibility = ClosedEnum<typeof EnvelopeFindVisibility>;

export const EnvelopeFindTemplateType = {
  Public: "PUBLIC",
  Private: "PRIVATE",
} as const;
export type EnvelopeFindTemplateType = ClosedEnum<
  typeof EnvelopeFindTemplateType
>;

export const EnvelopeFindGlobalAccessAuth = {
  Account: "ACCOUNT",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
} as const;
export type EnvelopeFindGlobalAccessAuth = ClosedEnum<
  typeof EnvelopeFindGlobalAccessAuth
>;

export const EnvelopeFindGlobalActionAuth = {
  Account: "ACCOUNT",
  Passkey: "PASSKEY",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
  Password: "PASSWORD",
} as const;
export type EnvelopeFindGlobalActionAuth = ClosedEnum<
  typeof EnvelopeFindGlobalActionAuth
>;

export type EnvelopeFindAuthOptions = {
  globalAccessAuth: Array<EnvelopeFindGlobalAccessAuth>;
  globalActionAuth: Array<EnvelopeFindGlobalActionAuth>;
};

export type EnvelopeFindFormValues = string | boolean | number;

export type EnvelopeFindUser = {
  id: number;
  name: string;
  email: string;
};

export const EnvelopeFindRole = {
  Cc: "CC",
  Signer: "SIGNER",
  Viewer: "VIEWER",
  Approver: "APPROVER",
  Assistant: "ASSISTANT",
} as const;
export type EnvelopeFindRole = ClosedEnum<typeof EnvelopeFindRole>;

export const EnvelopeFindReadStatus = {
  NotOpened: "NOT_OPENED",
  Opened: "OPENED",
} as const;
export type EnvelopeFindReadStatus = ClosedEnum<typeof EnvelopeFindReadStatus>;

export const EnvelopeFindSigningStatus = {
  NotSigned: "NOT_SIGNED",
  Signed: "SIGNED",
  Rejected: "REJECTED",
} as const;
export type EnvelopeFindSigningStatus = ClosedEnum<
  typeof EnvelopeFindSigningStatus
>;

export const EnvelopeFindSendStatus = {
  NotSent: "NOT_SENT",
  Sent: "SENT",
} as const;
export type EnvelopeFindSendStatus = ClosedEnum<typeof EnvelopeFindSendStatus>;

export const EnvelopeFindAccessAuth = {
  Account: "ACCOUNT",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
} as const;
export type EnvelopeFindAccessAuth = ClosedEnum<typeof EnvelopeFindAccessAuth>;

export const EnvelopeFindActionAuth = {
  Account: "ACCOUNT",
  Passkey: "PASSKEY",
  TwoFactorAuth: "TWO_FACTOR_AUTH",
  Password: "PASSWORD",
  ExplicitNone: "EXPLICIT_NONE",
} as const;
export type EnvelopeFindActionAuth = ClosedEnum<typeof EnvelopeFindActionAuth>;

export type EnvelopeFindRecipientAuthOptions = {
  accessAuth: Array<EnvelopeFindAccessAuth>;
  actionAuth: Array<EnvelopeFindActionAuth>;
};

export type EnvelopeFindRecipient = {
  envelopeId: string;
  role: EnvelopeFindRole;
  readStatus: EnvelopeFindReadStatus;
  signingStatus: EnvelopeFindSigningStatus;
  sendStatus: EnvelopeFindSendStatus;
  id: number;
  email: string;
  name: string;
  token: string;
  documentDeletedAt: string | null;
  expired: string | null;
  signedAt: string | null;
  authOptions: EnvelopeFindRecipientAuthOptions | null;
  signingOrder: number | null;
  rejectionReason: string | null;
};

export type EnvelopeFindTeam = {
  id: number;
  url: string;
};

export type EnvelopeFindData = {
  internalVersion: number;
  type: EnvelopeFindDataType;
  status: EnvelopeFindDataStatus;
  source: EnvelopeFindDataSource;
  visibility: EnvelopeFindVisibility;
  templateType: EnvelopeFindTemplateType;
  id: string;
  secondaryId: string;
  externalId: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
  deletedAt: string | null;
  title: string;
  authOptions: EnvelopeFindAuthOptions | null;
  formValues: { [k: string]: string | boolean | number } | null;
  publicTitle: string;
  publicDescription: string;
  userId: number;
  teamId: number;
  folderId: string | null;
  templateId: number | null;
  user: EnvelopeFindUser;
  recipients: Array<EnvelopeFindRecipient>;
  team: EnvelopeFindTeam | null;
};

/**
 * Successful response
 */
export type EnvelopeFindResponse = {
  data: Array<EnvelopeFindData>;
  count: number;
  currentPage: number;
  perPage: number;
  totalPages: number;
};

/** @internal */
export const EnvelopeFindQueryParamType$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindQueryParamType
> = z.nativeEnum(EnvelopeFindQueryParamType);
/** @internal */
export const EnvelopeFindQueryParamType$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindQueryParamType
> = EnvelopeFindQueryParamType$inboundSchema;

/** @internal */
export const EnvelopeFindQueryParamSource$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindQueryParamSource
> = z.nativeEnum(EnvelopeFindQueryParamSource);
/** @internal */
export const EnvelopeFindQueryParamSource$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindQueryParamSource
> = EnvelopeFindQueryParamSource$inboundSchema;

/** @internal */
export const EnvelopeFindQueryParamStatus$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindQueryParamStatus
> = z.nativeEnum(EnvelopeFindQueryParamStatus);
/** @internal */
export const EnvelopeFindQueryParamStatus$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindQueryParamStatus
> = EnvelopeFindQueryParamStatus$inboundSchema;

/** @internal */
export const EnvelopeFindOrderByColumn$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindOrderByColumn
> = z.nativeEnum(EnvelopeFindOrderByColumn);
/** @internal */
export const EnvelopeFindOrderByColumn$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindOrderByColumn
> = EnvelopeFindOrderByColumn$inboundSchema;

/** @internal */
export const EnvelopeFindOrderByDirection$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindOrderByDirection
> = z.nativeEnum(EnvelopeFindOrderByDirection);
/** @internal */
export const EnvelopeFindOrderByDirection$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindOrderByDirection
> = EnvelopeFindOrderByDirection$inboundSchema;

/** @internal */
export const EnvelopeFindRequest$inboundSchema: z.ZodType<
  EnvelopeFindRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  query: z.string().optional(),
  page: z.number().optional(),
  perPage: z.number().optional(),
  type: EnvelopeFindQueryParamType$inboundSchema.optional(),
  templateId: z.number().optional(),
  source: EnvelopeFindQueryParamSource$inboundSchema.optional(),
  status: EnvelopeFindQueryParamStatus$inboundSchema.optional(),
  folderId: z.string().optional(),
  orderByColumn: EnvelopeFindOrderByColumn$inboundSchema.optional(),
  orderByDirection: EnvelopeFindOrderByDirection$inboundSchema.default("desc"),
});
/** @internal */
export type EnvelopeFindRequest$Outbound = {
  query?: string | undefined;
  page?: number | undefined;
  perPage?: number | undefined;
  type?: string | undefined;
  templateId?: number | undefined;
  source?: string | undefined;
  status?: string | undefined;
  folderId?: string | undefined;
  orderByColumn?: string | undefined;
  orderByDirection: string;
};

/** @internal */
export const EnvelopeFindRequest$outboundSchema: z.ZodType<
  EnvelopeFindRequest$Outbound,
  z.ZodTypeDef,
  EnvelopeFindRequest
> = z.object({
  query: z.string().optional(),
  page: z.number().optional(),
  perPage: z.number().optional(),
  type: EnvelopeFindQueryParamType$outboundSchema.optional(),
  templateId: z.number().optional(),
  source: EnvelopeFindQueryParamSource$outboundSchema.optional(),
  status: EnvelopeFindQueryParamStatus$outboundSchema.optional(),
  folderId: z.string().optional(),
  orderByColumn: EnvelopeFindOrderByColumn$outboundSchema.optional(),
  orderByDirection: EnvelopeFindOrderByDirection$outboundSchema.default("desc"),
});

export function envelopeFindRequestToJSON(
  envelopeFindRequest: EnvelopeFindRequest,
): string {
  return JSON.stringify(
    EnvelopeFindRequest$outboundSchema.parse(envelopeFindRequest),
  );
}
export function envelopeFindRequestFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeFindRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeFindRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeFindRequest' from JSON`,
  );
}

/** @internal */
export const EnvelopeFindDataType$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindDataType
> = z.nativeEnum(EnvelopeFindDataType);
/** @internal */
export const EnvelopeFindDataType$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindDataType
> = EnvelopeFindDataType$inboundSchema;

/** @internal */
export const EnvelopeFindDataStatus$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindDataStatus
> = z.nativeEnum(EnvelopeFindDataStatus);
/** @internal */
export const EnvelopeFindDataStatus$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindDataStatus
> = EnvelopeFindDataStatus$inboundSchema;

/** @internal */
export const EnvelopeFindDataSource$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindDataSource
> = z.nativeEnum(EnvelopeFindDataSource);
/** @internal */
export const EnvelopeFindDataSource$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindDataSource
> = EnvelopeFindDataSource$inboundSchema;

/** @internal */
export const EnvelopeFindVisibility$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindVisibility
> = z.nativeEnum(EnvelopeFindVisibility);
/** @internal */
export const EnvelopeFindVisibility$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindVisibility
> = EnvelopeFindVisibility$inboundSchema;

/** @internal */
export const EnvelopeFindTemplateType$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindTemplateType
> = z.nativeEnum(EnvelopeFindTemplateType);
/** @internal */
export const EnvelopeFindTemplateType$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindTemplateType
> = EnvelopeFindTemplateType$inboundSchema;

/** @internal */
export const EnvelopeFindGlobalAccessAuth$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindGlobalAccessAuth
> = z.nativeEnum(EnvelopeFindGlobalAccessAuth);
/** @internal */
export const EnvelopeFindGlobalAccessAuth$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindGlobalAccessAuth
> = EnvelopeFindGlobalAccessAuth$inboundSchema;

/** @internal */
export const EnvelopeFindGlobalActionAuth$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindGlobalActionAuth
> = z.nativeEnum(EnvelopeFindGlobalActionAuth);
/** @internal */
export const EnvelopeFindGlobalActionAuth$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindGlobalActionAuth
> = EnvelopeFindGlobalActionAuth$inboundSchema;

/** @internal */
export const EnvelopeFindAuthOptions$inboundSchema: z.ZodType<
  EnvelopeFindAuthOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  globalAccessAuth: z.array(EnvelopeFindGlobalAccessAuth$inboundSchema),
  globalActionAuth: z.array(EnvelopeFindGlobalActionAuth$inboundSchema),
});
/** @internal */
export type EnvelopeFindAuthOptions$Outbound = {
  globalAccessAuth: Array<string>;
  globalActionAuth: Array<string>;
};

/** @internal */
export const EnvelopeFindAuthOptions$outboundSchema: z.ZodType<
  EnvelopeFindAuthOptions$Outbound,
  z.ZodTypeDef,
  EnvelopeFindAuthOptions
> = z.object({
  globalAccessAuth: z.array(EnvelopeFindGlobalAccessAuth$outboundSchema),
  globalActionAuth: z.array(EnvelopeFindGlobalActionAuth$outboundSchema),
});

export function envelopeFindAuthOptionsToJSON(
  envelopeFindAuthOptions: EnvelopeFindAuthOptions,
): string {
  return JSON.stringify(
    EnvelopeFindAuthOptions$outboundSchema.parse(envelopeFindAuthOptions),
  );
}
export function envelopeFindAuthOptionsFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeFindAuthOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeFindAuthOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeFindAuthOptions' from JSON`,
  );
}

/** @internal */
export const EnvelopeFindFormValues$inboundSchema: z.ZodType<
  EnvelopeFindFormValues,
  z.ZodTypeDef,
  unknown
> = z.union([z.string(), z.boolean(), z.number()]);
/** @internal */
export type EnvelopeFindFormValues$Outbound = string | boolean | number;

/** @internal */
export const EnvelopeFindFormValues$outboundSchema: z.ZodType<
  EnvelopeFindFormValues$Outbound,
  z.ZodTypeDef,
  EnvelopeFindFormValues
> = z.union([z.string(), z.boolean(), z.number()]);

export function envelopeFindFormValuesToJSON(
  envelopeFindFormValues: EnvelopeFindFormValues,
): string {
  return JSON.stringify(
    EnvelopeFindFormValues$outboundSchema.parse(envelopeFindFormValues),
  );
}
export function envelopeFindFormValuesFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeFindFormValues, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeFindFormValues$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeFindFormValues' from JSON`,
  );
}

/** @internal */
export const EnvelopeFindUser$inboundSchema: z.ZodType<
  EnvelopeFindUser,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number(),
  name: z.string(),
  email: z.string(),
});
/** @internal */
export type EnvelopeFindUser$Outbound = {
  id: number;
  name: string;
  email: string;
};

/** @internal */
export const EnvelopeFindUser$outboundSchema: z.ZodType<
  EnvelopeFindUser$Outbound,
  z.ZodTypeDef,
  EnvelopeFindUser
> = z.object({
  id: z.number(),
  name: z.string(),
  email: z.string(),
});

export function envelopeFindUserToJSON(
  envelopeFindUser: EnvelopeFindUser,
): string {
  return JSON.stringify(
    EnvelopeFindUser$outboundSchema.parse(envelopeFindUser),
  );
}
export function envelopeFindUserFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeFindUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeFindUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeFindUser' from JSON`,
  );
}

/** @internal */
export const EnvelopeFindRole$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindRole
> = z.nativeEnum(EnvelopeFindRole);
/** @internal */
export const EnvelopeFindRole$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindRole
> = EnvelopeFindRole$inboundSchema;

/** @internal */
export const EnvelopeFindReadStatus$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindReadStatus
> = z.nativeEnum(EnvelopeFindReadStatus);
/** @internal */
export const EnvelopeFindReadStatus$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindReadStatus
> = EnvelopeFindReadStatus$inboundSchema;

/** @internal */
export const EnvelopeFindSigningStatus$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindSigningStatus
> = z.nativeEnum(EnvelopeFindSigningStatus);
/** @internal */
export const EnvelopeFindSigningStatus$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindSigningStatus
> = EnvelopeFindSigningStatus$inboundSchema;

/** @internal */
export const EnvelopeFindSendStatus$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindSendStatus
> = z.nativeEnum(EnvelopeFindSendStatus);
/** @internal */
export const EnvelopeFindSendStatus$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindSendStatus
> = EnvelopeFindSendStatus$inboundSchema;

/** @internal */
export const EnvelopeFindAccessAuth$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindAccessAuth
> = z.nativeEnum(EnvelopeFindAccessAuth);
/** @internal */
export const EnvelopeFindAccessAuth$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindAccessAuth
> = EnvelopeFindAccessAuth$inboundSchema;

/** @internal */
export const EnvelopeFindActionAuth$inboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindActionAuth
> = z.nativeEnum(EnvelopeFindActionAuth);
/** @internal */
export const EnvelopeFindActionAuth$outboundSchema: z.ZodNativeEnum<
  typeof EnvelopeFindActionAuth
> = EnvelopeFindActionAuth$inboundSchema;

/** @internal */
export const EnvelopeFindRecipientAuthOptions$inboundSchema: z.ZodType<
  EnvelopeFindRecipientAuthOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  accessAuth: z.array(EnvelopeFindAccessAuth$inboundSchema),
  actionAuth: z.array(EnvelopeFindActionAuth$inboundSchema),
});
/** @internal */
export type EnvelopeFindRecipientAuthOptions$Outbound = {
  accessAuth: Array<string>;
  actionAuth: Array<string>;
};

/** @internal */
export const EnvelopeFindRecipientAuthOptions$outboundSchema: z.ZodType<
  EnvelopeFindRecipientAuthOptions$Outbound,
  z.ZodTypeDef,
  EnvelopeFindRecipientAuthOptions
> = z.object({
  accessAuth: z.array(EnvelopeFindAccessAuth$outboundSchema),
  actionAuth: z.array(EnvelopeFindActionAuth$outboundSchema),
});

export function envelopeFindRecipientAuthOptionsToJSON(
  envelopeFindRecipientAuthOptions: EnvelopeFindRecipientAuthOptions,
): string {
  return JSON.stringify(
    EnvelopeFindRecipientAuthOptions$outboundSchema.parse(
      envelopeFindRecipientAuthOptions,
    ),
  );
}
export function envelopeFindRecipientAuthOptionsFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeFindRecipientAuthOptions, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeFindRecipientAuthOptions$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeFindRecipientAuthOptions' from JSON`,
  );
}

/** @internal */
export const EnvelopeFindRecipient$inboundSchema: z.ZodType<
  EnvelopeFindRecipient,
  z.ZodTypeDef,
  unknown
> = z.object({
  envelopeId: z.string(),
  role: EnvelopeFindRole$inboundSchema,
  readStatus: EnvelopeFindReadStatus$inboundSchema,
  signingStatus: EnvelopeFindSigningStatus$inboundSchema,
  sendStatus: EnvelopeFindSendStatus$inboundSchema,
  id: z.number(),
  email: z.string(),
  name: z.string(),
  token: z.string(),
  documentDeletedAt: z.nullable(z.string()),
  expired: z.nullable(z.string()),
  signedAt: z.nullable(z.string()),
  authOptions: z.nullable(
    z.lazy(() => EnvelopeFindRecipientAuthOptions$inboundSchema),
  ),
  signingOrder: z.nullable(z.number()),
  rejectionReason: z.nullable(z.string()),
});
/** @internal */
export type EnvelopeFindRecipient$Outbound = {
  envelopeId: string;
  role: string;
  readStatus: string;
  signingStatus: string;
  sendStatus: string;
  id: number;
  email: string;
  name: string;
  token: string;
  documentDeletedAt: string | null;
  expired: string | null;
  signedAt: string | null;
  authOptions: EnvelopeFindRecipientAuthOptions$Outbound | null;
  signingOrder: number | null;
  rejectionReason: string | null;
};

/** @internal */
export const EnvelopeFindRecipient$outboundSchema: z.ZodType<
  EnvelopeFindRecipient$Outbound,
  z.ZodTypeDef,
  EnvelopeFindRecipient
> = z.object({
  envelopeId: z.string(),
  role: EnvelopeFindRole$outboundSchema,
  readStatus: EnvelopeFindReadStatus$outboundSchema,
  signingStatus: EnvelopeFindSigningStatus$outboundSchema,
  sendStatus: EnvelopeFindSendStatus$outboundSchema,
  id: z.number(),
  email: z.string(),
  name: z.string(),
  token: z.string(),
  documentDeletedAt: z.nullable(z.string()),
  expired: z.nullable(z.string()),
  signedAt: z.nullable(z.string()),
  authOptions: z.nullable(
    z.lazy(() => EnvelopeFindRecipientAuthOptions$outboundSchema),
  ),
  signingOrder: z.nullable(z.number()),
  rejectionReason: z.nullable(z.string()),
});

export function envelopeFindRecipientToJSON(
  envelopeFindRecipient: EnvelopeFindRecipient,
): string {
  return JSON.stringify(
    EnvelopeFindRecipient$outboundSchema.parse(envelopeFindRecipient),
  );
}
export function envelopeFindRecipientFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeFindRecipient, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeFindRecipient$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeFindRecipient' from JSON`,
  );
}

/** @internal */
export const EnvelopeFindTeam$inboundSchema: z.ZodType<
  EnvelopeFindTeam,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number(),
  url: z.string(),
});
/** @internal */
export type EnvelopeFindTeam$Outbound = {
  id: number;
  url: string;
};

/** @internal */
export const EnvelopeFindTeam$outboundSchema: z.ZodType<
  EnvelopeFindTeam$Outbound,
  z.ZodTypeDef,
  EnvelopeFindTeam
> = z.object({
  id: z.number(),
  url: z.string(),
});

export function envelopeFindTeamToJSON(
  envelopeFindTeam: EnvelopeFindTeam,
): string {
  return JSON.stringify(
    EnvelopeFindTeam$outboundSchema.parse(envelopeFindTeam),
  );
}
export function envelopeFindTeamFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeFindTeam, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeFindTeam$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeFindTeam' from JSON`,
  );
}

/** @internal */
export const EnvelopeFindData$inboundSchema: z.ZodType<
  EnvelopeFindData,
  z.ZodTypeDef,
  unknown
> = z.object({
  internalVersion: z.number(),
  type: EnvelopeFindDataType$inboundSchema,
  status: EnvelopeFindDataStatus$inboundSchema,
  source: EnvelopeFindDataSource$inboundSchema,
  visibility: EnvelopeFindVisibility$inboundSchema,
  templateType: EnvelopeFindTemplateType$inboundSchema,
  id: z.string(),
  secondaryId: z.string(),
  externalId: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  completedAt: z.nullable(z.string()),
  deletedAt: z.nullable(z.string()),
  title: z.string(),
  authOptions: z.nullable(z.lazy(() => EnvelopeFindAuthOptions$inboundSchema)),
  formValues: z.nullable(
    z.record(z.union([z.string(), z.boolean(), z.number()])),
  ),
  publicTitle: z.string(),
  publicDescription: z.string(),
  userId: z.number(),
  teamId: z.number(),
  folderId: z.nullable(z.string()),
  templateId: z.nullable(z.number()),
  user: z.lazy(() => EnvelopeFindUser$inboundSchema),
  recipients: z.array(z.lazy(() => EnvelopeFindRecipient$inboundSchema)),
  team: z.nullable(z.lazy(() => EnvelopeFindTeam$inboundSchema)),
});
/** @internal */
export type EnvelopeFindData$Outbound = {
  internalVersion: number;
  type: string;
  status: string;
  source: string;
  visibility: string;
  templateType: string;
  id: string;
  secondaryId: string;
  externalId: string | null;
  createdAt: string;
  updatedAt: string;
  completedAt: string | null;
  deletedAt: string | null;
  title: string;
  authOptions: EnvelopeFindAuthOptions$Outbound | null;
  formValues: { [k: string]: string | boolean | number } | null;
  publicTitle: string;
  publicDescription: string;
  userId: number;
  teamId: number;
  folderId: string | null;
  templateId: number | null;
  user: EnvelopeFindUser$Outbound;
  recipients: Array<EnvelopeFindRecipient$Outbound>;
  team: EnvelopeFindTeam$Outbound | null;
};

/** @internal */
export const EnvelopeFindData$outboundSchema: z.ZodType<
  EnvelopeFindData$Outbound,
  z.ZodTypeDef,
  EnvelopeFindData
> = z.object({
  internalVersion: z.number(),
  type: EnvelopeFindDataType$outboundSchema,
  status: EnvelopeFindDataStatus$outboundSchema,
  source: EnvelopeFindDataSource$outboundSchema,
  visibility: EnvelopeFindVisibility$outboundSchema,
  templateType: EnvelopeFindTemplateType$outboundSchema,
  id: z.string(),
  secondaryId: z.string(),
  externalId: z.nullable(z.string()),
  createdAt: z.string(),
  updatedAt: z.string(),
  completedAt: z.nullable(z.string()),
  deletedAt: z.nullable(z.string()),
  title: z.string(),
  authOptions: z.nullable(z.lazy(() => EnvelopeFindAuthOptions$outboundSchema)),
  formValues: z.nullable(
    z.record(z.union([z.string(), z.boolean(), z.number()])),
  ),
  publicTitle: z.string(),
  publicDescription: z.string(),
  userId: z.number(),
  teamId: z.number(),
  folderId: z.nullable(z.string()),
  templateId: z.nullable(z.number()),
  user: z.lazy(() => EnvelopeFindUser$outboundSchema),
  recipients: z.array(z.lazy(() => EnvelopeFindRecipient$outboundSchema)),
  team: z.nullable(z.lazy(() => EnvelopeFindTeam$outboundSchema)),
});

export function envelopeFindDataToJSON(
  envelopeFindData: EnvelopeFindData,
): string {
  return JSON.stringify(
    EnvelopeFindData$outboundSchema.parse(envelopeFindData),
  );
}
export function envelopeFindDataFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeFindData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeFindData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeFindData' from JSON`,
  );
}

/** @internal */
export const EnvelopeFindResponse$inboundSchema: z.ZodType<
  EnvelopeFindResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(z.lazy(() => EnvelopeFindData$inboundSchema)),
  count: z.number(),
  currentPage: z.number(),
  perPage: z.number(),
  totalPages: z.number(),
});
/** @internal */
export type EnvelopeFindResponse$Outbound = {
  data: Array<EnvelopeFindData$Outbound>;
  count: number;
  currentPage: number;
  perPage: number;
  totalPages: number;
};

/** @internal */
export const EnvelopeFindResponse$outboundSchema: z.ZodType<
  EnvelopeFindResponse$Outbound,
  z.ZodTypeDef,
  EnvelopeFindResponse
> = z.object({
  data: z.array(z.lazy(() => EnvelopeFindData$outboundSchema)),
  count: z.number(),
  currentPage: z.number(),
  perPage: z.number(),
  totalPages: z.number(),
});

export function envelopeFindResponseToJSON(
  envelopeFindResponse: EnvelopeFindResponse,
): string {
  return JSON.stringify(
    EnvelopeFindResponse$outboundSchema.parse(envelopeFindResponse),
  );
}
export function envelopeFindResponseFromJSON(
  jsonString: string,
): SafeParseResult<EnvelopeFindResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvelopeFindResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvelopeFindResponse' from JSON`,
  );
}
