// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmountUnit } from "./CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmountUnit.js";

export const CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmount: core.serialization.ObjectSchema<
    serializers.CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmount.Raw,
    Documenso.CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmount
> = core.serialization.object({
    unit: CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmountUnit,
    amount: core.serialization.number(),
});

export declare namespace CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmount {
    export interface Raw {
        unit: CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmountUnit.Raw;
        amount: number;
    }
}
