// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmount } from "./CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmount.js";
import { CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodDisabled } from "./CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodDisabled.js";

export const CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriod: core.serialization.Schema<
    serializers.CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriod.Raw,
    Documenso.CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriod
> = core.serialization.undiscriminatedUnion([
    CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmount,
    CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodDisabled,
]);

export declare namespace CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriod {
    export type Raw =
        | CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodAmount.Raw
        | CreateEnvelopesRequestPayloadMetaEnvelopeExpirationPeriodDisabled.Raw;
}
