// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const UpdateEnvelopesRequestMetaReminderSettingsSendAfterAmountUnit: core.serialization.Schema<
    serializers.UpdateEnvelopesRequestMetaReminderSettingsSendAfterAmountUnit.Raw,
    Documenso.UpdateEnvelopesRequestMetaReminderSettingsSendAfterAmountUnit
> = core.serialization.enum_(["day", "week", "month"]);

export declare namespace UpdateEnvelopesRequestMetaReminderSettingsSendAfterAmountUnit {
    export type Raw = "day" | "week" | "month";
}
