// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const CreateManyFieldsResponseDataItemFieldMetaInitialsTextAlign: core.serialization.Schema<
    serializers.envelopes.CreateManyFieldsResponseDataItemFieldMetaInitialsTextAlign.Raw,
    Documenso.envelopes.CreateManyFieldsResponseDataItemFieldMetaInitialsTextAlign
> = core.serialization.enum_(["left", "center", "right"]);

export declare namespace CreateManyFieldsResponseDataItemFieldMetaInitialsTextAlign {
    export type Raw = "left" | "center" | "right";
}
