// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const GetFieldsResponseFieldMetaNameOverflow: core.serialization.Schema<
    serializers.envelopes.GetFieldsResponseFieldMetaNameOverflow.Raw,
    Documenso.envelopes.GetFieldsResponseFieldMetaNameOverflow
> = core.serialization.enum_(["auto", "horizontal", "vertical", "crop"]);

export declare namespace GetFieldsResponseFieldMetaNameOverflow {
    export type Raw = "auto" | "horizontal" | "vertical" | "crop";
}
