// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const UpdateManyFieldsResponseDataItemFieldMetaInitialsTextAlign: core.serialization.Schema<
    serializers.envelopes.UpdateManyFieldsResponseDataItemFieldMetaInitialsTextAlign.Raw,
    Documenso.envelopes.UpdateManyFieldsResponseDataItemFieldMetaInitialsTextAlign
> = core.serialization.enum_(["left", "center", "right"]);

export declare namespace UpdateManyFieldsResponseDataItemFieldMetaInitialsTextAlign {
    export type Raw = "left" | "center" | "right";
}
