// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";
import { UpdateManyFieldsRequestDataItemFieldMetaOverflow } from "./UpdateManyFieldsRequestDataItemFieldMetaOverflow.js";

export const UpdateManyFieldsRequestDataItemFieldMeta: core.serialization.ObjectSchema<
    serializers.envelopes.UpdateManyFieldsRequestDataItemFieldMeta.Raw,
    Documenso.envelopes.UpdateManyFieldsRequestDataItemFieldMeta
> = core.serialization.object({
    label: core.serialization.string().optional(),
    placeholder: core.serialization.string().optional(),
    required: core.serialization.boolean().optional(),
    readOnly: core.serialization.boolean().optional(),
    fontSize: core.serialization.number().optional(),
    overflow: UpdateManyFieldsRequestDataItemFieldMetaOverflow.optional(),
    type: core.serialization.stringLiteral("signature"),
});

export declare namespace UpdateManyFieldsRequestDataItemFieldMeta {
    export interface Raw {
        label?: string | null;
        placeholder?: string | null;
        required?: boolean | null;
        readOnly?: boolean | null;
        fontSize?: number | null;
        overflow?: UpdateManyFieldsRequestDataItemFieldMetaOverflow.Raw | null;
        type: "signature";
    }
}
