// This file was auto-generated by Fern from our API Definition.

export const CreateManyFieldsRequestDataItemOneFieldMetaOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type CreateManyFieldsRequestDataItemOneFieldMetaOverflow =
    (typeof CreateManyFieldsRequestDataItemOneFieldMetaOverflow)[keyof typeof CreateManyFieldsRequestDataItemOneFieldMetaOverflow];
