// This file was auto-generated by Fern from our API Definition.

export const CreateManyFieldsResponseDataItemFieldMetaInitialsTextAlign = {
    Left: "left",
    Center: "center",
    Right: "right",
} as const;
export type CreateManyFieldsResponseDataItemFieldMetaInitialsTextAlign =
    (typeof CreateManyFieldsResponseDataItemFieldMetaInitialsTextAlign)[keyof typeof CreateManyFieldsResponseDataItemFieldMetaInitialsTextAlign];
