// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const TemplateCreateTemplateTemporaryTemplateRequestAttachmentsItem: core.serialization.ObjectSchema<
    serializers.TemplateCreateTemplateTemporaryTemplateRequestAttachmentsItem.Raw,
    Documenso.TemplateCreateTemplateTemporaryTemplateRequestAttachmentsItem
> = core.serialization.object({
    label: core.serialization.string(),
    data: core.serialization.string(),
    type: core.serialization.stringLiteral("link").optional(),
});

export declare namespace TemplateCreateTemplateTemporaryTemplateRequestAttachmentsItem {
    export interface Raw {
        label: string;
        data: string;
        type?: "link" | null;
    }
}
