// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const TemplateCreateTemplateTemporaryTemplateResponseTemplateRecipientsItemRole: core.serialization.Schema<
    serializers.TemplateCreateTemplateTemporaryTemplateResponseTemplateRecipientsItemRole.Raw,
    Documenso.TemplateCreateTemplateTemporaryTemplateResponseTemplateRecipientsItemRole
> = core.serialization.enum_(["CC", "SIGNER", "VIEWER", "APPROVER", "ASSISTANT"]);

export declare namespace TemplateCreateTemplateTemporaryTemplateResponseTemplateRecipientsItemRole {
    export type Raw = "CC" | "SIGNER" | "VIEWER" | "APPROVER" | "ASSISTANT";
}
