// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const TemplateCreateTemplateTemporaryTemplateResponseTemplateAuthOptionsGlobalAccessAuthItem: core.serialization.Schema<
    serializers.TemplateCreateTemplateTemporaryTemplateResponseTemplateAuthOptionsGlobalAccessAuthItem.Raw,
    Documenso.TemplateCreateTemplateTemporaryTemplateResponseTemplateAuthOptionsGlobalAccessAuthItem
> = core.serialization.enum_(["ACCOUNT", "TWO_FACTOR_AUTH"]);

export declare namespace TemplateCreateTemplateTemporaryTemplateResponseTemplateAuthOptionsGlobalAccessAuthItem {
    export type Raw = "ACCOUNT" | "TWO_FACTOR_AUTH";
}
