// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaTextTextAlign: core.serialization.Schema<
    serializers.TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaTextTextAlign.Raw,
    Documenso.TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaTextTextAlign
> = core.serialization.enum_(["left", "center", "right"]);

export declare namespace TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaTextTextAlign {
    export type Raw = "left" | "center" | "right";
}
