// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxDirection } from "./TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxDirection.js";
import { TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxOverflow } from "./TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxOverflow.js";
import { TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxValuesItem } from "./TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxValuesItem.js";

export const TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckbox: core.serialization.ObjectSchema<
    serializers.TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckbox.Raw,
    Documenso.TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckbox
> = core.serialization.object({
    label: core.serialization.string().optional(),
    placeholder: core.serialization.string().optional(),
    required: core.serialization.boolean().optional(),
    readOnly: core.serialization.boolean().optional(),
    fontSize: core.serialization.number().optional(),
    overflow: TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxOverflow.optional(),
    values: core.serialization
        .list(TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxValuesItem)
        .optional(),
    validationRule: core.serialization.string().optional(),
    validationLength: core.serialization.number().optional(),
    direction: TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxDirection,
});

export declare namespace TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckbox {
    export interface Raw {
        label?: string | null;
        placeholder?: string | null;
        required?: boolean | null;
        readOnly?: boolean | null;
        fontSize?: number | null;
        overflow?: TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxOverflow.Raw | null;
        values?:
            | TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxValuesItem.Raw[]
            | null;
        validationRule?: string | null;
        validationLength?: number | null;
        direction: TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaCheckboxDirection.Raw;
    }
}
