// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";
import { TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmailOverflow } from "./TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmailOverflow.js";
import { TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmailTextAlign } from "./TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmailTextAlign.js";

export const TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmail: core.serialization.ObjectSchema<
    serializers.TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmail.Raw,
    Documenso.TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmail
> = core.serialization.object({
    label: core.serialization.string().optional(),
    placeholder: core.serialization.string().optional(),
    required: core.serialization.boolean().optional(),
    readOnly: core.serialization.boolean().optional(),
    fontSize: core.serialization.number().optional(),
    overflow: TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmailOverflow,
    textAlign: TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmailTextAlign.optional(),
});

export declare namespace TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmail {
    export interface Raw {
        label?: string | null;
        placeholder?: string | null;
        required?: boolean | null;
        readOnly?: boolean | null;
        fontSize?: number | null;
        overflow: TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmailOverflow.Raw;
        textAlign?: TemplateCreateTemplateTemporaryTemplateResponseTemplateFieldsItemFieldMetaEmailTextAlign.Raw | null;
    }
}
