// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../index.js";

export interface UpdateRecipientsResponseAuthOptions {
    accessAuth: Documenso.documents.UpdateRecipientsResponseAuthOptionsAccessAuthItem[];
    actionAuth: Documenso.documents.UpdateRecipientsResponseAuthOptionsActionAuthItem[];
}
