// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../index.js";

export interface UpdateRecipientsResponseFieldsItemFieldMetaInitials {
    label?: string;
    placeholder?: string;
    required?: boolean;
    readOnly?: boolean;
    fontSize?: number;
    overflow?: Documenso.documents.UpdateRecipientsResponseFieldsItemFieldMetaInitialsOverflow;
    textAlign?: Documenso.documents.UpdateRecipientsResponseFieldsItemFieldMetaInitialsTextAlign;
}
