// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import * as serializers from "../../../index.js";

export const DocumentGetManyDocumentResponseDataItemAuthOptionsGlobalActionAuthItem: core.serialization.Schema<
    serializers.DocumentGetManyDocumentResponseDataItemAuthOptionsGlobalActionAuthItem.Raw,
    Documenso.DocumentGetManyDocumentResponseDataItemAuthOptionsGlobalActionAuthItem
> = core.serialization.enum_(["ACCOUNT", "PASSKEY", "TWO_FACTOR_AUTH", "PASSWORD"]);

export declare namespace DocumentGetManyDocumentResponseDataItemAuthOptionsGlobalActionAuthItem {
    export type Raw = "ACCOUNT" | "PASSKEY" | "TWO_FACTOR_AUTH" | "PASSWORD";
}
