// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const CreateManyRecipientsRequestDataItemAccessAuthItem: core.serialization.Schema<
    serializers.envelopes.CreateManyRecipientsRequestDataItemAccessAuthItem.Raw,
    Documenso.envelopes.CreateManyRecipientsRequestDataItemAccessAuthItem
> = core.serialization.enum_(["ACCOUNT", "TWO_FACTOR_AUTH"]);

export declare namespace CreateManyRecipientsRequestDataItemAccessAuthItem {
    export type Raw = "ACCOUNT" | "TWO_FACTOR_AUTH";
}
