// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";
import { UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaNameOverflow } from "./UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaNameOverflow.js";
import { UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaNameTextAlign } from "./UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaNameTextAlign.js";

export const UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaName: core.serialization.ObjectSchema<
    serializers.documents.UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaName.Raw,
    Documenso.documents.UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaName
> = core.serialization.object({
    label: core.serialization.string().optional(),
    placeholder: core.serialization.string().optional(),
    required: core.serialization.boolean().optional(),
    readOnly: core.serialization.boolean().optional(),
    fontSize: core.serialization.number().optional(),
    overflow: UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaNameOverflow.optional(),
    textAlign: UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaNameTextAlign.optional(),
});

export declare namespace UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaName {
    export interface Raw {
        label?: string | null;
        placeholder?: string | null;
        required?: boolean | null;
        readOnly?: boolean | null;
        fontSize?: number | null;
        overflow?: UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaNameOverflow.Raw | null;
        textAlign?: UpdateManyRecipientsResponseRecipientsItemFieldsItemFieldMetaNameTextAlign.Raw | null;
    }
}
