// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";

export const UpdateRecipientsResponseFieldsItemFieldMetaDropdownValuesItem: core.serialization.ObjectSchema<
    serializers.documents.UpdateRecipientsResponseFieldsItemFieldMetaDropdownValuesItem.Raw,
    Documenso.documents.UpdateRecipientsResponseFieldsItemFieldMetaDropdownValuesItem
> = core.serialization.object({
    value: core.serialization.string(),
});

export declare namespace UpdateRecipientsResponseFieldsItemFieldMetaDropdownValuesItem {
    export interface Raw {
        value: string;
    }
}
