// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import * as serializers from "../../../../../index.js";
import { UpdateManyRecipientsResponseRecipientsItemAuthOptionsAccessAuthItem } from "./UpdateManyRecipientsResponseRecipientsItemAuthOptionsAccessAuthItem.js";
import { UpdateManyRecipientsResponseRecipientsItemAuthOptionsActionAuthItem } from "./UpdateManyRecipientsResponseRecipientsItemAuthOptionsActionAuthItem.js";

export const UpdateManyRecipientsResponseRecipientsItemAuthOptions: core.serialization.ObjectSchema<
    serializers.documents.UpdateManyRecipientsResponseRecipientsItemAuthOptions.Raw,
    Documenso.documents.UpdateManyRecipientsResponseRecipientsItemAuthOptions
> = core.serialization.object({
    accessAuth: core.serialization.list(UpdateManyRecipientsResponseRecipientsItemAuthOptionsAccessAuthItem),
    actionAuth: core.serialization.list(UpdateManyRecipientsResponseRecipientsItemAuthOptionsActionAuthItem),
});

export declare namespace UpdateManyRecipientsResponseRecipientsItemAuthOptions {
    export interface Raw {
        accessAuth: UpdateManyRecipientsResponseRecipientsItemAuthOptionsAccessAuthItem.Raw[];
        actionAuth: UpdateManyRecipientsResponseRecipientsItemAuthOptionsActionAuthItem.Raw[];
    }
}
