// This file was auto-generated by Fern from our API Definition.

/** The type of authentication required for the recipient to access the document. */
export const CreateEnvelopesRequestPayloadRecipientsItemAccessAuthItem = {
    Account: "ACCOUNT",
    TwoFactorAuth: "TWO_FACTOR_AUTH",
} as const;
export type CreateEnvelopesRequestPayloadRecipientsItemAccessAuthItem =
    (typeof CreateEnvelopesRequestPayloadRecipientsItemAccessAuthItem)[keyof typeof CreateEnvelopesRequestPayloadRecipientsItemAccessAuthItem];
