// This file was auto-generated by Fern from our API Definition.

export const GetEnvelopesResponseFieldsItemFieldMetaNumberTextAlign = {
    Left: "left",
    Center: "center",
    Right: "right",
} as const;
export type GetEnvelopesResponseFieldsItemFieldMetaNumberTextAlign =
    (typeof GetEnvelopesResponseFieldsItemFieldMetaNumberTextAlign)[keyof typeof GetEnvelopesResponseFieldsItemFieldMetaNumberTextAlign];
