// This file was auto-generated by Fern from our API Definition.

export const GetEnvelopesResponseFieldsItemFieldMetaNameTextAlign = {
    Left: "left",
    Center: "center",
    Right: "right",
} as const;
export type GetEnvelopesResponseFieldsItemFieldMetaNameTextAlign =
    (typeof GetEnvelopesResponseFieldsItemFieldMetaNameTextAlign)[keyof typeof GetEnvelopesResponseFieldsItemFieldMetaNameTextAlign];
