// This file was auto-generated by Fern from our API Definition.

export const GetEnvelopesResponseFieldsItemFieldMetaCheckboxOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type GetEnvelopesResponseFieldsItemFieldMetaCheckboxOverflow =
    (typeof GetEnvelopesResponseFieldsItemFieldMetaCheckboxOverflow)[keyof typeof GetEnvelopesResponseFieldsItemFieldMetaCheckboxOverflow];
