// This file was auto-generated by Fern from our API Definition.

export const UpdateEnvelopesResponseStatus = {
    Draft: "DRAFT",
    Pending: "PENDING",
    Completed: "COMPLETED",
    Rejected: "REJECTED",
    Cancelled: "CANCELLED",
} as const;
export type UpdateEnvelopesResponseStatus =
    (typeof UpdateEnvelopesResponseStatus)[keyof typeof UpdateEnvelopesResponseStatus];
