// This file was auto-generated by Fern from our API Definition.

/** The distribution method to use when sending the document to the recipients. */
export const UseEnvelopesRequestPayloadOverrideDistributionMethod = {
    Email: "EMAIL",
    None: "NONE",
} as const;
export type UseEnvelopesRequestPayloadOverrideDistributionMethod =
    (typeof UseEnvelopesRequestPayloadOverrideDistributionMethod)[keyof typeof UseEnvelopesRequestPayloadOverrideDistributionMethod];
