// This file was auto-generated by Fern from our API Definition.

export const CreateFieldsResponseFieldMetaCheckboxOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type CreateFieldsResponseFieldMetaCheckboxOverflow =
    (typeof CreateFieldsResponseFieldMetaCheckboxOverflow)[keyof typeof CreateFieldsResponseFieldMetaCheckboxOverflow];
