// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../index.js";

export interface CreateFieldsResponseFieldMetaText {
    label?: string;
    placeholder?: string;
    required?: boolean;
    readOnly?: boolean;
    fontSize?: number;
    overflow?: Documenso.documents.CreateFieldsResponseFieldMetaTextOverflow;
    text?: string;
    characterLimit?: number;
    textAlign?: Documenso.documents.CreateFieldsResponseFieldMetaTextTextAlign;
    /** The line height of the text */
    lineHeight?: number | null;
    /** The spacing between each character */
    letterSpacing?: number | null;
    /** The vertical alignment of the text */
    verticalAlign?: Documenso.documents.CreateFieldsResponseFieldMetaTextVerticalAlign | null;
}
