// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../index.js";

export interface GetFieldsResponseFieldMetaRadio {
    label?: string;
    placeholder?: string;
    required?: boolean;
    readOnly?: boolean;
    fontSize?: number;
    overflow?: Documenso.documents.GetFieldsResponseFieldMetaRadioOverflow;
    values?: Documenso.documents.GetFieldsResponseFieldMetaRadioValuesItem[];
    direction: Documenso.documents.GetFieldsResponseFieldMetaRadioDirection;
}
