// This file was auto-generated by Fern from our API Definition.

export const GetFieldsResponseFieldMetaSignatureOverflow = {
    Auto: "auto",
    Horizontal: "horizontal",
    Vertical: "vertical",
    Crop: "crop",
} as const;
export type GetFieldsResponseFieldMetaSignatureOverflow =
    (typeof GetFieldsResponseFieldMetaSignatureOverflow)[keyof typeof GetFieldsResponseFieldMetaSignatureOverflow];
