// This file was auto-generated by Fern from our API Definition.

import * as Documenso from "../../../../../index.js";

export type GetFieldsResponseFieldMeta =
    | Documenso.documents.GetFieldsResponseFieldMeta.Signature
    | Documenso.documents.GetFieldsResponseFieldMeta.Initials
    | Documenso.documents.GetFieldsResponseFieldMeta.Name
    | Documenso.documents.GetFieldsResponseFieldMeta.Email
    | Documenso.documents.GetFieldsResponseFieldMeta.Date
    | Documenso.documents.GetFieldsResponseFieldMeta.Text
    | Documenso.documents.GetFieldsResponseFieldMeta.Number
    | Documenso.documents.GetFieldsResponseFieldMeta.Radio
    | Documenso.documents.GetFieldsResponseFieldMeta.Checkbox
    | Documenso.documents.GetFieldsResponseFieldMeta.Dropdown;

export namespace GetFieldsResponseFieldMeta {
    export interface Signature extends Documenso.documents.GetFieldsResponseFieldMetaSignature {
        type: "signature";
    }

    export interface Initials extends Documenso.documents.GetFieldsResponseFieldMetaInitials {
        type: "initials";
    }

    export interface Name extends Documenso.documents.GetFieldsResponseFieldMetaName {
        type: "name";
    }

    export interface Email extends Documenso.documents.GetFieldsResponseFieldMetaEmail {
        type: "email";
    }

    export interface Date extends Documenso.documents.GetFieldsResponseFieldMetaDate {
        type: "date";
    }

    export interface Text extends Documenso.documents.GetFieldsResponseFieldMetaText {
        type: "text";
    }

    export interface Number extends Documenso.documents.GetFieldsResponseFieldMetaNumber {
        type: "number";
    }

    export interface Radio extends Documenso.documents.GetFieldsResponseFieldMetaRadio {
        type: "radio";
    }

    export interface Checkbox extends Documenso.documents.GetFieldsResponseFieldMetaCheckbox {
        type: "checkbox";
    }

    export interface Dropdown extends Documenso.documents.GetFieldsResponseFieldMetaDropdown {
        type: "dropdown";
    }
}
