// This file was auto-generated by Fern from our API Definition.

export const UpdateManyFieldsResponseFieldsItemFieldMetaDateTextAlign = {
    Left: "left",
    Center: "center",
    Right: "right",
} as const;
export type UpdateManyFieldsResponseFieldsItemFieldMetaDateTextAlign =
    (typeof UpdateManyFieldsResponseFieldsItemFieldMetaDateTextAlign)[keyof typeof UpdateManyFieldsResponseFieldsItemFieldMetaDateTextAlign];
