// This file was auto-generated by Fern from our API Definition.

export const UpdateManyFieldsResponseFieldsItemFieldMetaInitialsTextAlign = {
    Left: "left",
    Center: "center",
    Right: "right",
} as const;
export type UpdateManyFieldsResponseFieldsItemFieldMetaInitialsTextAlign =
    (typeof UpdateManyFieldsResponseFieldsItemFieldMetaInitialsTextAlign)[keyof typeof UpdateManyFieldsResponseFieldsItemFieldMetaInitialsTextAlign];
